Public Class NCDB
    Inherits BaseDB

    Public Sub New()
        InitTables()
    End Sub

    Public Sub InitTables()
        'Creature_Root
        Dim Table As TTable
        Table = New TTable("creature_root", TableTypes.CreatureInfo)
        Tables.Add(Table)
        Table.Columns.Add(CreatureInfo_Columns.Entry, "creature_entry")
        Table.Columns.Add(CreatureInfo_Columns.Name, "name")
        Table.Columns.Add(CreatureInfo_Columns.SubName, "subname")
        Table.Columns.Add(CreatureInfo_Columns.InfoStr, "info_str")
        Table.Columns.Add(CreatureInfo_Columns.Flags, "Flags1")
        Table.Columns.Add(CreatureInfo_Columns.Type, "type")
        Table.Columns.Add(CreatureInfo_Columns.Family, "family")
        Table.Columns.Add(CreatureInfo_Columns.Rank, "rank")
        Table.Columns.Add(CreatureInfo_Columns.Unk4, "unk4")
        Table.Columns.Add(CreatureInfo_Columns.SpellDataID, "spelldataid")
        Table.Columns.Add(CreatureInfo_Columns.MaleDisplayID, "displayid")
        Table.Columns.Add(CreatureInfo_Columns.FemaleDisplayID, "displayid2")
        Table.Columns.Add(CreatureInfo_Columns.MaleDisplayID2, "displayid3")
        Table.Columns.Add(CreatureInfo_Columns.FemaleDisplayID2, "displayid4")
        Table.Columns.Add(CreatureInfo_Columns.UnknownFloat1, "unknown_float1")
        Table.Columns.Add(CreatureInfo_Columns.UnknownFloat2, "unknown_float2")
        Table.Columns.Add(CreatureInfo_Columns.Leader, "leader")

        'Creature_Template
        Table = New TTable("creature_template", TableTypes.CreatureInfo)
        Tables.Add(Table)
        Table.Columns.Add(CreatureInfo_Columns.Entry, "creature_entry")
        Table.Columns.Add(CreatureInfo_Columns.MinLevel, "minlvl")
        Table.Columns.Add(CreatureInfo_Columns.MaxLevel, "maxlvl")
        Table.Columns.Add(CreatureInfo_Columns.Size, "scale")
        Table.Columns.Add(CreatureInfo_Columns.Life, "maxhp")
        Table.Columns.Add(CreatureInfo_Columns.StartLife, "minhp")
        Table.Columns.Add(CreatureInfo_Columns.Mana, "mana")
        Table.Columns.Add(CreatureInfo_Columns.ManaType, "")
        Table.Columns.Add(CreatureInfo_Columns.Faction, "faction")
        Table.Columns.Add(CreatureInfo_Columns.MinDamage, "mainmindmg")
        Table.Columns.Add(CreatureInfo_Columns.MaxDamage, "mainmaxdmg")
        Table.Columns.Add(CreatureInfo_Columns.MinRangedDamage, "rangedmindmg")
        Table.Columns.Add(CreatureInfo_Columns.MaxRangedDamage, "rangedmaxdmg")
        Table.Columns.Add(CreatureInfo_Columns.Armor, "armor")
        Table.Columns.Add(CreatureInfo_Columns.ResHoly, "resistance1")
        Table.Columns.Add(CreatureInfo_Columns.ResFire, "resistance2")
        Table.Columns.Add(CreatureInfo_Columns.ResNature, "resistance3")
        Table.Columns.Add(CreatureInfo_Columns.ResFrost, "resistance4")
        Table.Columns.Add(CreatureInfo_Columns.ResShadow, "resistance5")
        Table.Columns.Add(CreatureInfo_Columns.ResArcane, "resistance6")
        Table.Columns.Add(CreatureInfo_Columns.WalkSpeed, "walkspeed")
        Table.Columns.Add(CreatureInfo_Columns.RunSpeed, "runspeed")
        Table.Columns.Add(CreatureInfo_Columns.FlySpeed, "flyspeed")
        Table.Columns.Add(CreatureInfo_Columns.RespawnTime, "respawntime")
        Table.Columns.Add(CreatureInfo_Columns.BaseAttackSpeed, "mainattacktime")
        Table.Columns.Add(CreatureInfo_Columns.BaseRangedAttackSpeed, "rangedattacktime")
        Table.Columns.Add(CreatureInfo_Columns.CombatReach, "combatreach")
        Table.Columns.Add(CreatureInfo_Columns.BondingRadius, "boundingradius")
        Table.Columns.Add(CreatureInfo_Columns.NpcFlags, "npcflags")
        Table.Columns.Add(CreatureInfo_Columns.Loot, "")
        Table.Columns.Add(CreatureInfo_Columns.SkinLoot, "")
        Table.Columns.Add(CreatureInfo_Columns.PickpocketLoot, "")
        Table.Columns.Add(CreatureInfo_Columns.EquipmentEntry, "equipment_entry")

        'Creature_Spawns
        Table = New TTable("creature_spawns", TableTypes.CreatureSpawn)
        Tables.Add(Table)
        Table.Columns.Add(CreatureSpawn_Columns.EquipmentEntry, "equipment_entry")
        Table.Columns.Add(CreatureSpawn_Columns.ID, "spawnid")
        Table.Columns.Add(CreatureSpawn_Columns.Entry, "creature_entry")
        Table.Columns.Add(CreatureSpawn_Columns.Map, "map")
        Table.Columns.Add(CreatureSpawn_Columns.PositionX, "position_x")
        Table.Columns.Add(CreatureSpawn_Columns.PositionY, "position_y")
        Table.Columns.Add(CreatureSpawn_Columns.PositionZ, "position_z")
        Table.Columns.Add(CreatureSpawn_Columns.Orientation, "orientation")
        Table.Columns.Add(CreatureSpawn_Columns.Range, "spawndist")
        Table.Columns.Add(CreatureSpawn_Columns.MoveType, "movetype")
        Table.Columns.Add(CreatureSpawn_Columns.Model, "displayid")
        Table.Columns.Add(CreatureSpawn_Columns.Faction, "faction")
        Table.Columns.Add(CreatureSpawn_Columns.Mount, "mount")
        Table.Columns.Add(CreatureSpawn_Columns.Flags, "flags")
        Table.Columns.Add(CreatureSpawn_Columns.Bytes0, "bytes0")
        Table.Columns.Add(CreatureSpawn_Columns.Bytes1, "bytes1")
        Table.Columns.Add(CreatureSpawn_Columns.Bytes2, "bytes2")
        Table.Columns.Add(CreatureSpawn_Columns.EmoteState, "emote_state")
        Table.Columns.Add(CreatureSpawn_Columns.StandState, "standstate")

        'creature_equip_template
        Table = New TTable("creature_equip_template", TableTypes.CreatureSpawn)
        Tables.Add(Table)
        Table.Columns.Add(CreatureSpawn_Columns.EquipmentEntry, "equipment_entry")
        Table.Columns.Add(CreatureSpawn_Columns.equipslot1, "itemId1")
        Table.Columns.Add(CreatureSpawn_Columns.equipslot2, "ItemId2")
        Table.Columns.Add(CreatureSpawn_Columns.equipslot3, "ItemId3")

        'Gameobject_Root
        Table = New TTable("gameobject_root", TableTypes.GameobjectInfo)
        Tables.Add(Table)
        Table.Columns.Add(GameobjectInfo_Columns.Entry, "gameobject_entry")
        Table.Columns.Add(GameobjectInfo_Columns.Type, "Type")
        Table.Columns.Add(GameobjectInfo_Columns.Model, "displayid")
        Table.Columns.Add(GameobjectInfo_Columns.Name, "Name")
        Table.Columns.Add(GameobjectInfo_Columns.Field0, "field0")
        Table.Columns.Add(GameobjectInfo_Columns.Field1, "field1")
        Table.Columns.Add(GameobjectInfo_Columns.Field2, "field2")
        Table.Columns.Add(GameobjectInfo_Columns.Field3, "field3")
        Table.Columns.Add(GameobjectInfo_Columns.Field4, "field4")
        Table.Columns.Add(GameobjectInfo_Columns.Field5, "field5")
        Table.Columns.Add(GameobjectInfo_Columns.Field6, "field6")
        Table.Columns.Add(GameobjectInfo_Columns.Field7, "field7")
        Table.Columns.Add(GameobjectInfo_Columns.Field8, "field8")
        Table.Columns.Add(GameobjectInfo_Columns.Field9, "field9")
        Table.Columns.Add(GameobjectInfo_Columns.Field10, "field10")
        Table.Columns.Add(GameobjectInfo_Columns.Field11, "field11")
        Table.Columns.Add(GameobjectInfo_Columns.Field12, "field12")
        Table.Columns.Add(GameobjectInfo_Columns.Field13, "field13")
        Table.Columns.Add(GameobjectInfo_Columns.Field14, "field14")
        Table.Columns.Add(GameobjectInfo_Columns.Field15, "field15")
        Table.Columns.Add(GameobjectInfo_Columns.Field16, "field16")
        Table.Columns.Add(GameobjectInfo_Columns.Field17, "field17")
        Table.Columns.Add(GameobjectInfo_Columns.Field18, "field18")
        Table.Columns.Add(GameobjectInfo_Columns.Field19, "field19")
        Table.Columns.Add(GameobjectInfo_Columns.Field20, "field20")
        Table.Columns.Add(GameobjectInfo_Columns.Field21, "field21")
        Table.Columns.Add(GameobjectInfo_Columns.Field22, "field22")
        Table.Columns.Add(GameobjectInfo_Columns.Field23, "field23")
        Table.Columns.Add(GameobjectInfo_Columns.Scale, "Scale")

        'Gameobject_Addons
        Table = New TTable("gameobject_addons", TableTypes.GameobjectInfo)
        Tables.Add(Table)
        Table.Columns.Add(GameobjectInfo_Columns.Entry, "gameobject_entry")
        Table.Columns.Add(GameobjectInfo_Columns.Faction, "faction")
        Table.Columns.Add(GameobjectInfo_Columns.Flags, "flags")
        Table.Columns.Add(GameobjectInfo_Columns.RespawnTime, "respawntimesecs")
        Table.Columns.Add(GameobjectInfo_Columns.CastBarCaption, "castbarcaption")
        Table.Columns.Add(GameobjectInfo_Columns.AnimProgress, "animprogress")

        'Gameobject_Spawns
        Table = New TTable("gameobject_spawns", TableTypes.GameobjectSpawn)
        Tables.Add(Table)
        Table.Columns.Add(GameobjectSpawn_Columns.ID, "spawnid")
        Table.Columns.Add(GameobjectSpawn_Columns.Entry, "gameobject_entry")
        Table.Columns.Add(GameobjectSpawn_Columns.Map, "map")
        Table.Columns.Add(GameobjectSpawn_Columns.PositionX, "position_x")
        Table.Columns.Add(GameobjectSpawn_Columns.PositionY, "position_y")
        Table.Columns.Add(GameobjectSpawn_Columns.PositionZ, "position_z")
        Table.Columns.Add(GameobjectSpawn_Columns.Orientation, "Facing")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation1, "orientation1")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation2, "orientation2")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation3, "orientation3")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation4, "orientation4")
        Table.Columns.Add(GameobjectSpawn_Columns.State, "State")
        Table.Columns.Add(GameobjectSpawn_Columns.Flags, "Flags")
        Table.Columns.Add(GameobjectSpawn_Columns.Faction, "Faction")
        Table.Columns.Add(GameobjectSpawn_Columns.Scale, "Scale")

        'Items_Root
        Table = New TTable("item_root", TableTypes.Items)
        Tables.Add(Table)
        Table.Columns.Add(Item_Columns.Entry, "item_entry")
        Table.Columns.Add(Item_Columns.Classe, "class")
        Table.Columns.Add(Item_Columns.SubClass, "subclass")
        Table.Columns.Add(Item_Columns.Field4, "field4")
        Table.Columns.Add(Item_Columns.Name1, "name1")
        Table.Columns.Add(Item_Columns.Name2, "name2")
        Table.Columns.Add(Item_Columns.Name3, "name3")
        Table.Columns.Add(Item_Columns.Name4, "name4")
        Table.Columns.Add(Item_Columns.DisplayID, "displayid")
        Table.Columns.Add(Item_Columns.Quality, "quality")
        Table.Columns.Add(Item_Columns.Flags, "flags")
        Table.Columns.Add(Item_Columns.Buyprice, "buyprice")
        Table.Columns.Add(Item_Columns.Sellprice, "sellprice")
        Table.Columns.Add(Item_Columns.InventoryType, "inventorytype")
        Table.Columns.Add(Item_Columns.AllowableClass, "allowableclass")
        Table.Columns.Add(Item_Columns.AllowableRace, "allowablerace")
        Table.Columns.Add(Item_Columns.ItemLevel, "itemlevel")
        Table.Columns.Add(Item_Columns.RequiredLevel, "requiredlevel")
        Table.Columns.Add(Item_Columns.RequiredSkill, "RequiredSkill")
        Table.Columns.Add(Item_Columns.RequiredSkillRank, "RequiredSkillRank")
        Table.Columns.Add(Item_Columns.RequiredSubRank, "RequiredSkillSubRank")
        Table.Columns.Add(Item_Columns.RequiredPlayerRank1, "RequiredPlayerRank1")
        Table.Columns.Add(Item_Columns.RequiredPlayerRank2, "RequiredPlayerRank2")
        Table.Columns.Add(Item_Columns.RequiredFaction, "RequiredFaction")
        Table.Columns.Add(Item_Columns.RequiredFactionStanding, "RequiredFactionStanding")
        Table.Columns.Add(Item_Columns.Unique, "Unique")
        Table.Columns.Add(Item_Columns.MaxCount, "maxcount")
        Table.Columns.Add(Item_Columns.ContainerSlots, "ContainerSlots")
        Table.Columns.Add(Item_Columns.Stat_Type1, "stat_type1")
        Table.Columns.Add(Item_Columns.Stat_Value1, "stat_value1")
        Table.Columns.Add(Item_Columns.Stat_Type2, "stat_type2")
        Table.Columns.Add(Item_Columns.Stat_Value2, "stat_value2")
        Table.Columns.Add(Item_Columns.Stat_Type3, "stat_type3")
        Table.Columns.Add(Item_Columns.Stat_Value3, "stat_value3")
        Table.Columns.Add(Item_Columns.Stat_Type4, "stat_type4")
        Table.Columns.Add(Item_Columns.Stat_Value4, "stat_value4")
        Table.Columns.Add(Item_Columns.Stat_Type5, "stat_type5")
        Table.Columns.Add(Item_Columns.Stat_Value5, "stat_value5")
        Table.Columns.Add(Item_Columns.Stat_Type6, "stat_type6")
        Table.Columns.Add(Item_Columns.Stat_Value6, "stat_value6")
        Table.Columns.Add(Item_Columns.Stat_Type7, "stat_type7")
        Table.Columns.Add(Item_Columns.Stat_Value7, "stat_value7")
        Table.Columns.Add(Item_Columns.Stat_Type8, "stat_type8")
        Table.Columns.Add(Item_Columns.Stat_Value8, "stat_value8")
        Table.Columns.Add(Item_Columns.Stat_Type9, "stat_type9")
        Table.Columns.Add(Item_Columns.Stat_Value9, "stat_value9")
        Table.Columns.Add(Item_Columns.Stat_Type10, "stat_type10")
        Table.Columns.Add(Item_Columns.Stat_Value10, "stat_value10")
        Table.Columns.Add(Item_Columns.Dmg_Min1, "dmg_min1")
        Table.Columns.Add(Item_Columns.Dmg_Max1, "dmg_max1")
        Table.Columns.Add(Item_Columns.Dmg_Type1, "dmg_type1")
        Table.Columns.Add(Item_Columns.Dmg_Min2, "dmg_min2")
        Table.Columns.Add(Item_Columns.Dmg_Max2, "dmg_max2")
        Table.Columns.Add(Item_Columns.Dmg_Type2, "dmg_type2")
        Table.Columns.Add(Item_Columns.Dmg_Min3, "dmg_min3")
        Table.Columns.Add(Item_Columns.Dmg_Max3, "dmg_max3")
        Table.Columns.Add(Item_Columns.Dmg_Type3, "dmg_type3")
        Table.Columns.Add(Item_Columns.Dmg_Min4, "dmg_min4")
        Table.Columns.Add(Item_Columns.Dmg_Max4, "dmg_max4")
        Table.Columns.Add(Item_Columns.Dmg_Type4, "dmg_type4")
        Table.Columns.Add(Item_Columns.Dmg_Min5, "dmg_min5")
        Table.Columns.Add(Item_Columns.Dmg_Max5, "dmg_max5")
        Table.Columns.Add(Item_Columns.Dmg_Type5, "dmg_type5")
        Table.Columns.Add(Item_Columns.Armor, "armor")
        Table.Columns.Add(Item_Columns.HolyRes, "holy_res")
        Table.Columns.Add(Item_Columns.FireRes, "fire_res")
        Table.Columns.Add(Item_Columns.NatureRes, "nature_res")
        Table.Columns.Add(Item_Columns.FrostRes, "frost_res")
        Table.Columns.Add(Item_Columns.ShadowRes, "shadow_res")
        Table.Columns.Add(Item_Columns.ArcaneRes, "arcane_res")
        Table.Columns.Add(Item_Columns.Delay, "delay")
        Table.Columns.Add(Item_Columns.AmmoType, "ammo_type")
        Table.Columns.Add(Item_Columns.Range, "range")
        Table.Columns.Add(Item_Columns.SpellID_1, "spellid_1")
        Table.Columns.Add(Item_Columns.SpellTrigger_1, "spelltrigger_1")
        Table.Columns.Add(Item_Columns.SpellCharges_1, "spellcharges_1")
        Table.Columns.Add(Item_Columns.SpellCooldown_1, "spellcooldown_1")
        Table.Columns.Add(Item_Columns.SpellCategory_1, "spellcategory_1")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_1, "spellcategorycooldown_1")
        Table.Columns.Add(Item_Columns.SpellID_2, "spellid_2")
        Table.Columns.Add(Item_Columns.SpellTrigger_2, "spelltrigger_2")
        Table.Columns.Add(Item_Columns.SpellCharges_2, "spellcharges_2")
        Table.Columns.Add(Item_Columns.SpellCooldown_2, "spellcooldown_2")
        Table.Columns.Add(Item_Columns.SpellCategory_2, "spellcategory_2")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_2, "spellcategorycooldown_2")
        Table.Columns.Add(Item_Columns.SpellID_3, "spellid_3")
        Table.Columns.Add(Item_Columns.SpellTrigger_3, "spelltrigger_3")
        Table.Columns.Add(Item_Columns.SpellCharges_3, "spellcharges_3")
        Table.Columns.Add(Item_Columns.SpellCooldown_3, "spellcooldown_3")
        Table.Columns.Add(Item_Columns.SpellCategory_3, "spellcategory_3")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_3, "spellcategorycooldown_3")
        Table.Columns.Add(Item_Columns.SpellID_4, "spellid_4")
        Table.Columns.Add(Item_Columns.SpellTrigger_4, "spelltrigger_4")
        Table.Columns.Add(Item_Columns.SpellCharges_4, "spellcharges_4")
        Table.Columns.Add(Item_Columns.SpellCooldown_4, "spellcooldown_4")
        Table.Columns.Add(Item_Columns.SpellCategory_4, "spellcategory_4")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_4, "spellcategorycooldown_4")
        Table.Columns.Add(Item_Columns.SpellID_5, "spellid_5")
        Table.Columns.Add(Item_Columns.SpellTrigger_5, "spelltrigger_5")
        Table.Columns.Add(Item_Columns.SpellCharges_5, "spellcharges_5")
        Table.Columns.Add(Item_Columns.SpellCooldown_5, "spellcooldown_5")
        Table.Columns.Add(Item_Columns.SpellCategory_5, "spellcategory_5")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_5, "spellcategorycooldown_5")
        Table.Columns.Add(Item_Columns.Bonding, "bonding")
        Table.Columns.Add(Item_Columns.Description, "description")
        Table.Columns.Add(Item_Columns.PageID, "page_id")
        Table.Columns.Add(Item_Columns.PageLanguage, "page_language")
        Table.Columns.Add(Item_Columns.PageMaterial, "page_material")
        Table.Columns.Add(Item_Columns.QuestID, "quest_id")
        Table.Columns.Add(Item_Columns.LockID, "lock_id")
        Table.Columns.Add(Item_Columns.LockMaterial, "lock_material")
        Table.Columns.Add(Item_Columns.SheathID, "sheathID")
        Table.Columns.Add(Item_Columns.RandomProp, "randomprop")
        Table.Columns.Add(Item_Columns.RandomSuffix, "randomsuffix")
        Table.Columns.Add(Item_Columns.Block, "block")
        Table.Columns.Add(Item_Columns.ItemSet, "itemset")
        Table.Columns.Add(Item_Columns.MaxDurability, "MaxDurability")
        Table.Columns.Add(Item_Columns.ZoneNameID, "ZoneNameID")
        Table.Columns.Add(Item_Columns.MapID, "mapid")
        Table.Columns.Add(Item_Columns.BagFamily, "bagfamily")
        Table.Columns.Add(Item_Columns.TotemCategory, "TotemCategory")
        Table.Columns.Add(Item_Columns.SocketColor_1, "socket_color_1")
        Table.Columns.Add(Item_Columns.SocketContent_1, "socket_content_1")
        Table.Columns.Add(Item_Columns.SocketColor_2, "socket_color_2")
        Table.Columns.Add(Item_Columns.SocketContent_2, "socket_content_2")
        Table.Columns.Add(Item_Columns.SocketColor_3, "socket_color_3")
        Table.Columns.Add(Item_Columns.SocketContent_3, "socket_content_3")
        Table.Columns.Add(Item_Columns.SocketBonus, "socket_bonus")
        Table.Columns.Add(Item_Columns.GemProperties, "GemProperties")
        Table.Columns.Add(Item_Columns.ReqDisenchantSkill, "ReqDisenchantSkill")
        Table.Columns.Add(Item_Columns.ArmorDamageModifier, "armorDamageModifier")
        Table.Columns.Add(Item_Columns.ExistingDuration, "ExistingDuration")

        'Loot_Creatures
        Table = New TTable("loot_creatures", TableTypes.CreatureLoot)
        Tables.Add(Table)
        Table.Columns.Add(CreatureLoot_Columns.Entry, "creature_entry")
        Table.Columns.Add(CreatureLoot_Columns.Item, "drop_item_entry")
        Table.Columns.Add(CreatureLoot_Columns.Group, "groupid")
        Table.Columns.Add(CreatureLoot_Columns.Chance, "percentchance")
        Table.Columns.Add(CreatureLoot_Columns.HeroicChance, "heroicpercentchance")
        Table.Columns.Add(CreatureLoot_Columns.Min, "mincount")
        Table.Columns.Add(CreatureLoot_Columns.Max, "maxcount")
        Table.Columns.Add(CreatureLoot_Columns.FFA, "ffa_loot")
        Table.Columns.Add(CreatureLoot_Columns.Condition, "loot_condition")
        Table.Columns.Add(CreatureLoot_Columns.ConditionValue1, "condition_value_1")
        Table.Columns.Add(CreatureLoot_Columns.ConditionValue2, "condition_value_2")

        'Loot_Gameobject
        Table = New TTable("loot_gameobject", TableTypes.GameobjectLoot)
        Tables.Add(Table)
        Table.Columns.Add(GameobjectLoot_Columns.Entry, "loot_entry")
        Table.Columns.Add(GameobjectLoot_Columns.Item, "drop_item_entry")
        Table.Columns.Add(GameobjectLoot_Columns.Group, "groupid")
        Table.Columns.Add(GameobjectLoot_Columns.Chance, "percentchance")
        Table.Columns.Add(GameobjectLoot_Columns.HeroicChance, "heroicpercentchance")
        Table.Columns.Add(GameobjectLoot_Columns.Min, "mincount")
        Table.Columns.Add(GameobjectLoot_Columns.Max, "maxcount")
        Table.Columns.Add(GameobjectLoot_Columns.FFA, "ffa_loot")
        Table.Columns.Add(GameobjectLoot_Columns.Condition, "loot_condition")
        Table.Columns.Add(GameobjectLoot_Columns.ConditionValue1, "condition_value_1")
        Table.Columns.Add(GameobjectLoot_Columns.ConditionValue2, "condition_value_2")

        'Quests_Root
        Table = New TTable("quests_root", TableTypes.Quests)
        Tables.Add(Table)
        Table.Columns.Add(Quest_Columns.ID, "QuestId")
        Table.Columns.Add(Quest_Columns.IsActive, "IsActive")
        Table.Columns.Add(Quest_Columns.LevelNormal, "QuestLevel")
        Table.Columns.Add(Quest_Columns.Zone, "ZoneIdOrSort")
        Table.Columns.Add(Quest_Columns.Type, "Type")
        Table.Columns.Add(Quest_Columns.SuggestedPlayers, "SuggestedPlayers")
        Table.Columns.Add(Quest_Columns.ReqReputation1Faction, "ObjRepFaction1")
        Table.Columns.Add(Quest_Columns.ReqReputation1, "ObjRepValue1")
        Table.Columns.Add(Quest_Columns.ReqReputation2Faction, "ObjRepFaction2")
        Table.Columns.Add(Quest_Columns.ReqReputation2, "ObjRepValue2")
        Table.Columns.Add(Quest_Columns.NextQuest, "NextQuestInChain")
        Table.Columns.Add(Quest_Columns.RewardGold, "RewMoney")
        Table.Columns.Add(Quest_Columns.MoneyAtMaxLevel, "MoneyAtMaxLevel")
        Table.Columns.Add(Quest_Columns.RewardSpell, "RewSpell")
        Table.Columns.Add(Quest_Columns.RewardSpellCast, "CastSpell")
        'Table.Columns.Add(Quest_Columns.IsActive, "unknown3")
        Table.Columns.Add(Quest_Columns.ObjectiveDeliver, "srcItem")
        Table.Columns.Add(Quest_Columns.Flags, "Flags")
        'Table.Columns.Add(Quest_Columns.IsActive, "unknown4")
        'Table.Columns.Add(Quest_Columns.IsActive, "unknown5")
        Table.Columns.Add(Quest_Columns.RewTitleId, "RewTitleId")
        Table.Columns.Add(Quest_Columns.RewardTalents, "rewtalents")
        Table.Columns.Add(Quest_Columns.RewardStaticItem1, "RewItemId0")
        Table.Columns.Add(Quest_Columns.RewardStaticItem1Count, "RewItemCount0")
        Table.Columns.Add(Quest_Columns.RewardStaticItem2, "RewItemId1")
        Table.Columns.Add(Quest_Columns.RewardStaticItem2Count, "RewItemCount1")
        Table.Columns.Add(Quest_Columns.RewardStaticItem3, "RewItemId2")
        Table.Columns.Add(Quest_Columns.RewardStaticItem3Count, "RewItemCount2")
        Table.Columns.Add(Quest_Columns.RewardStaticItem4, "RewItemId3")
        Table.Columns.Add(Quest_Columns.RewardStaticItem4Count, "RewItemCount3")
        Table.Columns.Add(Quest_Columns.RewardItem1, "RewChoiceItemId0")
        Table.Columns.Add(Quest_Columns.RewardItem1Count, "RewChoiceItemCount0")
        Table.Columns.Add(Quest_Columns.RewardItem2, "RewChoiceItemId1")
        Table.Columns.Add(Quest_Columns.RewardItem2Count, "RewChoiceItemCount1")
        Table.Columns.Add(Quest_Columns.RewardItem3, "RewChoiceItemId2")
        Table.Columns.Add(Quest_Columns.RewardItem3Count, "RewChoiceItemCount2")
        Table.Columns.Add(Quest_Columns.RewardItem4, "RewChoiceItemId3")
        Table.Columns.Add(Quest_Columns.RewardItem4Count, "RewChoiceItemCount3")
        Table.Columns.Add(Quest_Columns.RewardItem5, "RewChoiceItemId4")
        Table.Columns.Add(Quest_Columns.RewardItem5Count, "RewChoiceItemCount4")
        Table.Columns.Add(Quest_Columns.RewardItem6, "RewChoiceItemId5")
        Table.Columns.Add(Quest_Columns.RewardItem6Count, "RewChoiceItemCount5")
        Table.Columns.Add(Quest_Columns.PointMap, "PointMapId")
        Table.Columns.Add(Quest_Columns.PointX, "PointX")
        Table.Columns.Add(Quest_Columns.PointY, "PointY")
        Table.Columns.Add(Quest_Columns.PointOpt, "PointOpt")
        Table.Columns.Add(Quest_Columns.Title, "Title")
        Table.Columns.Add(Quest_Columns.TextObjectives, "Objectives")
        Table.Columns.Add(Quest_Columns.TextDescription, "Details")
        Table.Columns.Add(Quest_Columns.TextEnd, "EndText")
        Table.Columns.Add(Quest_Columns.ObjectiveKill1, "ObjInteractId0")
        Table.Columns.Add(Quest_Columns.ObjectiveKill1Count, "ObjInteractCount0")
        Table.Columns.Add(Quest_Columns.ObjectiveKill2, "ObjInteractId1")
        Table.Columns.Add(Quest_Columns.ObjectiveKill2Count, "ObjInteractCount1")
        Table.Columns.Add(Quest_Columns.ObjectiveKill3, "ObjInteractId2")
        Table.Columns.Add(Quest_Columns.ObjectiveKill3Count, "ObjInteractCount2")
        Table.Columns.Add(Quest_Columns.ObjectiveKill4, "ObjInteractId3")
        Table.Columns.Add(Quest_Columns.ObjectiveKill4Count, "ObjInteractCount3")
        Table.Columns.Add(Quest_Columns.ObjectiveItem1, "ObjItemId0")
        Table.Columns.Add(Quest_Columns.ObjectiveItem1Count, "ObjItemCount0")
        Table.Columns.Add(Quest_Columns.ObjectiveItem2, "ObjItemId1")
        Table.Columns.Add(Quest_Columns.ObjectiveItem2Count, "ObjItemCount1")
        Table.Columns.Add(Quest_Columns.ObjectiveItem3, "ObjItemId2")
        Table.Columns.Add(Quest_Columns.ObjectiveItem3Count, "ObjItemCount2")
        Table.Columns.Add(Quest_Columns.ObjectiveItem4, "ObjItemId3")
        Table.Columns.Add(Quest_Columns.ObjectiveItem4Count, "ObjItemCount3")
        Table.Columns.Add(Quest_Columns.ObjectiveText1, "ObjText0")
        Table.Columns.Add(Quest_Columns.ObjectiveText2, "ObjText1")
        Table.Columns.Add(Quest_Columns.ObjectiveText3, "ObjText2")
        Table.Columns.Add(Quest_Columns.ObjectiveText4, "ObjText3")

        'Quests_Settings
        Table = New TTable("quests_settings", TableTypes.Quests)
        Tables.Add(Table)
        Table.Columns.Add(Quest_Columns.ID, "QuestId")
        Table.Columns.Add(Quest_Columns.SpecialFlags, "SpecialFlags")
        'Table.Columns.Add(Quest_Columns.PrevQuest, "PrevQuestID")
        'Table.Columns.Add(Quest_Columns.NextQuest, "NextQuestID")
        'Table.Columns.Add(Quest_Columns.ID, "ExclusiveGroup")
        Table.Columns.Add(Quest_Columns.TimeLimit, "TimeLimit")
        Table.Columns.Add(Quest_Columns.TextComplete, "CompletionText")
        Table.Columns.Add(Quest_Columns.TextIncomplete, "IncompleteText")
        Table.Columns.Add(Quest_Columns.Repeatable, "Repeatable")

        'Quests_Rewards
        Table = New TTable("quests_rewards", TableTypes.Quests)
        Tables.Add(Table)
        Table.Columns.Add(Quest_Columns.ID, "QuestId")
        Table.Columns.Add(Quest_Columns.RewardXP, "RewXP")
        Table.Columns.Add(Quest_Columns.RewardReputation1Faction, "RewRepFaction0")
        Table.Columns.Add(Quest_Columns.RewardReputation1, "RewRepValue0")
        Table.Columns.Add(Quest_Columns.RewardReputation2Faction, "RewRepFaction1")
        Table.Columns.Add(Quest_Columns.RewardReputation2, "RewRepValue1")
        Table.Columns.Add(Quest_Columns.RewardReputation3Faction, "RewRepFaction2")
        Table.Columns.Add(Quest_Columns.RewardReputation3, "RewRepValue2")

        'Quests_Objectives
        Table = New TTable("quests_objectives", TableTypes.Quests)
        Tables.Add(Table)
        Table.Columns.Add(Quest_Columns.ID, "QuestId")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger1, "ObjTrigger0")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger2, "ObjTrigger1")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger3, "ObjTrigger2")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger4, "ObjTrigger3")
        Table.Columns.Add(Quest_Columns.ObjectiveCast1, "ObjSpellCast0")
        Table.Columns.Add(Quest_Columns.ObjectiveCast2, "ObjSpellCast1")
        Table.Columns.Add(Quest_Columns.ObjectiveCast3, "ObjSpellCast2")
        Table.Columns.Add(Quest_Columns.ObjectiveCast4, "ObjSpellCast3")

        'Quests_Requirements
        Table = New TTable("quests_requirements", TableTypes.Quests)
        Tables.Add(Table)
        Table.Columns.Add(Quest_Columns.ID, "QuestId")
        Table.Columns.Add(Quest_Columns.LevelStart, "ReqLevel")
        Table.Columns.Add(Quest_Columns.ReqRace, "ReqRaces")
        Table.Columns.Add(Quest_Columns.ReqClass, "ReqClass")
        Table.Columns.Add(Quest_Columns.ReqTradeSkill, "ReqTradeSkill")
        Table.Columns.Add(Quest_Columns.ReqTradeSkillValue, "ReqTradeSkillValue")
        Table.Columns.Add(Quest_Columns.ReqQuest1, "ReqQuests0")
        Table.Columns.Add(Quest_Columns.ReqQuest2, "ReqQuests1")
        Table.Columns.Add(Quest_Columns.ReqQuest3, "ReqQuests2")
        Table.Columns.Add(Quest_Columns.ReqQuest4, "ReqQuests3")

        'Battleground_Battlemaster
        Table = New TTable("battleground_battlemaster", TableTypes.BattleGround_BattleMaster)
        Tables.Add(Table)
        Table.Columns.Add(BattleGround_Columns.creature, "creature_entry")
        Table.Columns.Add(BattleGround_Columns.battleground, "battleground_entry")

        'Battleground_Template
        Table = New TTable("battleground_template", TableTypes.BattleGround_Template)
        Tables.Add(Table)
        Table.Columns.Add(BattleGround_Columns.battleground, "battleground_entry")
        Table.Columns.Add(BattleGround_Columns.Name, "Name")
        Table.Columns.Add(BattleGround_Columns.Type, "Type")
        Table.Columns.Add(BattleGround_Columns.Map1, "Map1")
        Table.Columns.Add(BattleGround_Columns.Map2, "Map2")
        Table.Columns.Add(BattleGround_Columns.Map3, "Map3")
        Table.Columns.Add(BattleGround_Columns.MinPlayersPerTeam, "MinPlayersPerTeam")
        Table.Columns.Add(BattleGround_Columns.MaxPlayersPerTeam, "MaxPlayersPerTeam")
        Table.Columns.Add(BattleGround_Columns.MinLvl, "MinLvl")
        Table.Columns.Add(BattleGround_Columns.MaxLvl, "MaxLvl")
        Table.Columns.Add(BattleGround_Columns.Band, "Band")
        Table.Columns.Add(BattleGround_Columns.AllianceStartLoc, "AllianceStartLoc")
        Table.Columns.Add(BattleGround_Columns.AllianceStartO, "AllianceStartO")
        Table.Columns.Add(BattleGround_Columns.HordeStartLoc, "HordeStartLoc")
        Table.Columns.Add(BattleGround_Columns.HordeStartO, "HordeStartO")
        Table.Columns.Add(BattleGround_Columns.IsActive, "IsActive")

        'AreaTrigger_InvolvedRelation
        Table = New TTable("areatrigger_involvedrelation", TableTypes.AreaTrigger_InvolvedRelation)
        Tables.Add(Table)
        Table.Columns.Add(AreaTrigger_Columns.TriggerID, "TriggerID")
        Table.Columns.Add(AreaTrigger_Columns.quest, "quest")

        'AreaTrigger_Tavern
        Table = New TTable("areatrigger_tavern", TableTypes.AreaTrigger_Tavern)
        Tables.Add(Table)
        Table.Columns.Add(AreaTrigger_Columns.TriggerID, "TriggerID")

        'AreaTrigger_Template
        Table = New TTable("areatriggers_template", TableTypes.AreaTrigger_Template)
        Tables.Add(Table)
        Table.Columns.Add(AreaTrigger_Columns.TriggerID, "TriggerID")
        Table.Columns.Add(AreaTrigger_Columns.type, "type")
        Table.Columns.Add(AreaTrigger_Columns.name, "name")
        Table.Columns.Add(AreaTrigger_Columns.position_map, "position_map")
        Table.Columns.Add(AreaTrigger_Columns.position_x, "position_x")
        Table.Columns.Add(AreaTrigger_Columns.position_y, "position_y")
        Table.Columns.Add(AreaTrigger_Columns.position_z, "position_z")
        Table.Columns.Add(AreaTrigger_Columns.target_map, "target_map")
        Table.Columns.Add(AreaTrigger_Columns.target_screen, "target_screen")
        Table.Columns.Add(AreaTrigger_Columns.target_position_x, "target_position_x")
        Table.Columns.Add(AreaTrigger_Columns.target_position_y, "target_position_y")
        Table.Columns.Add(AreaTrigger_Columns.target_position_z, "target_position_z")
        Table.Columns.Add(AreaTrigger_Columns.target_orientation, "target_orientation")
        Table.Columns.Add(AreaTrigger_Columns.required_item, "required_item")
        Table.Columns.Add(AreaTrigger_Columns.required_item2, "required_item2")
        Table.Columns.Add(AreaTrigger_Columns.heroic_key, "heroic_key")
        Table.Columns.Add(AreaTrigger_Columns.heroic_key2, "heroic_key2")
        Table.Columns.Add(AreaTrigger_Columns.required_quest_done, "required_quest_done")
        Table.Columns.Add(AreaTrigger_Columns.required_failed_text, "required_failed_text")
        Table.Columns.Add(AreaTrigger_Columns.required_level, "required_level")

        'Quests_Creature_Starter
        Table = New TTable("quests_creature_starter", TableTypes.QuestStartersCreature)
        Tables.Add(Table)
        Table.Columns.Add(QuestStarter_Columns.Type, "-1") 'hardcoded to value 1 (creature)
        Table.Columns.Add(QuestStarter_Columns.TypeID, "creature_entry")
        Table.Columns.Add(QuestStarter_Columns.QuestID, "QuestId")

        'Quests_Gameobject_Starter
        Table = New TTable("quests_gameobject_starter", TableTypes.QuestStartersGameobject)
        Tables.Add(Table)
        Table.Columns.Add(QuestStarter_Columns.Type, "-2") 'hardcoded to value 2 (gameobject)
        Table.Columns.Add(QuestStarter_Columns.TypeID, "gameobject_entry")
        Table.Columns.Add(QuestStarter_Columns.QuestID, "QuestId")

        'Quests_Creature_Starter
        Table = New TTable("quests_creature_finisher", TableTypes.QuestFinishersCreature)
        Tables.Add(Table)
        Table.Columns.Add(QuestFinisher_Columns.Type, "-1") 'hardcoded to value 1 (creature)
        Table.Columns.Add(QuestFinisher_Columns.TypeID, "creature_entry")
        Table.Columns.Add(QuestFinisher_Columns.QuestID, "QuestId")

        'Quests_Gameobject_Starter
        Table = New TTable("quests_gameobject_finisher", TableTypes.QuestFinishersGameobject)
        Tables.Add(Table)
        Table.Columns.Add(QuestFinisher_Columns.Type, "-2") 'hardcoded to value 2 (gameobject)
        Table.Columns.Add(QuestFinisher_Columns.TypeID, "gameobject_entry")
        Table.Columns.Add(QuestFinisher_Columns.QuestID, "QuestId")

        'Spells_Teleport_Coords
        Table = New TTable("spells_teleport_coords", TableTypes.SpellTeleportCoords)
        Tables.Add(Table)
        Table.Columns.Add(SpellTeleportCoords_Columns.ID, "spellid")
        Table.Columns.Add(SpellTeleportCoords_Columns.Name, "name")
        Table.Columns.Add(SpellTeleportCoords_Columns.Map, "mapId")
        Table.Columns.Add(SpellTeleportCoords_Columns.PosX, "position_x")
        Table.Columns.Add(SpellTeleportCoords_Columns.PosY, "position_y")
        Table.Columns.Add(SpellTeleportCoords_Columns.PosZ, "position_z")
        Table.Columns.Add(SpellTeleportCoords_Columns.ToTrigger, "totrigger")

        'Gameobject_Quest_Item_Binding
        Table = New TTable("gameobject_quest_item_binding", TableTypes.GameObjectQuestAssociation)
        Tables.Add(Table)
        Table.Columns.Add(GameObjectQuestAssociation_Columns.Entry, "gameobject_entry")
        Table.Columns.Add(GameObjectQuestAssociation_Columns.Quest, "QuestId")
        Table.Columns.Add(GameObjectQuestAssociation_Columns.Item, "item_entry")
        Table.Columns.Add(GameObjectQuestAssociation_Columns.ItemCount, "item_count")

        'Npc_Text
        Table = New TTable("npc_text", TableTypes.NpcText)
        Tables.Add(Table)
        Table.Columns.Add(NpcText_Columns.Entry, "text_entry")
        Table.Columns.Add(NpcText_Columns.Prob0, "prob0")
        Table.Columns.Add(NpcText_Columns.Text0_0, "text0_0")
        Table.Columns.Add(NpcText_Columns.Text0_1, "text0_1")
        Table.Columns.Add(NpcText_Columns.Lang0, "lang0")
        Table.Columns.Add(NpcText_Columns.em0_0, "em0_0")
        Table.Columns.Add(NpcText_Columns.em0_1, "em0_1")
        Table.Columns.Add(NpcText_Columns.em0_2, "em0_2")
        Table.Columns.Add(NpcText_Columns.em0_3, "em0_3")
        Table.Columns.Add(NpcText_Columns.em0_4, "em0_4")
        Table.Columns.Add(NpcText_Columns.em0_5, "em0_5")
        Table.Columns.Add(NpcText_Columns.Prob1, "prob1")
        Table.Columns.Add(NpcText_Columns.Text1_0, "text1_0")
        Table.Columns.Add(NpcText_Columns.Text1_1, "text1_1")
        Table.Columns.Add(NpcText_Columns.Lang1, "lang1")
        Table.Columns.Add(NpcText_Columns.em1_0, "em1_0")
        Table.Columns.Add(NpcText_Columns.em1_1, "em1_1")
        Table.Columns.Add(NpcText_Columns.em1_2, "em1_2")
        Table.Columns.Add(NpcText_Columns.em1_3, "em1_3")
        Table.Columns.Add(NpcText_Columns.em1_4, "em1_4")
        Table.Columns.Add(NpcText_Columns.em1_5, "em1_5")
        Table.Columns.Add(NpcText_Columns.Prob2, "prob2")
        Table.Columns.Add(NpcText_Columns.Text2_0, "text2_0")
        Table.Columns.Add(NpcText_Columns.Text2_1, "text2_1")
        Table.Columns.Add(NpcText_Columns.Lang2, "lang2")
        Table.Columns.Add(NpcText_Columns.em2_0, "em2_0")
        Table.Columns.Add(NpcText_Columns.em2_1, "em2_1")
        Table.Columns.Add(NpcText_Columns.em2_2, "em2_2")
        Table.Columns.Add(NpcText_Columns.em2_3, "em2_3")
        Table.Columns.Add(NpcText_Columns.em2_4, "em2_4")
        Table.Columns.Add(NpcText_Columns.em2_5, "em2_5")
        Table.Columns.Add(NpcText_Columns.Prob3, "prob3")
        Table.Columns.Add(NpcText_Columns.Text3_0, "text3_0")
        Table.Columns.Add(NpcText_Columns.Text3_1, "text3_1")
        Table.Columns.Add(NpcText_Columns.Lang3, "lang3")
        Table.Columns.Add(NpcText_Columns.em3_0, "em3_0")
        Table.Columns.Add(NpcText_Columns.em3_1, "em3_1")
        Table.Columns.Add(NpcText_Columns.em3_2, "em3_2")
        Table.Columns.Add(NpcText_Columns.em3_3, "em3_3")
        Table.Columns.Add(NpcText_Columns.em3_4, "em3_4")
        Table.Columns.Add(NpcText_Columns.em3_5, "em3_5")
        Table.Columns.Add(NpcText_Columns.Prob4, "prob4")
        Table.Columns.Add(NpcText_Columns.Text4_0, "text4_0")
        Table.Columns.Add(NpcText_Columns.Text4_1, "text4_1")
        Table.Columns.Add(NpcText_Columns.Lang4, "lang4")
        Table.Columns.Add(NpcText_Columns.em4_0, "em4_0")
        Table.Columns.Add(NpcText_Columns.em4_1, "em4_1")
        Table.Columns.Add(NpcText_Columns.em4_2, "em4_2")
        Table.Columns.Add(NpcText_Columns.em4_3, "em4_3")
        Table.Columns.Add(NpcText_Columns.em4_4, "em4_4")
        Table.Columns.Add(NpcText_Columns.em4_5, "em4_5")
        Table.Columns.Add(NpcText_Columns.Prob5, "prob5")
        Table.Columns.Add(NpcText_Columns.Text5_0, "text5_0")
        Table.Columns.Add(NpcText_Columns.Text5_1, "text5_1")
        Table.Columns.Add(NpcText_Columns.Lang5, "lang5")
        Table.Columns.Add(NpcText_Columns.em5_0, "em5_0")
        Table.Columns.Add(NpcText_Columns.em5_1, "em5_1")
        Table.Columns.Add(NpcText_Columns.em5_2, "em5_2")
        Table.Columns.Add(NpcText_Columns.em5_3, "em5_3")
        Table.Columns.Add(NpcText_Columns.em5_4, "em5_4")
        Table.Columns.Add(NpcText_Columns.em5_5, "em5_5")
        Table.Columns.Add(NpcText_Columns.Prob6, "prob6")
        Table.Columns.Add(NpcText_Columns.Text6_0, "text6_0")
        Table.Columns.Add(NpcText_Columns.Text6_1, "text6_1")
        Table.Columns.Add(NpcText_Columns.Lang6, "lang6")
        Table.Columns.Add(NpcText_Columns.em6_0, "em6_0")
        Table.Columns.Add(NpcText_Columns.em6_1, "em6_1")
        Table.Columns.Add(NpcText_Columns.em6_2, "em6_2")
        Table.Columns.Add(NpcText_Columns.em6_3, "em6_3")
        Table.Columns.Add(NpcText_Columns.em6_4, "em6_4")
        Table.Columns.Add(NpcText_Columns.em6_5, "em6_5")
        Table.Columns.Add(NpcText_Columns.Prob7, "prob7")
        Table.Columns.Add(NpcText_Columns.Text7_0, "text7_0")
        Table.Columns.Add(NpcText_Columns.Text7_1, "text7_1")
        Table.Columns.Add(NpcText_Columns.Lang7, "lang7")
        Table.Columns.Add(NpcText_Columns.em7_0, "em7_0")
        Table.Columns.Add(NpcText_Columns.em7_1, "em7_1")
        Table.Columns.Add(NpcText_Columns.em7_2, "em7_2")
        Table.Columns.Add(NpcText_Columns.em7_3, "em7_3")
        Table.Columns.Add(NpcText_Columns.em7_4, "em7_4")
        Table.Columns.Add(NpcText_Columns.em7_5, "em7_5")

        'Npc_Vendors
        Table = New TTable("npc_vendor", TableTypes.NpcVendor)
        Tables.Add(Table)
        Table.Columns.Add(NpcVendor_Columns.Entry, "creature_entry")
        Table.Columns.Add(NpcVendor_Columns.Item, "item_entry")
        'Table.Columns.Add(NpcVendor_Columns.Amount, "SellAmount")
        'Table.Columns.Add(NpcVendor_Columns.Stock, "Stock")
        'Table.Columns.Add(NpcVendor_Columns.Refill, "StockRefill")
        Table.Columns.Add(NpcVendor_Columns.ExtendedCost, "extendedcost")

        'Items_Amounts
        Table = New TTable("item_amounts", TableTypes.NpcVendor)
        Tables.Add(Table)
        Table.Columns.Add(NpcVendor_Columns.Item, "item_entry")
        Table.Columns.Add(NpcVendor_Columns.Amount, "SellAmount")
        Table.Columns.Add(NpcVendor_Columns.Stock, "Stock")
        Table.Columns.Add(NpcVendor_Columns.Refill, "StockRefill")

        'Npc_Gossip_TextID
        Table = New TTable("npc_gossip_textid", TableTypes.NpcGossipTextID)
        Tables.Add(Table)
        Table.Columns.Add(NpcGossipTextID_Columns.Entry, "creature_entry")
        Table.Columns.Add(NpcGossipTextID_Columns.TextID, "textid")

        'Npc_Trainer_Defs
        Table = New TTable("npc_trainer_defs", TableTypes.NpcTrainerDefs)
        Tables.Add(Table)
        Table.Columns.Add(NpcTrainerDef_Columns.Entry, "creature_entry")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqSkill, "required_skill")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqSkillValue, "required_skillvalue")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqRace, "req_race")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqClass, "req_class")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqSpell, "req_spell")
        Table.Columns.Add(NpcTrainerDef_Columns.TrainerType, "trainer_type")
        Table.Columns.Add(NpcTrainerDef_Columns.WindowMessage, "trainer_ui_window_message")
        Table.Columns.Add(NpcTrainerDef_Columns.CanTrainMessage, "can_train_gossip_textid")
        Table.Columns.Add(NpcTrainerDef_Columns.CanNotTrainMessage, "cannot_train_gossip_textid")

        'Npc_Trainer_Spells
        Table = New TTable("npc_trainer_spells", TableTypes.NpcTrainerSpells)
        Tables.Add(Table)
        Table.Columns.Add(NpcTrainerSpell_Columns.Spell, "SpellID")
        Table.Columns.Add(NpcTrainerSpell_Columns.Entry, "creature_entry")

        'Npc_Trainer_Spell_Settings
        Table = New TTable("npc_trainer_spell_settings", TableTypes.NpcTrainerSpells)
        Tables.Add(Table)
        Table.Columns.Add(NpcTrainerSpell_Columns.Spell, "SpellID")
        Table.Columns.Add(NpcTrainerSpell_Columns.SpellCost, "SpellCost")
        Table.Columns.Add(NpcTrainerSpell_Columns.ReqSpell, "ReqSpell")
        Table.Columns.Add(NpcTrainerSpell_Columns.ReqSkill, "ReqSkill")
        Table.Columns.Add(NpcTrainerSpell_Columns.ReqSkillValue, "ReqSkillValue")
        Table.Columns.Add(NpcTrainerSpell_Columns.ReqLevel, "ReqLevel")
        Table.Columns.Add(NpcTrainerSpell_Columns.DeleteSpell, "DeleteSpell")
        Table.Columns.Add(NpcTrainerSpell_Columns.IsProf, "IsProf")
        Table.Columns.Add(NpcTrainerSpell_Columns.IsCast, "isCast")

        'items_randomprop_groups
        Table = New TTable("item_randomprop_groups", TableTypes.ItemRandomPropGroups)
        Tables.Add(Table)
        Table.Columns.Add(ItemRandom_Columns.ItemEntry, "randomprops_group")
        Table.Columns.Add(ItemRandom_Columns.RandomPropsEntryID, "randomprops_entryid")
        Table.Columns.Add(ItemRandom_Columns.Chance, "chance")

        'items_randomsuffix_groups
        Table = New TTable("item_randomsuffix_groups", TableTypes.ItemSuffixGroups)
        Tables.Add(Table)
        Table.Columns.Add(ItemRandom_Columns.ItemEntry, "suffix_group")
        Table.Columns.Add(ItemRandom_Columns.RandomSuffixEntryID, "randomsuffix_entryid")
        Table.Columns.Add(ItemRandom_Columns.Chance, "chance")

        'items_pagetext
        Table = New TTable("item_pagetext", TableTypes.ItemPages)
        Tables.Add(Table)
        Table.Columns.Add(ItemPages_Columns.ItemEntry, "page_entry")
        Table.Columns.Add(ItemPages_Columns.Text, "text")
        Table.Columns.Add(ItemPages_Columns.NextPage, "next_page")

        'items_foodtype
        Table = New TTable("item_foodtype", TableTypes.ItemPetFood)
        Tables.Add(Table)
        Table.Columns.Add(PetFood_Columns.ItemEntry, "item_entry")
        Table.Columns.Add(PetFood_Columns.FoodType, "food_type")

        'PlayerCreateInfo_Archetype
        Table = New TTable("playercreateinfo_archetype", TableTypes.PlayerCreateInfo)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfo_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfo_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfo_Columns.StartMap, "StartMap")
        Table.Columns.Add(PlayerCreateInfo_Columns.StartZone, "StartZone")
        Table.Columns.Add(PlayerCreateInfo_Columns.StartX, "StartX")
        Table.Columns.Add(PlayerCreateInfo_Columns.StartY, "StartY")
        Table.Columns.Add(PlayerCreateInfo_Columns.StartZ, "StartZ")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseStrength, "BaseStrength")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseAgility, "BaseAgility")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseStamina, "BaseStamina")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseIntellect, "BaseIntellect")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseSpirit, "BaseSpirit")
        'Table.Columns.Add(PlayerCreateInfo_Columns.BaseHealth, "BaseHealth")
        'Table.Columns.Add(PlayerCreateInfo_Columns.BasePower, "BasePower")
        'Table.Columns.Add(PlayerCreateInfo_Columns.StartO, "StartO")
        'Table.Columns.Add(PlayerCreateInfo_Columns.Intro, "Intro")
        'Table.Columns.Add(PlayerCreateInfo_Columns.IsBC, "RequiredExpansion")

        'PlayerCreateInfo_Classes
        Table = New TTable("playercreateinfo_classes", TableTypes.PlayerCreateInfo)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfo_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfo_Columns.MinDamage, "MinDamage")
        Table.Columns.Add(PlayerCreateInfo_Columns.MaxDamage, "MaxDamage")
        Table.Columns.Add(PlayerCreateInfo_Columns.PowerType, "PowerType")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseHealth, "BaseHealth")
        Table.Columns.Add(PlayerCreateInfo_Columns.BasePower, "BasePower")

        'PlayerCreateInfo_Races
        Table = New TTable("playercreateinfo_races", TableTypes.PlayerCreateInfo)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfo_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfo_Columns.Faction, "Faction")
        Table.Columns.Add(PlayerCreateInfo_Columns.MaleModelOffset, "MaleModelOffset")
        'Table.Columns.Add(PlayerCreateInfo_Columns.FemaleModelOffset, "FemaleModelOffset")
        'Table.Columns.Add(PlayerCreateInfo_Columns.Scale, "Scale")
        'Table.Columns.Add(PlayerCreateInfo_Columns.StartMap, "StartMap")
        'Table.Columns.Add(PlayerCreateInfo_Columns.StartZone, "StartZone")
        'Table.Columns.Add(PlayerCreateInfo_Columns.StartX, "StartX")
        'Table.Columns.Add(PlayerCreateInfo_Columns.StartY, "StartY")
        'Table.Columns.Add(PlayerCreateInfo_Columns.StartZ, "StartZ")
        'Table.Columns.Add(PlayerCreateInfo_Columns.StartO, "StartO")
        'Table.Columns.Add(PlayerCreateInfo_Columns.Intro, "Intro")
        'Table.Columns.Add(PlayerCreateInfo_Columns.IsBC, "IsBC")

        'PlayerCreateInfo_Bars
        Table = New TTable("playercreateinfo_bars", TableTypes.PlayerCreateInfo_Bars)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Button, "button")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Action, "action")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Type, "type")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Misc, "misc")

        'PlayerCreateInfo_Items
        Table = New TTable("playercreateinfo_items", TableTypes.PlayerCreateInfo_Items)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoItem_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.ItemID, "protoid")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.Slot, "slotid")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.Amount, "amount")

        'PlayerCreateInfo_Skills
        Table = New TTable("playercreateinfo_skills", TableTypes.PlayerCreateInfo_Skills)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.SkillID, "skillid")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.Level, "level")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.MaxLevel, "maxlevel")

        'PlayerCreateInfo_Spells
        Table = New TTable("playercreateinfo_spells", TableTypes.PlayerCreateInfo_Spells)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoSpell_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfoSpell_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfoSpell_Columns.SpellID, "spellid")

        'Npc_MonsterSay
        Table = New TTable("npc_monstersay", TableTypes.MonsterSay)
        Tables.Add(Table)
        Table.Columns.Add(MonsterSay_Columns.CreatureEntry, "creature_entry")
        Table.Columns.Add(MonsterSay_Columns.Evente, "event")
        Table.Columns.Add(MonsterSay_Columns.Chance, "chance")
        Table.Columns.Add(MonsterSay_Columns.Language, "language")
        Table.Columns.Add(MonsterSay_Columns.Type, "type")
        Table.Columns.Add(MonsterSay_Columns.MonsterName, "monstername")
        Table.Columns.Add(MonsterSay_Columns.Text0, "text0")
        Table.Columns.Add(MonsterSay_Columns.Text1, "text1")
        Table.Columns.Add(MonsterSay_Columns.Text2, "text2")
        Table.Columns.Add(MonsterSay_Columns.Text3, "text3")
        Table.Columns.Add(MonsterSay_Columns.Text4, "text4")

        'Loot_Skinning
        Table = New TTable("loot_skinning", TableTypes.LootsSkinning)
        Tables.Add(Table)
        Table.Columns.Add(LootsSkinning_Columns.CreatureEntry, "creature_entry")
        Table.Columns.Add(LootsSkinning_Columns.ItemID, "drop_item_entry")
        Table.Columns.Add(LootsSkinning_Columns.GroupID, "groupid")
        Table.Columns.Add(LootsSkinning_Columns.PercentChance, "percentchance")
        Table.Columns.Add(LootsSkinning_Columns.HeroicPercentChance, "heroicpercentchance")
        Table.Columns.Add(LootsSkinning_Columns.MinCount, "mincount")
        Table.Columns.Add(LootsSkinning_Columns.MaxCount, "maxcount")
        Table.Columns.Add(LootsSkinning_Columns.FFA_Loot, "ffa_loot")
        Table.Columns.Add(LootsSkinning_Columns.LootCondition, "loot_condition")
        Table.Columns.Add(LootsSkinning_Columns.ConditionValue1, "condition_value_1")
        Table.Columns.Add(LootsSkinning_Columns.ConditionValue2, "condition_value_2")

        'Loot_Item
        Table = New TTable("loot_item", TableTypes.LootsItem)
        Tables.Add(Table)
        Table.Columns.Add(LootsItem_Columns.ItemEntry, "item_entry")
        Table.Columns.Add(LootsItem_Columns.ItemID, "drop_item_entry")
        Table.Columns.Add(LootsItem_Columns.GroupID, "groupid")
        Table.Columns.Add(LootsItem_Columns.PercentChance, "percentchance")
        Table.Columns.Add(LootsItem_Columns.HeroicPercentChance, "heroicpercentchance")
        Table.Columns.Add(LootsItem_Columns.MinCount, "mincount")
        Table.Columns.Add(LootsItem_Columns.MaxCount, "maxcount")
        Table.Columns.Add(LootsItem_Columns.FFA_Loot, "ffa_loot")
        Table.Columns.Add(LootsItem_Columns.LootCondition, "loot_condition")
        Table.Columns.Add(LootsItem_Columns.ConditionValue1, "condition_value_1")
        Table.Columns.Add(LootsItem_Columns.ConditionValue2, "condition_value_2")

        'World_CmdTeleports
        Table = New TTable("world_cmdteleports", TableTypes.CmdTeleports)
        Tables.Add(Table)
        Table.Columns.Add(CmdTeleports_Columns.Id, "id")
        Table.Columns.Add(CmdTeleports_Columns.Name, "name")
        Table.Columns.Add(CmdTeleports_Columns.MapID, "MapId")
        Table.Columns.Add(CmdTeleports_Columns.PositionX, "positionX")
        Table.Columns.Add(CmdTeleports_Columns.PositionY, "positionY")
        Table.Columns.Add(CmdTeleports_Columns.PositionZ, "positionZ")

        'Creatures_Movement
        Table = New TTable("creature_movement", TableTypes.creature_movement)
        Tables.Add(Table)
        Table.Columns.Add(Creature_Movement_Columns.spawnid, "spawnid")
        Table.Columns.Add(Creature_Movement_Columns.waypointid, "waypointid")
        Table.Columns.Add(Creature_Movement_Columns.position_x, "position_x")
        Table.Columns.Add(Creature_Movement_Columns.position_y, "position_y")
        Table.Columns.Add(Creature_Movement_Columns.position_z, "position_z")
        Table.Columns.Add(Creature_Movement_Columns.waittime, "waittime")
        Table.Columns.Add(Creature_Movement_Columns.flags, "flags")
        Table.Columns.Add(Creature_Movement_Columns.emote, "emote")
        Table.Columns.Add(Creature_Movement_Columns.orientation, "orientation")

    End Sub

End Class
