Public Class Spurious
    Inherits BaseDB

    Public Sub New()
        InitTables()
    End Sub

    Public Sub InitTables()
        Dim Table As TTable
        'Creatures
        Table = New TTable("creatures", TableTypes.CreatureInfo)
        Tables.Add(Table)
        Table.Columns.Add(CreatureInfo_Columns.Entry, "creature_id")
        Table.Columns.Add(CreatureInfo_Columns.Name, "creature_name")
        Table.Columns.Add(CreatureInfo_Columns.SubName, "creature_guild")
        Table.Columns.Add(CreatureInfo_Columns.InfoStr, "info_str")
        Table.Columns.Add(CreatureInfo_Columns.Flags, "creature_flags")
        Table.Columns.Add(CreatureInfo_Columns.Type, "creature_type")
        Table.Columns.Add(CreatureInfo_Columns.Family, "creature_family")
        Table.Columns.Add(CreatureInfo_Columns.Rank, "creature_elite")
        Table.Columns.Add(CreatureInfo_Columns.Unk4, "")
        Table.Columns.Add(CreatureInfo_Columns.SpellDataID, "")
        Table.Columns.Add(CreatureInfo_Columns.MaleDisplayID, "creature_model")
        Table.Columns.Add(CreatureInfo_Columns.FemaleDisplayID, "creature_femalemodel")
        Table.Columns.Add(CreatureInfo_Columns.MaleDisplayID2, "")
        Table.Columns.Add(CreatureInfo_Columns.FemaleDisplayID2, "")
        Table.Columns.Add(CreatureInfo_Columns.UnknownFloat1, "creature_unkfloat1")
        Table.Columns.Add(CreatureInfo_Columns.UnknownFloat2, "creature_unkfloat2")
        Table.Columns.Add(CreatureInfo_Columns.Civilian, "")
        Table.Columns.Add(CreatureInfo_Columns.Leader, "creature_leader")
        Table.Columns.Add(CreatureInfo_Columns.MinLevel, "creature_minLevel")
        Table.Columns.Add(CreatureInfo_Columns.MaxLevel, "creature_maxLevel")
        Table.Columns.Add(CreatureInfo_Columns.Size, "creature_size")
        Table.Columns.Add(CreatureInfo_Columns.Life, "creature_life")
        Table.Columns.Add(CreatureInfo_Columns.Mana, "creature_mana")
        Table.Columns.Add(CreatureInfo_Columns.ManaType, "creature_manaType")
        Table.Columns.Add(CreatureInfo_Columns.Faction, "creature_faction")
        Table.Columns.Add(CreatureInfo_Columns.MinDamage, "creature_minDamage")
        Table.Columns.Add(CreatureInfo_Columns.MaxDamage, "creature_maxDamage")
        Table.Columns.Add(CreatureInfo_Columns.MinRangedDamage, "creature_minRangedDamage")
        Table.Columns.Add(CreatureInfo_Columns.MaxRangedDamage, "creature_maxRangedDamage")
        Table.Columns.Add(CreatureInfo_Columns.Armor, "creature_armor")
        Table.Columns.Add(CreatureInfo_Columns.ResHoly, "creature_resHoly")
        Table.Columns.Add(CreatureInfo_Columns.ResFire, "creature_resFire")
        Table.Columns.Add(CreatureInfo_Columns.ResNature, "creature_resNature")
        Table.Columns.Add(CreatureInfo_Columns.ResFrost, "creature_resFrost")
        Table.Columns.Add(CreatureInfo_Columns.ResShadow, "creature_resShadow")
        Table.Columns.Add(CreatureInfo_Columns.ResArcane, "creature_resArcane")
        Table.Columns.Add(CreatureInfo_Columns.WalkSpeed, "creature_walkSpeed")
        Table.Columns.Add(CreatureInfo_Columns.RunSpeed, "creature_runSpeed")
        Table.Columns.Add(CreatureInfo_Columns.FlySpeed, "creature_flySpeed")
        Table.Columns.Add(CreatureInfo_Columns.RespawnTime, "creature_respawnTime")
        Table.Columns.Add(CreatureInfo_Columns.BaseAttackSpeed, "creature_baseAttackSpeed")
        Table.Columns.Add(CreatureInfo_Columns.BaseRangedAttackSpeed, "creature_baseRangedAttackSpeed")
        Table.Columns.Add(CreatureInfo_Columns.CombatReach, "creature_combatReach")
        Table.Columns.Add(CreatureInfo_Columns.BondingRadius, "creature_bondingRadius")
        Table.Columns.Add(CreatureInfo_Columns.NpcFlags, "creature_npcFlags")
        Table.Columns.Add(CreatureInfo_Columns.Loot, "creature_loot")
        Table.Columns.Add(CreatureInfo_Columns.SkinLoot, "creature_skinloot")
        Table.Columns.Add(CreatureInfo_Columns.PickpocketLoot, "creature_pickpocketloot")
        Table.Columns.Add(CreatureInfo_Columns.EquipmentEntry, "creature_equipmententry")

        'Spawns_Creatures
        Table = New TTable("spawns_creatures", TableTypes.CreatureSpawn)
        Tables.Add(Table)
        Table.Columns.Add(CreatureSpawn_Columns.ID, "spawn_id")
        Table.Columns.Add(CreatureSpawn_Columns.Entry, "spawn_entry")
        Table.Columns.Add(CreatureSpawn_Columns.PositionX, "spawn_positionX")
        Table.Columns.Add(CreatureSpawn_Columns.PositionY, "spawn_positionY")
        Table.Columns.Add(CreatureSpawn_Columns.PositionZ, "spawn_positionZ")
        Table.Columns.Add(CreatureSpawn_Columns.Orientation, "spawn_orientation")
        Table.Columns.Add(CreatureSpawn_Columns.Range, "spawn_range")
        Table.Columns.Add(CreatureSpawn_Columns.Map, "spawn_map")
        Table.Columns.Add(CreatureSpawn_Columns.MoveType, "spawn_movetype")
        Table.Columns.Add(CreatureSpawn_Columns.Model, "spawn_displayid")
        Table.Columns.Add(CreatureSpawn_Columns.Faction, "spawn_faction")
        Table.Columns.Add(CreatureSpawn_Columns.Mount, "spawn_mount")
        Table.Columns.Add(CreatureSpawn_Columns.Flags, "spawn_flags")
        Table.Columns.Add(CreatureSpawn_Columns.Bytes0, "spawn_bytes0")
        Table.Columns.Add(CreatureSpawn_Columns.Bytes1, "spawn_bytes1")
        Table.Columns.Add(CreatureSpawn_Columns.Bytes2, "spawn_bytes2")
        Table.Columns.Add(CreatureSpawn_Columns.EmoteState, "spawn_emotestate")
        Table.Columns.Add(CreatureSpawn_Columns.StandState, "spawn_standstate")
        Table.Columns.Add(CreatureSpawn_Columns.equipslot1, "spawn_equipslot1")
        Table.Columns.Add(CreatureSpawn_Columns.equipslot2, "spawn_equipslot2")
        Table.Columns.Add(CreatureSpawn_Columns.equipslot3, "spawn_equipslot3")

        'Gameobjects
        Table = New TTable("gameobjects", TableTypes.GameobjectInfo)
        Tables.Add(Table)
        Table.Columns.Add(GameobjectInfo_Columns.Entry, "gameObject_ID")
        Table.Columns.Add(GameobjectInfo_Columns.Model, "gameObject_Model")
        Table.Columns.Add(GameobjectInfo_Columns.Name, "gameObject_Name")
        Table.Columns.Add(GameobjectInfo_Columns.Type, "gameObject_Type")
        Table.Columns.Add(GameobjectInfo_Columns.RespawnTime, "gameObject_RespawnTime")
        Table.Columns.Add(GameobjectInfo_Columns.Field0, "gameObject_Field0")
        Table.Columns.Add(GameobjectInfo_Columns.Field1, "gameObject_Field1")
        Table.Columns.Add(GameobjectInfo_Columns.Field2, "gameObject_Field2")
        Table.Columns.Add(GameobjectInfo_Columns.Field3, "gameObject_Field3")
        Table.Columns.Add(GameobjectInfo_Columns.Field4, "gameObject_Field4")
        Table.Columns.Add(GameobjectInfo_Columns.Field5, "gameObject_Field5")
        Table.Columns.Add(GameobjectInfo_Columns.Field6, "gameObject_Field6")
        Table.Columns.Add(GameobjectInfo_Columns.Field7, "gameObject_Field7")
        Table.Columns.Add(GameobjectInfo_Columns.Field8, "gameObject_Field8")
        Table.Columns.Add(GameobjectInfo_Columns.Field9, "gameObject_Field9")
        Table.Columns.Add(GameobjectInfo_Columns.Field10, "gameObject_Field10")
        Table.Columns.Add(GameobjectInfo_Columns.Field11, "gameObject_Field11")
        Table.Columns.Add(GameobjectInfo_Columns.Field12, "gameObject_Field12")
        Table.Columns.Add(GameobjectInfo_Columns.Field13, "gameObject_Field13")
        Table.Columns.Add(GameobjectInfo_Columns.Field14, "gameObject_Field14")
        Table.Columns.Add(GameobjectInfo_Columns.Field15, "gameObject_Field15")
        Table.Columns.Add(GameobjectInfo_Columns.Field16, "gameObject_Field16")
        Table.Columns.Add(GameobjectInfo_Columns.Field17, "gameObject_Field17")
        Table.Columns.Add(GameobjectInfo_Columns.Field18, "gameObject_Field18")
        Table.Columns.Add(GameobjectInfo_Columns.Field19, "gameObject_Field19")
        Table.Columns.Add(GameobjectInfo_Columns.Field20, "gameObject_Field20")
        Table.Columns.Add(GameobjectInfo_Columns.Field21, "gameObject_Field21")
        Table.Columns.Add(GameobjectInfo_Columns.Field22, "gameObject_Field22")
        Table.Columns.Add(GameobjectInfo_Columns.Field23, "gameObject_Field23")
        Table.Columns.Add(GameobjectInfo_Columns.Scale, "")

        'Spawns_Gameobjects
        Table = New TTable("spawns_gameobjects", TableTypes.GameobjectSpawn)
        Tables.Add(Table)
        Table.Columns.Add(GameobjectSpawn_Columns.ID, "spawn_id")
        Table.Columns.Add(GameobjectSpawn_Columns.Entry, "spawn_entry")
        Table.Columns.Add(GameobjectSpawn_Columns.PositionX, "spawn_positionX")
        Table.Columns.Add(GameobjectSpawn_Columns.PositionY, "spawn_positionY")
        Table.Columns.Add(GameobjectSpawn_Columns.PositionZ, "spawn_positionZ")
        Table.Columns.Add(GameobjectSpawn_Columns.Orientation, "spawn_orientation")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation1, "spawn_orientation1")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation2, "spawn_orientation2")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation3, "spawn_orientation3")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation4, "spawn_orientation4")
        Table.Columns.Add(GameobjectSpawn_Columns.Map, "spawn_map")
        Table.Columns.Add(GameobjectSpawn_Columns.State, "spawn_state")
        Table.Columns.Add(GameobjectSpawn_Columns.Flags, "spawn_flags")
        Table.Columns.Add(GameobjectSpawn_Columns.Faction, "spawn_faction")
        Table.Columns.Add(GameobjectSpawn_Columns.Scale, "spawn_scale")

        'Items
        Table = New TTable("items", TableTypes.Items)
        Tables.Add(Table)
        Table.Columns.Add(Item_Columns.Entry, "entry")
        Table.Columns.Add(Item_Columns.Classe, "class")
        Table.Columns.Add(Item_Columns.SubClass, "subclass")
        Table.Columns.Add(Item_Columns.Field4, "field4")
        Table.Columns.Add(Item_Columns.Name1, "name1")
        Table.Columns.Add(Item_Columns.Name2, "name2")
        Table.Columns.Add(Item_Columns.Name3, "name3")
        Table.Columns.Add(Item_Columns.Name4, "name4")
        Table.Columns.Add(Item_Columns.DisplayID, "displayid")
        Table.Columns.Add(Item_Columns.Quality, "quality")
        Table.Columns.Add(Item_Columns.Flags, "flags")
        Table.Columns.Add(Item_Columns.Buyprice, "buyprice")
        Table.Columns.Add(Item_Columns.Sellprice, "sellprice")
        Table.Columns.Add(Item_Columns.InventoryType, "inventorytype")
        Table.Columns.Add(Item_Columns.AllowableClass, "allowableclass")
        Table.Columns.Add(Item_Columns.AllowableRace, "allowablerace")
        Table.Columns.Add(Item_Columns.ItemLevel, "itemlevel")
        Table.Columns.Add(Item_Columns.RequiredLevel, "requiredlevel")
        Table.Columns.Add(Item_Columns.RequiredSkill, "RequiredSkill")
        Table.Columns.Add(Item_Columns.RequiredSkillRank, "RequiredSkillRank")
        Table.Columns.Add(Item_Columns.RequiredSubRank, "RequiredSkillSubRank")
        Table.Columns.Add(Item_Columns.RequiredPlayerRank1, "RequiredPlayerRank1")
        Table.Columns.Add(Item_Columns.RequiredPlayerRank2, "RequiredPlayerRank2")
        Table.Columns.Add(Item_Columns.RequiredFaction, "RequiredFaction")
        Table.Columns.Add(Item_Columns.RequiredFactionStanding, "RequiredFactionStanding")
        Table.Columns.Add(Item_Columns.Unique, "Unique")
        Table.Columns.Add(Item_Columns.MaxCount, "maxcount")
        Table.Columns.Add(Item_Columns.ContainerSlots, "ContainerSlots")
        Table.Columns.Add(Item_Columns.Stat_Type1, "stat_type1")
        Table.Columns.Add(Item_Columns.Stat_Value1, "stat_value1")
        Table.Columns.Add(Item_Columns.Stat_Type2, "stat_type2")
        Table.Columns.Add(Item_Columns.Stat_Value2, "stat_value2")
        Table.Columns.Add(Item_Columns.Stat_Type3, "stat_type3")
        Table.Columns.Add(Item_Columns.Stat_Value3, "stat_value3")
        Table.Columns.Add(Item_Columns.Stat_Type4, "stat_type4")
        Table.Columns.Add(Item_Columns.Stat_Value4, "stat_value4")
        Table.Columns.Add(Item_Columns.Stat_Type5, "stat_type5")
        Table.Columns.Add(Item_Columns.Stat_Value5, "stat_value5")
        Table.Columns.Add(Item_Columns.Stat_Type6, "stat_type6")
        Table.Columns.Add(Item_Columns.Stat_Value6, "stat_value6")
        Table.Columns.Add(Item_Columns.Stat_Type7, "stat_type7")
        Table.Columns.Add(Item_Columns.Stat_Value7, "stat_value7")
        Table.Columns.Add(Item_Columns.Stat_Type8, "stat_type8")
        Table.Columns.Add(Item_Columns.Stat_Value8, "stat_value8")
        Table.Columns.Add(Item_Columns.Stat_Type9, "stat_type9")
        Table.Columns.Add(Item_Columns.Stat_Value9, "stat_value9")
        Table.Columns.Add(Item_Columns.Stat_Type10, "stat_type10")
        Table.Columns.Add(Item_Columns.Stat_Value10, "stat_value10")
        Table.Columns.Add(Item_Columns.Dmg_Min1, "dmg_min1")
        Table.Columns.Add(Item_Columns.Dmg_Max1, "dmg_max1")
        Table.Columns.Add(Item_Columns.Dmg_Type1, "dmg_type1")
        Table.Columns.Add(Item_Columns.Dmg_Min2, "dmg_min2")
        Table.Columns.Add(Item_Columns.Dmg_Max2, "dmg_max2")
        Table.Columns.Add(Item_Columns.Dmg_Type2, "dmg_type2")
        Table.Columns.Add(Item_Columns.Dmg_Min3, "")
        Table.Columns.Add(Item_Columns.Dmg_Max3, "")
        Table.Columns.Add(Item_Columns.Dmg_Type3, "")
        Table.Columns.Add(Item_Columns.Dmg_Min4, "")
        Table.Columns.Add(Item_Columns.Dmg_Max4, "")
        Table.Columns.Add(Item_Columns.Dmg_Type4, "")
        Table.Columns.Add(Item_Columns.Dmg_Min5, "")
        Table.Columns.Add(Item_Columns.Dmg_Max5, "")
        Table.Columns.Add(Item_Columns.Dmg_Type5, "")
        Table.Columns.Add(Item_Columns.Armor, "armor")
        Table.Columns.Add(Item_Columns.HolyRes, "holy_res")
        Table.Columns.Add(Item_Columns.FireRes, "fire_res")
        Table.Columns.Add(Item_Columns.NatureRes, "nature_res")
        Table.Columns.Add(Item_Columns.FrostRes, "frost_res")
        Table.Columns.Add(Item_Columns.ShadowRes, "shadow_res")
        Table.Columns.Add(Item_Columns.ArcaneRes, "arcane_res")
        Table.Columns.Add(Item_Columns.Delay, "delay")
        Table.Columns.Add(Item_Columns.AmmoType, "ammo_type")
        Table.Columns.Add(Item_Columns.Range, "range")
        Table.Columns.Add(Item_Columns.SpellID_1, "spellid_1")
        Table.Columns.Add(Item_Columns.SpellTrigger_1, "spelltrigger_1")
        Table.Columns.Add(Item_Columns.SpellCharges_1, "spellcharges_1")
        Table.Columns.Add(Item_Columns.SpellCooldown_1, "spellcooldown_1")
        Table.Columns.Add(Item_Columns.SpellCategory_1, "spellcategory_1")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_1, "spellcategorycooldown_1")
        Table.Columns.Add(Item_Columns.SpellID_2, "spellid_2")
        Table.Columns.Add(Item_Columns.SpellTrigger_2, "spelltrigger_2")
        Table.Columns.Add(Item_Columns.SpellCharges_2, "spellcharges_2")
        Table.Columns.Add(Item_Columns.SpellCooldown_2, "spellcooldown_2")
        Table.Columns.Add(Item_Columns.SpellCategory_2, "spellcategory_2")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_2, "spellcategorycooldown_2")
        Table.Columns.Add(Item_Columns.SpellID_3, "spellid_3")
        Table.Columns.Add(Item_Columns.SpellTrigger_3, "spelltrigger_3")
        Table.Columns.Add(Item_Columns.SpellCharges_3, "spellcharges_3")
        Table.Columns.Add(Item_Columns.SpellCooldown_3, "spellcooldown_3")
        Table.Columns.Add(Item_Columns.SpellCategory_3, "spellcategory_3")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_3, "spellcategorycooldown_3")
        Table.Columns.Add(Item_Columns.SpellID_4, "spellid_4")
        Table.Columns.Add(Item_Columns.SpellTrigger_4, "spelltrigger_4")
        Table.Columns.Add(Item_Columns.SpellCharges_4, "spellcharges_4")
        Table.Columns.Add(Item_Columns.SpellCooldown_4, "spellcooldown_4")
        Table.Columns.Add(Item_Columns.SpellCategory_4, "spellcategory_4")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_4, "spellcategorycooldown_4")
        Table.Columns.Add(Item_Columns.SpellID_5, "spellid_5")
        Table.Columns.Add(Item_Columns.SpellTrigger_5, "spelltrigger_5")
        Table.Columns.Add(Item_Columns.SpellCharges_5, "spellcharges_5")
        Table.Columns.Add(Item_Columns.SpellCooldown_5, "spellcooldown_5")
        Table.Columns.Add(Item_Columns.SpellCategory_5, "spellcategory_5")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_5, "spellcategorycooldown_5")
        Table.Columns.Add(Item_Columns.Bonding, "bonding")
        Table.Columns.Add(Item_Columns.Description, "description")
        Table.Columns.Add(Item_Columns.PageID, "page_id")
        Table.Columns.Add(Item_Columns.PageLanguage, "page_language")
        Table.Columns.Add(Item_Columns.PageMaterial, "page_material")
        Table.Columns.Add(Item_Columns.QuestID, "quest_id")
        Table.Columns.Add(Item_Columns.LockID, "lock_id")
        Table.Columns.Add(Item_Columns.LockMaterial, "lock_material")
        Table.Columns.Add(Item_Columns.SheathID, "sheathID")
        Table.Columns.Add(Item_Columns.RandomProp, "randomprop")
        Table.Columns.Add(Item_Columns.RandomSuffix, "randomsuffix")
        Table.Columns.Add(Item_Columns.Block, "block")
        Table.Columns.Add(Item_Columns.ItemSet, "itemset")
        Table.Columns.Add(Item_Columns.MaxDurability, "MaxDurability")
        Table.Columns.Add(Item_Columns.ZoneNameID, "ZoneNameID")
        Table.Columns.Add(Item_Columns.MapID, "mapid")
        Table.Columns.Add(Item_Columns.BagFamily, "bagfamily")
        Table.Columns.Add(Item_Columns.TotemCategory, "TotemCategory")
        Table.Columns.Add(Item_Columns.SocketColor_1, "socket_color_1")
        Table.Columns.Add(Item_Columns.SocketContent_1, "socket_content_1")
        Table.Columns.Add(Item_Columns.SocketColor_2, "socket_color_2")
        Table.Columns.Add(Item_Columns.SocketContent_2, "socket_content_2")
        Table.Columns.Add(Item_Columns.SocketColor_3, "socket_color_3")
        Table.Columns.Add(Item_Columns.SocketContent_3, "socket_content_3")
        Table.Columns.Add(Item_Columns.SocketBonus, "socket_bonus")
        Table.Columns.Add(Item_Columns.GemProperties, "GemProperties")
        Table.Columns.Add(Item_Columns.ReqDisenchantSkill, "ReqDisenchantSkill")
        Table.Columns.Add(Item_Columns.ArmorDamageModifier, "armorDamageModifier")
        Table.Columns.Add(Item_Columns.ExistingDuration, "ExistingDuration")

        'Loots
        Table = New TTable("loots", TableTypes.CreatureLoot)
        Tables.Add(Table)
        Table.Columns.Add(CreatureLoot_Columns.Entry, "loot_creature")
        Table.Columns.Add(CreatureLoot_Columns.Item, "loot_item")
        Table.Columns.Add(CreatureLoot_Columns.Chance, "loot_chance")
        Table.Columns.Add(CreatureLoot_Columns.HeroicChance, "loot_heroicchance")
        Table.Columns.Add(CreatureLoot_Columns.Min, "loot_min")
        Table.Columns.Add(CreatureLoot_Columns.Max, "loot_max")
        Table.Columns.Add(CreatureLoot_Columns.FFA, "loot_ffa")

        'Loots_Gameobject
        Table = New TTable("loots_gameobject", TableTypes.GameobjectLoot)
        Tables.Add(Table)
        Table.Columns.Add(GameobjectLoot_Columns.Entry, "loot_object")
        Table.Columns.Add(GameobjectLoot_Columns.Item, "loot_item")
        Table.Columns.Add(GameobjectLoot_Columns.Chance, "loot_chance")
        Table.Columns.Add(GameobjectLoot_Columns.HeroicChance, "loot_heroicchance")
        Table.Columns.Add(GameobjectLoot_Columns.Min, "loot_min")
        Table.Columns.Add(GameobjectLoot_Columns.Max, "loot_max")
        Table.Columns.Add(GameobjectLoot_Columns.FFA, "loot_ffa")

        'Quests
        Table = New TTable("quests", TableTypes.Quests)
        Tables.Add(Table)
        Table.Columns.Add(Quest_Columns.ID, "id")
        Table.Columns.Add(Quest_Columns.NextQuest, "NextQuest")
        Table.Columns.Add(Quest_Columns.Title, "Title")
        Table.Columns.Add(Quest_Columns.Zone, "Zone")
        Table.Columns.Add(Quest_Columns.Type, "Type")
        Table.Columns.Add(Quest_Columns.Flags, "Flags")
        Table.Columns.Add(Quest_Columns.RewTitleId, "RewTitleId")
        Table.Columns.Add(Quest_Columns.RewardTalents, "rewtalents")
        Table.Columns.Add(Quest_Columns.SpecialFlags, "SpecialFlags")
        Table.Columns.Add(Quest_Columns.LevelStart, "Level_Start")
        Table.Columns.Add(Quest_Columns.LevelNormal, "Level_Normal")
        Table.Columns.Add(Quest_Columns.ReqQuest1, "Required_Quest1")
        Table.Columns.Add(Quest_Columns.ReqQuest2, "Required_Quest2")
        Table.Columns.Add(Quest_Columns.ReqQuest3, "Required_Quest3")
        Table.Columns.Add(Quest_Columns.ReqQuest4, "Required_Quest4")
        Table.Columns.Add(Quest_Columns.ReqRace, "Required_Race")
        Table.Columns.Add(Quest_Columns.ReqClass, "Required_Class")
        Table.Columns.Add(Quest_Columns.ReqTradeSkill, "Required_TradeSkill")
        Table.Columns.Add(Quest_Columns.ReqTradeSkillValue, "Required_TradeSkillValue")
        Table.Columns.Add(Quest_Columns.ReqReputation1, "Required_Reputation1")
        Table.Columns.Add(Quest_Columns.ReqReputation1Faction, "Required_Reputation1_Faction")
        Table.Columns.Add(Quest_Columns.ReqReputation2, "Required_Reputation2")
        Table.Columns.Add(Quest_Columns.ReqReputation2Faction, "Required_Reputation2_Faction")
        Table.Columns.Add(Quest_Columns.TextObjectives, "Text_Objectives")
        Table.Columns.Add(Quest_Columns.TextDescription, "Text_Description")
        Table.Columns.Add(Quest_Columns.TextEnd, "Text_End")
        Table.Columns.Add(Quest_Columns.TextIncomplete, "Text_Incomplete")
        Table.Columns.Add(Quest_Columns.TextPrecomplete, "Text_PreComplete")
        Table.Columns.Add(Quest_Columns.TextComplete, "Text_Complete")
        Table.Columns.Add(Quest_Columns.RewardXP, "Reward_XP")
        Table.Columns.Add(Quest_Columns.RewardGold, "Reward_Gold")
        Table.Columns.Add(Quest_Columns.RewardSpell, "Reward_Spell")
        Table.Columns.Add(Quest_Columns.RewardSpellCast, "Reward_SpellCast")
        Table.Columns.Add(Quest_Columns.RewardReputation1, "Reward_Reputation1")
        Table.Columns.Add(Quest_Columns.RewardReputation1Faction, "Reward_Reputation1_Faction")
        Table.Columns.Add(Quest_Columns.RewardReputation2, "Reward_Reputation2")
        Table.Columns.Add(Quest_Columns.RewardReputation2Faction, "Reward_Reputation2_Faction")
        Table.Columns.Add(Quest_Columns.RewardReputation3, "Reward_Reputation3")
        Table.Columns.Add(Quest_Columns.RewardReputation3Faction, "Reward_Reputation3_Faction")
        Table.Columns.Add(Quest_Columns.RewardItem1, "Reward_Item1")
        Table.Columns.Add(Quest_Columns.RewardItem1Count, "Reward_Item1_Count")
        Table.Columns.Add(Quest_Columns.RewardItem2, "Reward_Item2")
        Table.Columns.Add(Quest_Columns.RewardItem2Count, "Reward_Item2_Count")
        Table.Columns.Add(Quest_Columns.RewardItem3, "Reward_Item3")
        Table.Columns.Add(Quest_Columns.RewardItem3Count, "Reward_Item3_Count")
        Table.Columns.Add(Quest_Columns.RewardItem4, "Reward_Item4")
        Table.Columns.Add(Quest_Columns.RewardItem4Count, "Reward_Item4_Count")
        Table.Columns.Add(Quest_Columns.RewardItem5, "Reward_Item5")
        Table.Columns.Add(Quest_Columns.RewardItem5Count, "Reward_Item5_Count")
        Table.Columns.Add(Quest_Columns.RewardItem6, "Reward_Item6")
        Table.Columns.Add(Quest_Columns.RewardItem6Count, "Reward_Item6_Count")
        Table.Columns.Add(Quest_Columns.RewardStaticItem1, "Reward_StaticItem1")
        Table.Columns.Add(Quest_Columns.RewardStaticItem1Count, "Reward_StaticItem1_Count")
        Table.Columns.Add(Quest_Columns.RewardStaticItem2, "Reward_StaticItem2")
        Table.Columns.Add(Quest_Columns.RewardStaticItem2Count, "Reward_StaticItem2_Count")
        Table.Columns.Add(Quest_Columns.RewardStaticItem3, "Reward_StaticItem3")
        Table.Columns.Add(Quest_Columns.RewardStaticItem3Count, "Reward_StaticItem3_Count")
        Table.Columns.Add(Quest_Columns.RewardStaticItem4, "Reward_StaticItem4")
        Table.Columns.Add(Quest_Columns.RewardStaticItem4Count, "Reward_StaticItem4_Count")
        Table.Columns.Add(Quest_Columns.TimeLimit, "Time_Limit")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger1, "Objective_Trigger1")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger2, "Objective_Trigger2")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger3, "Objective_Trigger3")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger4, "Objective_Trigger4")
        Table.Columns.Add(Quest_Columns.ObjectiveCast1, "Objective_Cast1")
        Table.Columns.Add(Quest_Columns.ObjectiveCast2, "Objective_Cast2")
        Table.Columns.Add(Quest_Columns.ObjectiveCast3, "Objective_Cast3")
        Table.Columns.Add(Quest_Columns.ObjectiveCast4, "Objective_Cast4")
        Table.Columns.Add(Quest_Columns.ObjectiveKill1, "Objective_Kill1")
        Table.Columns.Add(Quest_Columns.ObjectiveKill1Count, "Objective_Kill1_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveKill2, "Objective_Kill2")
        Table.Columns.Add(Quest_Columns.ObjectiveKill2Count, "Objective_Kill2_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveKill3, "Objective_Kill3")
        Table.Columns.Add(Quest_Columns.ObjectiveKill3Count, "Objective_Kill3_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveKill4, "Objective_Kill4")
        Table.Columns.Add(Quest_Columns.ObjectiveKill4Count, "Objective_Kill4_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveItem1, "Objective_Item1")
        Table.Columns.Add(Quest_Columns.ObjectiveItem1Count, "Objective_Item1_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveItem2, "Objective_Item2")
        Table.Columns.Add(Quest_Columns.ObjectiveItem2Count, "Objective_Item2_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveItem3, "Objective_Item3")
        Table.Columns.Add(Quest_Columns.ObjectiveItem3Count, "Objective_Item3_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveItem4, "Objective_Item4")
        Table.Columns.Add(Quest_Columns.ObjectiveItem4Count, "Objective_Item4_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveDeliver, "Objective_Deliver1")
        Table.Columns.Add(Quest_Columns.ObjectiveText1, "Objective_Text1")
        Table.Columns.Add(Quest_Columns.ObjectiveText2, "Objective_Text2")
        Table.Columns.Add(Quest_Columns.ObjectiveText3, "Objective_Text3")
        Table.Columns.Add(Quest_Columns.ObjectiveText4, "Objective_Text4")
        Table.Columns.Add(Quest_Columns.SuggestedPlayers, "SuggestedPlayers")
        Table.Columns.Add(Quest_Columns.PointMap, "PointMap")
        Table.Columns.Add(Quest_Columns.PointX, "PointX")
        Table.Columns.Add(Quest_Columns.PointY, "PointY")
        Table.Columns.Add(Quest_Columns.PointOpt, "PointOpt")
        Table.Columns.Add(Quest_Columns.MoneyAtMaxLevel, "MoneyAtMaxLevel")
        Table.Columns.Add(Quest_Columns.IsActive, "IsActive")

        'Battleground_Battlemaster
        Table = New TTable("battleground_battlemaster", TableTypes.BattleGround_BattleMaster)
        Tables.Add(Table)
        Table.Columns.Add(BattleGround_Columns.creature, "entry")
        Table.Columns.Add(BattleGround_Columns.battleground, "battleground_entry")

        'Battleground_Template
        Table = New TTable("battleground_template", TableTypes.BattleGround_Template)
        Tables.Add(Table)
        Table.Columns.Add(BattleGround_Columns.battleground, "id")
        Table.Columns.Add(BattleGround_Columns.Name, "Name")
        Table.Columns.Add(BattleGround_Columns.Type, "Type")
        Table.Columns.Add(BattleGround_Columns.Map1, "Map1")
        Table.Columns.Add(BattleGround_Columns.Map2, "Map2")
        Table.Columns.Add(BattleGround_Columns.Map3, "Map3")
        Table.Columns.Add(BattleGround_Columns.MinPlayersPerTeam, "MinPlayersPerTeam")
        Table.Columns.Add(BattleGround_Columns.MaxPlayersPerTeam, "MaxPlayersPerTeam")
        Table.Columns.Add(BattleGround_Columns.MinLvl, "MinLvl")
        Table.Columns.Add(BattleGround_Columns.MaxLvl, "MaxLvl")
        Table.Columns.Add(BattleGround_Columns.Band, "Band")
        Table.Columns.Add(BattleGround_Columns.AllianceStartLoc, "AllianceStartLoc")
        Table.Columns.Add(BattleGround_Columns.AllianceStartO, "AllianceStartO")
        Table.Columns.Add(BattleGround_Columns.HordeStartLoc, "HordeStartLoc")
        Table.Columns.Add(BattleGround_Columns.HordeStartO, "HordeStartO")
        Table.Columns.Add(BattleGround_Columns.IsActive, "IsActive")

        'AreaTrigger_InvolvedRelation
        Table = New TTable("areatrigger_involvedrelation", TableTypes.AreaTrigger_InvolvedRelation)
        Tables.Add(Table)
        Table.Columns.Add(AreaTrigger_Columns.TriggerID, "id")
        Table.Columns.Add(AreaTrigger_Columns.quest, "quest")

        'AreaTrigger_Tavern
        Table = New TTable("areatrigger_tavern", TableTypes.AreaTrigger_Tavern)
        Tables.Add(Table)
        Table.Columns.Add(AreaTrigger_Columns.TriggerID, "id")
        Table.Columns.Add(AreaTrigger_Columns.name, "name")

        'AreaTrigger_Teleport
        Table = New TTable("areatrigger_teleport", TableTypes.AreaTrigger_Template)
        Tables.Add(Table)
        Table.Columns.Add(AreaTrigger_Columns.TriggerID, "id")
        Table.Columns.Add(AreaTrigger_Columns.name, "name")
        Table.Columns.Add(AreaTrigger_Columns.required_level, "required_level")
        Table.Columns.Add(AreaTrigger_Columns.required_item, "required_item")
        Table.Columns.Add(AreaTrigger_Columns.required_item2, "required_item2")
        Table.Columns.Add(AreaTrigger_Columns.heroic_key, "heroic_key")
        Table.Columns.Add(AreaTrigger_Columns.heroic_key2, "heroic_key2")
        Table.Columns.Add(AreaTrigger_Columns.required_quest_done, "required_quest_done")
        Table.Columns.Add(AreaTrigger_Columns.required_failed_text, "required_failed_text")
        Table.Columns.Add(AreaTrigger_Columns.target_map, "target_map")
        Table.Columns.Add(AreaTrigger_Columns.target_position_x, "target_position_x")
        Table.Columns.Add(AreaTrigger_Columns.target_position_y, "target_position_y")
        Table.Columns.Add(AreaTrigger_Columns.target_position_z, "target_position_z")
        Table.Columns.Add(AreaTrigger_Columns.target_orientation, "target_orientation")

        'Queststarters
        Table = New TTable("queststarters", TableTypes.QuestStartersCreature)
        Tables.Add(Table)
        Table.Columns.Add(QuestStarter_Columns.Type, "type")
        Table.Columns.Add(QuestStarter_Columns.TypeID, "typeid")
        Table.Columns.Add(QuestStarter_Columns.QuestID, "questid")

        'QuestStarters
        Table = New TTable("queststarters", TableTypes.QuestStartersGameobject)
        Tables.Add(Table)
        Table.Columns.Add(QuestStarter_Columns.Type, "type")
        Table.Columns.Add(QuestStarter_Columns.TypeID, "typeid")
        Table.Columns.Add(QuestStarter_Columns.QuestID, "questid")

        'QuestFinishers
        Table = New TTable("questfinishers", TableTypes.QuestFinishersCreature)
        Tables.Add(Table)
        Table.Columns.Add(QuestFinisher_Columns.Type, "type")
        Table.Columns.Add(QuestFinisher_Columns.TypeID, "typeid")
        Table.Columns.Add(QuestFinisher_Columns.QuestID, "questid")

        'Questfinishers
        Table = New TTable("questfinishers", TableTypes.QuestFinishersGameobject)
        Tables.Add(Table)
        Table.Columns.Add(QuestFinisher_Columns.Type, "type")
        Table.Columns.Add(QuestFinisher_Columns.TypeID, "typeid")
        Table.Columns.Add(QuestFinisher_Columns.QuestID, "questid")

        'Spells_Teleport_Coords
        Table = New TTable("spells_teleport_coords", TableTypes.SpellTeleportCoords)
        Tables.Add(Table)
        Table.Columns.Add(SpellTeleportCoords_Columns.ID, "id")
        Table.Columns.Add(SpellTeleportCoords_Columns.Name, "name")
        Table.Columns.Add(SpellTeleportCoords_Columns.Map, "mapId")
        Table.Columns.Add(SpellTeleportCoords_Columns.PosX, "position_x")
        Table.Columns.Add(SpellTeleportCoords_Columns.PosY, "position_y")
        Table.Columns.Add(SpellTeleportCoords_Columns.PosZ, "position_z")
        Table.Columns.Add(SpellTeleportCoords_Columns.ToTrigger, "totrigger")

        'Gameobject_Quest_Association
        Table = New TTable("gameobject_quest_association", TableTypes.GameObjectQuestAssociation)
        Tables.Add(Table)
        Table.Columns.Add(GameObjectQuestAssociation_Columns.Entry, "entry")
        Table.Columns.Add(GameObjectQuestAssociation_Columns.Quest, "quest")
        Table.Columns.Add(GameObjectQuestAssociation_Columns.Item, "item")
        Table.Columns.Add(GameObjectQuestAssociation_Columns.ItemCount, "item_count")

        'NpcText
        Table = New TTable("npctext", TableTypes.NpcText)
        Tables.Add(Table)
        Table.Columns.Add(NpcText_Columns.Entry, "entry")
        Table.Columns.Add(NpcText_Columns.Prob0, "prob0")
        Table.Columns.Add(NpcText_Columns.Text0_0, "text0_0")
        Table.Columns.Add(NpcText_Columns.Text0_1, "text0_1")
        Table.Columns.Add(NpcText_Columns.Lang0, "lang0")
        Table.Columns.Add(NpcText_Columns.em0_0, "em0_0")
        Table.Columns.Add(NpcText_Columns.em0_1, "em0_1")
        Table.Columns.Add(NpcText_Columns.em0_2, "em0_2")
        Table.Columns.Add(NpcText_Columns.em0_3, "em0_3")
        Table.Columns.Add(NpcText_Columns.em0_4, "em0_4")
        Table.Columns.Add(NpcText_Columns.em0_5, "em0_5")
        Table.Columns.Add(NpcText_Columns.Prob1, "prob1")
        Table.Columns.Add(NpcText_Columns.Text1_0, "text1_0")
        Table.Columns.Add(NpcText_Columns.Text1_1, "text1_1")
        Table.Columns.Add(NpcText_Columns.Lang1, "lang1")
        Table.Columns.Add(NpcText_Columns.em1_0, "em1_0")
        Table.Columns.Add(NpcText_Columns.em1_1, "em1_1")
        Table.Columns.Add(NpcText_Columns.em1_2, "em1_2")
        Table.Columns.Add(NpcText_Columns.em1_3, "em1_3")
        Table.Columns.Add(NpcText_Columns.em1_4, "em1_4")
        Table.Columns.Add(NpcText_Columns.em1_5, "em1_5")
        Table.Columns.Add(NpcText_Columns.Prob2, "prob2")
        Table.Columns.Add(NpcText_Columns.Text2_0, "text2_0")
        Table.Columns.Add(NpcText_Columns.Text2_1, "text2_1")
        Table.Columns.Add(NpcText_Columns.Lang2, "lang2")
        Table.Columns.Add(NpcText_Columns.em2_0, "em2_0")
        Table.Columns.Add(NpcText_Columns.em2_1, "em2_1")
        Table.Columns.Add(NpcText_Columns.em2_2, "em2_2")
        Table.Columns.Add(NpcText_Columns.em2_3, "em2_3")
        Table.Columns.Add(NpcText_Columns.em2_4, "em2_4")
        Table.Columns.Add(NpcText_Columns.em2_5, "em2_5")
        Table.Columns.Add(NpcText_Columns.Prob3, "prob3")
        Table.Columns.Add(NpcText_Columns.Text3_0, "text3_0")
        Table.Columns.Add(NpcText_Columns.Text3_1, "text3_1")
        Table.Columns.Add(NpcText_Columns.Lang3, "lang3")
        Table.Columns.Add(NpcText_Columns.em3_0, "em3_0")
        Table.Columns.Add(NpcText_Columns.em3_1, "em3_1")
        Table.Columns.Add(NpcText_Columns.em3_2, "em3_2")
        Table.Columns.Add(NpcText_Columns.em3_3, "em3_3")
        Table.Columns.Add(NpcText_Columns.em3_4, "em3_4")
        Table.Columns.Add(NpcText_Columns.em3_5, "em3_5")
        Table.Columns.Add(NpcText_Columns.Prob4, "prob4")
        Table.Columns.Add(NpcText_Columns.Text4_0, "text4_0")
        Table.Columns.Add(NpcText_Columns.Text4_1, "text4_1")
        Table.Columns.Add(NpcText_Columns.Lang4, "lang4")
        Table.Columns.Add(NpcText_Columns.em4_0, "em4_0")
        Table.Columns.Add(NpcText_Columns.em4_1, "em4_1")
        Table.Columns.Add(NpcText_Columns.em4_2, "em4_2")
        Table.Columns.Add(NpcText_Columns.em4_3, "em4_3")
        Table.Columns.Add(NpcText_Columns.em4_4, "em4_4")
        Table.Columns.Add(NpcText_Columns.em4_5, "em4_5")
        Table.Columns.Add(NpcText_Columns.Prob5, "prob5")
        Table.Columns.Add(NpcText_Columns.Text5_0, "text5_0")
        Table.Columns.Add(NpcText_Columns.Text5_1, "text5_1")
        Table.Columns.Add(NpcText_Columns.Lang5, "lang5")
        Table.Columns.Add(NpcText_Columns.em5_0, "em5_0")
        Table.Columns.Add(NpcText_Columns.em5_1, "em5_1")
        Table.Columns.Add(NpcText_Columns.em5_2, "em5_2")
        Table.Columns.Add(NpcText_Columns.em5_3, "em5_3")
        Table.Columns.Add(NpcText_Columns.em5_4, "em5_4")
        Table.Columns.Add(NpcText_Columns.em5_5, "em5_5")
        Table.Columns.Add(NpcText_Columns.Prob6, "prob6")
        Table.Columns.Add(NpcText_Columns.Text6_0, "text6_0")
        Table.Columns.Add(NpcText_Columns.Text6_1, "text6_1")
        Table.Columns.Add(NpcText_Columns.Lang6, "lang6")
        Table.Columns.Add(NpcText_Columns.em6_0, "em6_0")
        Table.Columns.Add(NpcText_Columns.em6_1, "em6_1")
        Table.Columns.Add(NpcText_Columns.em6_2, "em6_2")
        Table.Columns.Add(NpcText_Columns.em6_3, "em6_3")
        Table.Columns.Add(NpcText_Columns.em6_4, "em6_4")
        Table.Columns.Add(NpcText_Columns.em6_5, "em6_5")
        Table.Columns.Add(NpcText_Columns.Prob7, "prob7")
        Table.Columns.Add(NpcText_Columns.Text7_0, "text7_0")
        Table.Columns.Add(NpcText_Columns.Text7_1, "text7_1")
        Table.Columns.Add(NpcText_Columns.Lang7, "lang7")
        Table.Columns.Add(NpcText_Columns.em7_0, "em7_0")
        Table.Columns.Add(NpcText_Columns.em7_1, "em7_1")
        Table.Columns.Add(NpcText_Columns.em7_2, "em7_2")
        Table.Columns.Add(NpcText_Columns.em7_3, "em7_3")
        Table.Columns.Add(NpcText_Columns.em7_4, "em7_4")
        Table.Columns.Add(NpcText_Columns.em7_5, "em7_5")

        'Npc_Vendor
        Table = New TTable("npc_vendor", TableTypes.NpcVendor)
        Tables.Add(Table)
        Table.Columns.Add(NpcVendor_Columns.Entry, "entry")
        Table.Columns.Add(NpcVendor_Columns.Item, "item")
        Table.Columns.Add(NpcVendor_Columns.Amount, "sellamount")
        Table.Columns.Add(NpcVendor_Columns.Stock, "maxcount")
        Table.Columns.Add(NpcVendor_Columns.Refill, "incrtime")
        Table.Columns.Add(NpcVendor_Columns.ExtendedCost, "extendedcost")

        'Npc_Gossip_TextID
        Table = New TTable("npc_gossip_textid", TableTypes.NpcGossipTextID)
        Tables.Add(Table)
        Table.Columns.Add(NpcGossipTextID_Columns.Entry, "creatureid")
        Table.Columns.Add(NpcGossipTextID_Columns.TextID, "textid")

        'Trainer_Defs
        Table = New TTable("trainer_defs", TableTypes.NpcTrainerDefs)
        Tables.Add(Table)
        Table.Columns.Add(NpcTrainerDef_Columns.Entry, "entry")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqSkill, "required_skill")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqSkillValue, "required_skillvalue")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqRace, "")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqClass, "req_class")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqSpell, "")
        Table.Columns.Add(NpcTrainerDef_Columns.TrainerType, "trainer_type")
        Table.Columns.Add(NpcTrainerDef_Columns.WindowMessage, "trainer_ui_window_message")
        Table.Columns.Add(NpcTrainerDef_Columns.CanTrainMessage, "can_train_gossip_textid")
        Table.Columns.Add(NpcTrainerDef_Columns.CanNotTrainMessage, "cannot_train_gossip_textid")

        'Trainer_Spells
        Table = New TTable("trainer_spells", TableTypes.NpcTrainerSpells)
        Tables.Add(Table)
        Table.Columns.Add(NpcTrainerSpell_Columns.Entry, "entry")
        Table.Columns.Add(NpcTrainerSpell_Columns.Spell, "spellid")
        Table.Columns.Add(NpcTrainerSpell_Columns.SpellCost, "spellcost")
        Table.Columns.Add(NpcTrainerSpell_Columns.ReqSpell, "reqspell")
        Table.Columns.Add(NpcTrainerSpell_Columns.ReqSkill, "reqskill")
        Table.Columns.Add(NpcTrainerSpell_Columns.ReqSkillValue, "reqskillvalue")
        Table.Columns.Add(NpcTrainerSpell_Columns.ReqLevel, "reqlevel")
        Table.Columns.Add(NpcTrainerSpell_Columns.DeleteSpell, "deletespell")
        Table.Columns.Add(NpcTrainerSpell_Columns.IsProf, "is_prof")
        Table.Columns.Add(NpcTrainerSpell_Columns.IsCast, "is_cast")

        'Items_RandomProp_Groups
        Table = New TTable("item_randomprop_groups", TableTypes.ItemRandomPropGroups)
        Tables.Add(Table)
        Table.Columns.Add(ItemRandom_Columns.ItemEntry, "entry_id")
        Table.Columns.Add(ItemRandom_Columns.RandomPropsEntryID, "randomprops_entryid")
        Table.Columns.Add(ItemRandom_Columns.Chance, "chance")

        'Items_RandomSuffix_Groups
        Table = New TTable("item_randomsuffix_groups", TableTypes.ItemSuffixGroups)
        Tables.Add(Table)
        Table.Columns.Add(ItemRandom_Columns.ItemEntry, "entry_id")
        Table.Columns.Add(ItemRandom_Columns.RandomSuffixEntryID, "randomsuffix_entryid")
        Table.Columns.Add(ItemRandom_Columns.Chance, "chance")

        'ItemPages
        Table = New TTable("itempages", TableTypes.ItemPages)
        Tables.Add(Table)
        Table.Columns.Add(ItemPages_Columns.ItemEntry, "entry")
        Table.Columns.Add(ItemPages_Columns.Text, "text")
        Table.Columns.Add(ItemPages_Columns.NextPage, "next_page")

        'Items_FoodType
        Table = New TTable("itempetfood", TableTypes.ItemPetFood)
        Tables.Add(Table)
        Table.Columns.Add(PetFood_Columns.ItemEntry, "entry")
        Table.Columns.Add(PetFood_Columns.FoodType, "food_type")

        'PlayerCreateInfo
        Table = New TTable("playercreateinfo", TableTypes.PlayerCreateInfo)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfo_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfo_Columns.Faction, "factiontemplate")
        Table.Columns.Add(PlayerCreateInfo_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfo_Columns.StartMap, "MapID")
        Table.Columns.Add(PlayerCreateInfo_Columns.StartZone, "ZoneID")
        Table.Columns.Add(PlayerCreateInfo_Columns.StartX, "positionX")
        Table.Columns.Add(PlayerCreateInfo_Columns.StartY, "positionY")
        Table.Columns.Add(PlayerCreateInfo_Columns.StartZ, "positionZ")
        Table.Columns.Add(PlayerCreateInfo_Columns.MaleModelOffset, "displayID")
        Table.Columns.Add(PlayerCreateInfo_Columns.PowerType, "PowerType")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseStrength, "BaseStrength")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseAgility, "BaseAgility")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseStamina, "BaseStamina")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseIntellect, "BaseIntellect")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseSpirit, "BaseSpirit")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseHealth, "BaseHealth")
        Table.Columns.Add(PlayerCreateInfo_Columns.BasePower, "BasePower")
        Table.Columns.Add(PlayerCreateInfo_Columns.MinDamage, "mindmg")
        Table.Columns.Add(PlayerCreateInfo_Columns.MaxDamage, "maxdmg")

        'PlayerCreateInfo_Bars
        Table = New TTable("playercreateinfo_bars", TableTypes.PlayerCreateInfo_Bars)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Button, "button")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Action, "action")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Type, "type")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Misc, "misc")

        'PlayerCreateInfo_Items
        Table = New TTable("playercreateinfo_items", TableTypes.PlayerCreateInfo_Items)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoItem_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.ItemID, "protoid")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.Slot, "slotid")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.Amount, "amount")

        'PlayerCreateInfo_Skills
        Table = New TTable("playercreateinfo_skills", TableTypes.PlayerCreateInfo_Skills)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.SkillID, "skillid")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.Level, "level")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.MaxLevel, "maxlevel")

        'PlayerCreateInfo_Spells
        Table = New TTable("playercreateinfo_spells", TableTypes.PlayerCreateInfo_Spells)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoSpell_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfoSpell_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfoSpell_Columns.SpellID, "spellid")

        'Npc_MonsterSay
        Table = New TTable("npc_monstersay", TableTypes.MonsterSay)
        Tables.Add(Table)
        Table.Columns.Add(MonsterSay_Columns.CreatureEntry, "entry")
        Table.Columns.Add(MonsterSay_Columns.Evente, "event")
        Table.Columns.Add(MonsterSay_Columns.Chance, "chance")
        Table.Columns.Add(MonsterSay_Columns.Language, "language")
        Table.Columns.Add(MonsterSay_Columns.Type, "type")
        Table.Columns.Add(MonsterSay_Columns.MonsterName, "monstername")
        Table.Columns.Add(MonsterSay_Columns.Text0, "text0")
        Table.Columns.Add(MonsterSay_Columns.Text1, "text1")
        Table.Columns.Add(MonsterSay_Columns.Text2, "text2")
        Table.Columns.Add(MonsterSay_Columns.Text3, "text3")
        Table.Columns.Add(MonsterSay_Columns.Text4, "text4")

        'Loots_Skinning
        Table = New TTable("loots_skinning", TableTypes.LootsSkinning)
        Tables.Add(Table)
        Table.Columns.Add(LootsSkinning_Columns.CreatureEntry, "loot_creature")
        Table.Columns.Add(LootsSkinning_Columns.ItemID, "loot_item")
        Table.Columns.Add(LootsSkinning_Columns.PercentChance, "loot_chance")
        Table.Columns.Add(LootsSkinning_Columns.HeroicPercentChance, "loot_heroicchance")
        Table.Columns.Add(LootsSkinning_Columns.MinCount, "loot_min")
        Table.Columns.Add(LootsSkinning_Columns.MaxCount, "loot_max")
        Table.Columns.Add(LootsSkinning_Columns.FFA_Loot, "loot_ffa")

        'Loot_Item
        Table = New TTable("itemloot", TableTypes.LootsItem)
        Tables.Add(Table)
        Table.Columns.Add(LootsItem_Columns.ItemEntry, "entryid")
        Table.Columns.Add(LootsItem_Columns.ItemID, "itemid")
        Table.Columns.Add(LootsItem_Columns.PercentChance, "percentchance")
        Table.Columns.Add(LootsItem_Columns.HeroicPercentChance, "heroicpercentchance")
        Table.Columns.Add(LootsItem_Columns.MinCount, "mincount")
        Table.Columns.Add(LootsItem_Columns.MaxCount, "maxcount")
        Table.Columns.Add(LootsItem_Columns.FFA_Loot, "ffa_loot")

        'World_CmdTeleports
        Table = New TTable("world_cmdteleports", TableTypes.CmdTeleports)
        Tables.Add(Table)
        Table.Columns.Add(CmdTeleports_Columns.Id, "id")
        Table.Columns.Add(CmdTeleports_Columns.Name, "name")
        Table.Columns.Add(CmdTeleports_Columns.MapID, "MapId")
        Table.Columns.Add(CmdTeleports_Columns.PositionX, "positionX")
        Table.Columns.Add(CmdTeleports_Columns.PositionY, "positionY")
        Table.Columns.Add(CmdTeleports_Columns.PositionZ, "positionZ")

        'Creatures_Movement
        Table = New TTable("creature_movement", TableTypes.creature_movement)
        Tables.Add(Table)
        Table.Columns.Add(Creature_Movement_Columns.spawnid, "spawnid")
        Table.Columns.Add(Creature_Movement_Columns.waypointid, "waypointid")
        Table.Columns.Add(Creature_Movement_Columns.position_x, "position_x")
        Table.Columns.Add(Creature_Movement_Columns.position_y, "position_y")
        Table.Columns.Add(Creature_Movement_Columns.position_z, "position_z")
        Table.Columns.Add(Creature_Movement_Columns.waittime, "waittime")
        Table.Columns.Add(Creature_Movement_Columns.flags, "flags")
        Table.Columns.Add(Creature_Movement_Columns.emote, "emote")
        Table.Columns.Add(Creature_Movement_Columns.orientation, "orientation")
    End Sub
End Class
