Public Class Spurious
    Inherits WhyDBBaseDB

    Public Sub New()
        InitTables()
    End Sub

    Public Sub InitTables()
        Dim Table As TTable
        'Creatures
        Table = New TTable("creatures", TableTypes.CreatureInfo)
        Tables.Add(Table)
        Table.Columns.Add(CreatureInfo_Columns.Entry, "creature_id")
        Table.Columns.Add(CreatureInfo_Columns.Name, "creature_name")
        Table.Columns.Add(CreatureInfo_Columns.SubName, "creature_guild")
        Table.Columns.Add(CreatureInfo_Columns.InfoStr, "info_str")
        Table.Columns.Add(CreatureInfo_Columns.KillCredit1, "KillCredit1")
        Table.Columns.Add(CreatureInfo_Columns.KillCredit2, "KillCredit2")
        Table.Columns.Add(CreatureInfo_Columns.MaleDisplayID, "creature_model")
        Table.Columns.Add(CreatureInfo_Columns.FemaleDisplayID, "creature_femalemodel")
        Table.Columns.Add(CreatureInfo_Columns.MaleDisplayID2, "creature_model2")
        Table.Columns.Add(CreatureInfo_Columns.FemaleDisplayID2, "creature_femalemodel2")
        Table.Columns.Add(CreatureInfo_Columns.Size, "creature_size")
        Table.Columns.Add(CreatureInfo_Columns.MinLife, "creature_minlife")
        Table.Columns.Add(CreatureInfo_Columns.MaxLife, "creature_maxlife")
        Table.Columns.Add(CreatureInfo_Columns.MinMana, "creature_minmana")
        Table.Columns.Add(CreatureInfo_Columns.MaxMana, "creature_maxmana")
        Table.Columns.Add(CreatureInfo_Columns.ManaType, "creature_manaType")
        Table.Columns.Add(CreatureInfo_Columns.Boss, "creature_boss")
        Table.Columns.Add(CreatureInfo_Columns.Rank, "creature_elite")
        Table.Columns.Add(CreatureInfo_Columns.Leader, "creature_leader")
        Table.Columns.Add(CreatureInfo_Columns.Faction, "creature_faction")
        Table.Columns.Add(CreatureInfo_Columns.Family, "creature_family")
        Table.Columns.Add(CreatureInfo_Columns.Type, "creature_type")
        Table.Columns.Add(CreatureInfo_Columns.SpellDataID, "creature_spelldataid")
        Table.Columns.Add(CreatureInfo_Columns.MinDamage, "creature_minDamage")
        Table.Columns.Add(CreatureInfo_Columns.MaxDamage, "creature_maxDamage")
        Table.Columns.Add(CreatureInfo_Columns.MinRangedDamage, "creature_minRangedDamage")
        Table.Columns.Add(CreatureInfo_Columns.MaxRangedDamage, "creature_maxRangedDamage")
        Table.Columns.Add(CreatureInfo_Columns.Armor, "creature_armor")
        Table.Columns.Add(CreatureInfo_Columns.ResHoly, "creature_resHoly")
        Table.Columns.Add(CreatureInfo_Columns.ResFire, "creature_resFire")
        Table.Columns.Add(CreatureInfo_Columns.ResNature, "creature_resNature")
        Table.Columns.Add(CreatureInfo_Columns.ResFrost, "creature_resFrost")
        Table.Columns.Add(CreatureInfo_Columns.ResShadow, "creature_resShadow")
        Table.Columns.Add(CreatureInfo_Columns.ResArcane, "creature_resArcane")
        Table.Columns.Add(CreatureInfo_Columns.WalkSpeed, "creature_walkSpeed")
        Table.Columns.Add(CreatureInfo_Columns.RunSpeed, "creature_runSpeed")
        Table.Columns.Add(CreatureInfo_Columns.FlySpeed, "creature_flySpeed")
        Table.Columns.Add(CreatureInfo_Columns.RespawnTime, "creature_respawnTime")
        Table.Columns.Add(CreatureInfo_Columns.BaseAttackSpeed, "creature_baseAttackSpeed")
        Table.Columns.Add(CreatureInfo_Columns.BaseRangedAttackSpeed, "creature_baseRangedAttackSpeed")
        Table.Columns.Add(CreatureInfo_Columns.CombatReach, "creature_combatReach")
        Table.Columns.Add(CreatureInfo_Columns.BondingRadius, "creature_bondingRadius")
        Table.Columns.Add(CreatureInfo_Columns.NpcFlags, "creature_npcFlags")
        Table.Columns.Add(CreatureInfo_Columns.Flags, "creature_flags")
        Table.Columns.Add(CreatureInfo_Columns.MinLevel, "creature_minLevel")
        Table.Columns.Add(CreatureInfo_Columns.MaxLevel, "creature_maxLevel")
        Table.Columns.Add(CreatureInfo_Columns.Loot, "creature_loot")
        Table.Columns.Add(CreatureInfo_Columns.SkinLoot, "creature_skinloot")
        Table.Columns.Add(CreatureInfo_Columns.PickpocketLoot, "creature_pickpocketloot")
        Table.Columns.Add(CreatureInfo_Columns.EquipmentEntry, "creature_equipmententry")
        Table.Columns.Add(CreatureInfo_Columns.EquipModel1, "creature_equipmodel1")
        Table.Columns.Add(CreatureInfo_Columns.EquipModel2, "creature_equipmodel2")
        Table.Columns.Add(CreatureInfo_Columns.EquipModel3, "creature_equipmodel3")
        Table.Columns.Add(CreatureInfo_Columns.EquipInfo1, "creature_equipinfo1")
        Table.Columns.Add(CreatureInfo_Columns.EquipInfo2, "creature_equipinfo2")
        Table.Columns.Add(CreatureInfo_Columns.EquipInfo3, "creature_equipinfor3")
        Table.Columns.Add(CreatureInfo_Columns.EquipSlot1, "creature_equipslot1")
        Table.Columns.Add(CreatureInfo_Columns.EquipSlot2, "creature_equipslot2")
        Table.Columns.Add(CreatureInfo_Columns.EquipSlot3, "creature_equipslot3")
        Table.Columns.Add(CreatureInfo_Columns.UnknownFloat1, "creature_unkfloat1")
        Table.Columns.Add(CreatureInfo_Columns.UnknownFloat2, "creature_unkfloat2")
        Table.Columns.Add(CreatureInfo_Columns.AiScript, "creature_aiScript")
        Table.Columns.Add(CreatureInfo_Columns.MinGold, "creature_minGold")
        Table.Columns.Add(CreatureInfo_Columns.MaxGold, "creature_maxGold")
        Table.Columns.Add(CreatureInfo_Columns.TrainerType, "creature_trainerType")
        Table.Columns.Add(CreatureInfo_Columns.TrainerSpell, "creature_trainerSpell")
        Table.Columns.Add(CreatureInfo_Columns.TrainerClass, "creature_trainerClass")
        Table.Columns.Add(CreatureInfo_Columns.TrainerRace, "creature_trainerRace")
        Table.Columns.Add(CreatureInfo_Columns.MovementType, "creature_movementType")
        Table.Columns.Add(CreatureInfo_Columns.RegenHealth, "creature_regenHealth")
        Table.Columns.Add(CreatureInfo_Columns.ModImmunities, "creature_mechanicImmuneMask")
        Table.Columns.Add(CreatureInfo_Columns.ExtraA9Flags, "creature_flagsExtra")
        Table.Columns.Add(CreatureInfo_Columns.QuestItem1, "questItem1")
        Table.Columns.Add(CreatureInfo_Columns.QuestItem2, "questItem2")
        Table.Columns.Add(CreatureInfo_Columns.QuestItem3, "questItem3")
        Table.Columns.Add(CreatureInfo_Columns.QuestItem4, "questItem4")
        Table.Columns.Add(CreatureInfo_Columns.QuestItem5, "questItem5")
        Table.Columns.Add(CreatureInfo_Columns.QuestItem6, "questItem6")

        'Spawns_Creatures
        Table = New TTable("spawns_creatures", TableTypes.CreatureSpawn)
        Tables.Add(Table)
        Table.Columns.Add(CreatureSpawn_Columns.ID, "spawn_id")
        Table.Columns.Add(CreatureSpawn_Columns.Entry, "spawn_entry")
        Table.Columns.Add(CreatureSpawn_Columns.PositionX, "spawn_positionX")
        Table.Columns.Add(CreatureSpawn_Columns.PositionY, "spawn_positionY")
        Table.Columns.Add(CreatureSpawn_Columns.PositionZ, "spawn_positionZ")
        Table.Columns.Add(CreatureSpawn_Columns.Orientation, "spawn_orientation")
        Table.Columns.Add(CreatureSpawn_Columns.Range, "spawn_range")
        Table.Columns.Add(CreatureSpawn_Columns.Map, "spawn_map")
        Table.Columns.Add(CreatureSpawn_Columns.MoveType, "spawn_movetype")
        Table.Columns.Add(CreatureSpawn_Columns.Model, "spawn_displayid")
        Table.Columns.Add(CreatureSpawn_Columns.Faction, "spawn_faction")
        Table.Columns.Add(CreatureSpawn_Columns.Mount, "spawn_mount")
        Table.Columns.Add(CreatureSpawn_Columns.Flags, "spawn_flags")
        Table.Columns.Add(CreatureSpawn_Columns.Bytes0, "spawn_bytes0")
        Table.Columns.Add(CreatureSpawn_Columns.Bytes1, "spawn_bytes1")
        Table.Columns.Add(CreatureSpawn_Columns.Bytes2, "spawn_bytes2")
        Table.Columns.Add(CreatureSpawn_Columns.EmoteState, "spawn_emotestate")
        Table.Columns.Add(CreatureSpawn_Columns.StandState, "spawn_standstate")
        Table.Columns.Add(CreatureSpawn_Columns.equipslot1, "spawn_equipslot1")
        Table.Columns.Add(CreatureSpawn_Columns.equipslot2, "spawn_equipslot2")
        Table.Columns.Add(CreatureSpawn_Columns.equipslot3, "spawn_equipslot3")

        'Gameobjects
        Table = New TTable("gameobjects", TableTypes.GameobjectInfo)
        Tables.Add(Table)
        Table.Columns.Add(GameobjectInfo_Columns.Entry, "gameObject_ID")
        Table.Columns.Add(GameobjectInfo_Columns.Model, "gameObject_Model")
        Table.Columns.Add(GameobjectInfo_Columns.Name, "gameObject_Name")
        Table.Columns.Add(GameobjectInfo_Columns.Category, "gameObject_IconName")
        Table.Columns.Add(GameobjectInfo_Columns.CastBarCaption, "gameObject_CastBarCaption")
        Table.Columns.Add(GameobjectInfo_Columns.Type, "gameObject_Type")
        Table.Columns.Add(GameobjectInfo_Columns.RespawnTime, "gameObject_RespawnTime")
        Table.Columns.Add(GameobjectInfo_Columns.Scale, "gameObject_Size")
        Table.Columns.Add(GameobjectInfo_Columns.Field0, "gameObject_Field0")
        Table.Columns.Add(GameobjectInfo_Columns.Field1, "gameObject_Field1")
        Table.Columns.Add(GameobjectInfo_Columns.Field2, "gameObject_Field2")
        Table.Columns.Add(GameobjectInfo_Columns.Field3, "gameObject_Field3")
        Table.Columns.Add(GameobjectInfo_Columns.Field4, "gameObject_Field4")
        Table.Columns.Add(GameobjectInfo_Columns.Field5, "gameObject_Field5")
        Table.Columns.Add(GameobjectInfo_Columns.Field6, "gameObject_Field6")
        Table.Columns.Add(GameobjectInfo_Columns.Field7, "gameObject_Field7")
        Table.Columns.Add(GameobjectInfo_Columns.Field8, "gameObject_Field8")
        Table.Columns.Add(GameobjectInfo_Columns.Field9, "gameObject_Field9")
        Table.Columns.Add(GameobjectInfo_Columns.Field10, "gameObject_Field10")
        Table.Columns.Add(GameobjectInfo_Columns.Field11, "gameObject_Field11")
        Table.Columns.Add(GameobjectInfo_Columns.Field12, "gameObject_Field12")
        Table.Columns.Add(GameobjectInfo_Columns.Field13, "gameObject_Field13")
        Table.Columns.Add(GameobjectInfo_Columns.Field14, "gameObject_Field14")
        Table.Columns.Add(GameobjectInfo_Columns.Field15, "gameObject_Field15")
        Table.Columns.Add(GameobjectInfo_Columns.Field16, "gameObject_Field16")
        Table.Columns.Add(GameobjectInfo_Columns.Field17, "gameObject_Field17")
        Table.Columns.Add(GameobjectInfo_Columns.Field18, "gameObject_Field18")
        Table.Columns.Add(GameobjectInfo_Columns.Field19, "gameObject_Field19")
        Table.Columns.Add(GameobjectInfo_Columns.Field20, "gameObject_Field20")
        Table.Columns.Add(GameobjectInfo_Columns.Field21, "gameObject_Field21")
        Table.Columns.Add(GameobjectInfo_Columns.Field22, "gameObject_Field22")
        Table.Columns.Add(GameobjectInfo_Columns.Field23, "gameObject_Field23")
        Table.Columns.Add(GameobjectInfo_Columns.QuestItem1, "gameObject_QuestItem0")
        Table.Columns.Add(GameobjectInfo_Columns.QuestItem2, "gameObject_QuestItem1")
        Table.Columns.Add(GameobjectInfo_Columns.QuestItem3, "gameObject_QuestItem2")
        Table.Columns.Add(GameobjectInfo_Columns.QuestItem4, "gameObject_QuestItem3")
        Table.Columns.Add(GameobjectInfo_Columns.QuestItem5, "gameObject_QuestItem4")
        Table.Columns.Add(GameobjectInfo_Columns.QuestItem6, "gameObject_QuestItem5")

        'Spawns_Gameobjects
        Table = New TTable("spawns_gameobjects", TableTypes.GameobjectSpawn)
        Tables.Add(Table)
        Table.Columns.Add(GameobjectSpawn_Columns.ID, "spawn_id")
        Table.Columns.Add(GameobjectSpawn_Columns.Entry, "spawn_entry")
        Table.Columns.Add(GameobjectSpawn_Columns.PositionX, "spawn_positionX")
        Table.Columns.Add(GameobjectSpawn_Columns.PositionY, "spawn_positionY")
        Table.Columns.Add(GameobjectSpawn_Columns.PositionZ, "spawn_positionZ")
        Table.Columns.Add(GameobjectSpawn_Columns.Orientation, "spawn_orientation")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation1, "spawn_orientation1")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation2, "spawn_orientation2")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation3, "spawn_orientation3")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation4, "spawn_orientation4")
        Table.Columns.Add(GameobjectSpawn_Columns.Map, "spawn_map")
        Table.Columns.Add(GameobjectSpawn_Columns.State, "spawn_state")
        Table.Columns.Add(GameobjectSpawn_Columns.Flags, "spawn_flags")
        Table.Columns.Add(GameobjectSpawn_Columns.Faction, "spawn_faction")
        Table.Columns.Add(GameobjectSpawn_Columns.Scale, "spawn_scale")

        'Items
        Table = New TTable("items", TableTypes.Items)
        Tables.Add(Table)
        Table.Columns.Add(Item_Columns.Entry, "entry")
        Table.Columns.Add(Item_Columns.Classe, "class")
        Table.Columns.Add(Item_Columns.SubClass, "subclass")
        Table.Columns.Add(Item_Columns.Field4, "field4")
        Table.Columns.Add(Item_Columns.Name1, "name1")
        Table.Columns.Add(Item_Columns.Name2, "name2")
        Table.Columns.Add(Item_Columns.Name3, "name3")
        Table.Columns.Add(Item_Columns.Name4, "name4")
        Table.Columns.Add(Item_Columns.DisplayID, "displayid")
        Table.Columns.Add(Item_Columns.Quality, "quality")
        Table.Columns.Add(Item_Columns.Flags, "flags")
        Table.Columns.Add(Item_Columns.Faction, "faction")
        Table.Columns.Add(Item_Columns.BuyCount, "buycount")
        Table.Columns.Add(Item_Columns.Buyprice, "buyprice")
        Table.Columns.Add(Item_Columns.Sellprice, "sellprice")
        Table.Columns.Add(Item_Columns.InventoryType, "inventorytype")
        Table.Columns.Add(Item_Columns.AllowableClass, "allowableclass")
        Table.Columns.Add(Item_Columns.AllowableRace, "allowablerace")
        Table.Columns.Add(Item_Columns.ItemLevel, "itemlevel")
        Table.Columns.Add(Item_Columns.RequiredLevel, "requiredlevel")
        Table.Columns.Add(Item_Columns.RequiredSkill, "RequiredSkill")
        Table.Columns.Add(Item_Columns.RequiredSkillRank, "RequiredSkillRank")
        Table.Columns.Add(Item_Columns.RequiredSubRank, "RequiredSkillSubRank")
        Table.Columns.Add(Item_Columns.RequiredPlayerRank1, "RequiredPlayerRank1")
        Table.Columns.Add(Item_Columns.RequiredPlayerRank2, "RequiredPlayerRank2")
        Table.Columns.Add(Item_Columns.RequiredFaction, "RequiredFaction")
        Table.Columns.Add(Item_Columns.RequiredFactionStanding, "RequiredFactionStanding")
        Table.Columns.Add(Item_Columns.Unique, "Unique")
        Table.Columns.Add(Item_Columns.MaxCount, "maxcount")
        Table.Columns.Add(Item_Columns.ContainerSlots, "ContainerSlots")
        Table.Columns.Add(Item_Columns.StatsCount, "StatsCount")
        Table.Columns.Add(Item_Columns.Stat_Type1, "stat_type1")
        Table.Columns.Add(Item_Columns.Stat_Value1, "stat_value1")
        Table.Columns.Add(Item_Columns.Stat_Type2, "stat_type2")
        Table.Columns.Add(Item_Columns.Stat_Value2, "stat_value2")
        Table.Columns.Add(Item_Columns.Stat_Type3, "stat_type3")
        Table.Columns.Add(Item_Columns.Stat_Value3, "stat_value3")
        Table.Columns.Add(Item_Columns.Stat_Type4, "stat_type4")
        Table.Columns.Add(Item_Columns.Stat_Value4, "stat_value4")
        Table.Columns.Add(Item_Columns.Stat_Type5, "stat_type5")
        Table.Columns.Add(Item_Columns.Stat_Value5, "stat_value5")
        Table.Columns.Add(Item_Columns.Stat_Type6, "stat_type6")
        Table.Columns.Add(Item_Columns.Stat_Value6, "stat_value6")
        Table.Columns.Add(Item_Columns.Stat_Type7, "stat_type7")
        Table.Columns.Add(Item_Columns.Stat_Value7, "stat_value7")
        Table.Columns.Add(Item_Columns.Stat_Type8, "stat_type8")
        Table.Columns.Add(Item_Columns.Stat_Value8, "stat_value8")
        Table.Columns.Add(Item_Columns.Stat_Type9, "stat_type9")
        Table.Columns.Add(Item_Columns.Stat_Value9, "stat_value9")
        Table.Columns.Add(Item_Columns.Stat_Type10, "stat_type10")
        Table.Columns.Add(Item_Columns.Stat_Value10, "stat_value10")
        Table.Columns.Add(Item_Columns.ScaledStatsDistributionID, "ScalingStatDistribution")
        Table.Columns.Add(Item_Columns.ScaledStatsDistributionFlags, "ScalingStatValue")
        Table.Columns.Add(Item_Columns.Dmg_Min1, "dmg_min1")
        Table.Columns.Add(Item_Columns.Dmg_Max1, "dmg_max1")
        Table.Columns.Add(Item_Columns.Dmg_Type1, "dmg_type1")
        Table.Columns.Add(Item_Columns.Dmg_Min2, "dmg_min2")
        Table.Columns.Add(Item_Columns.Dmg_Max2, "dmg_max2")
        Table.Columns.Add(Item_Columns.Dmg_Type2, "dmg_type2")
        Table.Columns.Add(Item_Columns.Dmg_Min3, "dmg_min3")
        Table.Columns.Add(Item_Columns.Dmg_Max3, "dmg_max3")
        Table.Columns.Add(Item_Columns.Dmg_Type3, "dmg_type3")
        Table.Columns.Add(Item_Columns.Dmg_Min4, "dmg_min4")
        Table.Columns.Add(Item_Columns.Dmg_Max4, "dmg_max4")
        Table.Columns.Add(Item_Columns.Dmg_Type4, "dmg_type4")
        Table.Columns.Add(Item_Columns.Dmg_Min5, "dmg_min5")
        Table.Columns.Add(Item_Columns.Dmg_Max5, "dmg_max5")
        Table.Columns.Add(Item_Columns.Dmg_Type5, "dmg_type5")
        Table.Columns.Add(Item_Columns.Armor, "armor")
        Table.Columns.Add(Item_Columns.HolyRes, "holy_res")
        Table.Columns.Add(Item_Columns.FireRes, "fire_res")
        Table.Columns.Add(Item_Columns.NatureRes, "nature_res")
        Table.Columns.Add(Item_Columns.FrostRes, "frost_res")
        Table.Columns.Add(Item_Columns.ShadowRes, "shadow_res")
        Table.Columns.Add(Item_Columns.ArcaneRes, "arcane_res")
        Table.Columns.Add(Item_Columns.Delay, "delay")
        Table.Columns.Add(Item_Columns.AmmoType, "ammo_type")
        Table.Columns.Add(Item_Columns.Range, "range")
        Table.Columns.Add(Item_Columns.SpellID_1, "spellid_1")
        Table.Columns.Add(Item_Columns.SpellTrigger_1, "spelltrigger_1")
        Table.Columns.Add(Item_Columns.SpellCharges_1, "spellcharges_1")
        Table.Columns.Add(Item_Columns.SpellCooldown_1, "spellcooldown_1")
        Table.Columns.Add(Item_Columns.SpellCategory_1, "spellcategory_1")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_1, "spellcategorycooldown_1")
        Table.Columns.Add(Item_Columns.SpellID_2, "spellid_2")
        Table.Columns.Add(Item_Columns.SpellTrigger_2, "spelltrigger_2")
        Table.Columns.Add(Item_Columns.SpellCharges_2, "spellcharges_2")
        Table.Columns.Add(Item_Columns.SpellCooldown_2, "spellcooldown_2")
        Table.Columns.Add(Item_Columns.SpellCategory_2, "spellcategory_2")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_2, "spellcategorycooldown_2")
        Table.Columns.Add(Item_Columns.SpellID_3, "spellid_3")
        Table.Columns.Add(Item_Columns.SpellTrigger_3, "spelltrigger_3")
        Table.Columns.Add(Item_Columns.SpellCharges_3, "spellcharges_3")
        Table.Columns.Add(Item_Columns.SpellCooldown_3, "spellcooldown_3")
        Table.Columns.Add(Item_Columns.SpellCategory_3, "spellcategory_3")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_3, "spellcategorycooldown_3")
        Table.Columns.Add(Item_Columns.SpellID_4, "spellid_4")
        Table.Columns.Add(Item_Columns.SpellTrigger_4, "spelltrigger_4")
        Table.Columns.Add(Item_Columns.SpellCharges_4, "spellcharges_4")
        Table.Columns.Add(Item_Columns.SpellCooldown_4, "spellcooldown_4")
        Table.Columns.Add(Item_Columns.SpellCategory_4, "spellcategory_4")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_4, "spellcategorycooldown_4")
        Table.Columns.Add(Item_Columns.SpellID_5, "spellid_5")
        Table.Columns.Add(Item_Columns.SpellTrigger_5, "spelltrigger_5")
        Table.Columns.Add(Item_Columns.SpellCharges_5, "spellcharges_5")
        Table.Columns.Add(Item_Columns.SpellCooldown_5, "spellcooldown_5")
        Table.Columns.Add(Item_Columns.SpellCategory_5, "spellcategory_5")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_5, "spellcategorycooldown_5")
        Table.Columns.Add(Item_Columns.Bonding, "bonding")
        Table.Columns.Add(Item_Columns.Description, "description")
        Table.Columns.Add(Item_Columns.PageID, "page_id")
        Table.Columns.Add(Item_Columns.PageLanguage, "page_language")
        Table.Columns.Add(Item_Columns.PageMaterial, "page_material")
        Table.Columns.Add(Item_Columns.QuestID, "quest_id")
        Table.Columns.Add(Item_Columns.LockID, "lock_id")
        Table.Columns.Add(Item_Columns.LockMaterial, "lock_material")
        Table.Columns.Add(Item_Columns.SheathID, "sheathID")
        Table.Columns.Add(Item_Columns.RandomProp, "randomprop")
        Table.Columns.Add(Item_Columns.RandomSuffix, "randomsuffix")
        Table.Columns.Add(Item_Columns.Block, "block")
        Table.Columns.Add(Item_Columns.ItemSet, "itemset")
        Table.Columns.Add(Item_Columns.MaxDurability, "MaxDurability")
        Table.Columns.Add(Item_Columns.ZoneNameID, "ZoneNameID")
        Table.Columns.Add(Item_Columns.MapID, "mapid")
        Table.Columns.Add(Item_Columns.BagFamily, "bagfamily")
        Table.Columns.Add(Item_Columns.TotemCategory, "TotemCategory")
        Table.Columns.Add(Item_Columns.SocketColor_1, "socket_color_1")
        Table.Columns.Add(Item_Columns.SocketContent_1, "socket_content_1")
        Table.Columns.Add(Item_Columns.SocketColor_2, "socket_color_2")
        Table.Columns.Add(Item_Columns.SocketContent_2, "socket_content_2")
        Table.Columns.Add(Item_Columns.SocketColor_3, "socket_color_3")
        Table.Columns.Add(Item_Columns.SocketContent_3, "socket_content_3")
        Table.Columns.Add(Item_Columns.SocketBonus, "socket_bonus")
        Table.Columns.Add(Item_Columns.GemProperties, "GemProperties")
        Table.Columns.Add(Item_Columns.ReqDisenchantSkill, "ReqDisenchantSkill")
        Table.Columns.Add(Item_Columns.ArmorDamageModifier, "armorDamageModifier")
        Table.Columns.Add(Item_Columns.ExistingDuration, "ExistingDuration")
        Table.Columns.Add(Item_Columns.ItemLimitCategory, "ItemLimitCategory")
        Table.Columns.Add(Item_Columns.HolidayId, "HolidayId")
        Table.Columns.Add(Item_Columns.DisenchantID, "DisenchantID")
        Table.Columns.Add(Item_Columns.FoodType, "FoodType")
        Table.Columns.Add(Item_Columns.MinMoneyLoot, "minMoneyLoot")
        Table.Columns.Add(Item_Columns.MaxMoneyLoot, "maxMoneyLoot")
        Table.Columns.Add(Item_Columns.ExtraFlags, "ExtraFlags")

        'Loots
        Table = New TTable("loots", TableTypes.CreatureLoot)
        Tables.Add(Table)
        Table.Columns.Add(CreatureLoot_Columns.Entry, "loot_creature")
        Table.Columns.Add(CreatureLoot_Columns.Item, "loot_item")
        Table.Columns.Add(CreatureLoot_Columns.Chance, "loot_chance")
        Table.Columns.Add(CreatureLoot_Columns.HeroicChance, "loot_heroicchance")
        Table.Columns.Add(CreatureLoot_Columns.Min, "loot_min")
        Table.Columns.Add(CreatureLoot_Columns.Max, "loot_max")
        Table.Columns.Add(CreatureLoot_Columns.FFA, "loot_ffa")

        'Loots_Gameobject
        Table = New TTable("loots_gameobject", TableTypes.GameobjectLoot)
        Tables.Add(Table)
        Table.Columns.Add(GameobjectLoot_Columns.Entry, "loot_object")
        Table.Columns.Add(GameobjectLoot_Columns.Item, "loot_item")
        Table.Columns.Add(GameobjectLoot_Columns.Chance, "loot_chance")
        Table.Columns.Add(GameobjectLoot_Columns.HeroicChance, "loot_heroicchance")
        Table.Columns.Add(GameobjectLoot_Columns.Min, "loot_min")
        Table.Columns.Add(GameobjectLoot_Columns.Max, "loot_max")
        Table.Columns.Add(GameobjectLoot_Columns.FFA, "loot_ffa")

        'ItemLoot
        Table = New TTable("itemloot", TableTypes.LootsItem)
        Tables.Add(Table)
        Table.Columns.Add(ItemsLoot_Columns.Index, "index")
        Table.Columns.Add(ItemsLoot_Columns.Entry, "entryid")
        Table.Columns.Add(ItemsLoot_Columns.Item, "itemid")
        Table.Columns.Add(ItemsLoot_Columns.Chance, "percentchance")
        Table.Columns.Add(ItemsLoot_Columns.HeroicChance, "heroicpercentchance")
        Table.Columns.Add(ItemsLoot_Columns.Min, "mincount")
        Table.Columns.Add(ItemsLoot_Columns.Max, "maxcount")
        Table.Columns.Add(ItemsLoot_Columns.FFA, "ffa_loot")

        'Loots_Skinning
        Table = New TTable("loots_skinning", TableTypes.LootsSkinning)
        Tables.Add(Table)
        Table.Columns.Add(SkinningLoot_Columns.Entry, "loot_creature")
        Table.Columns.Add(SkinningLoot_Columns.Item, "loot_item")
        Table.Columns.Add(SkinningLoot_Columns.Chance, "loot_chance")
        Table.Columns.Add(SkinningLoot_Columns.HeroicChance, "loot_heroicchance")
        Table.Columns.Add(SkinningLoot_Columns.Min, "loot_min")
        Table.Columns.Add(SkinningLoot_Columns.Max, "loot_max")
        Table.Columns.Add(SkinningLoot_Columns.FFA, "loot_ffa")

        'Loots_Fishing
        Table = New TTable("loots_fishing", TableTypes.Lootsfishing)
        Tables.Add(Table)
        Table.Columns.Add(FishingLoot_Columns.Entry, "loot_entry")
        Table.Columns.Add(FishingLoot_Columns.Item, "loot_item")
        Table.Columns.Add(FishingLoot_Columns.Chance, "loot_chance")
        Table.Columns.Add(FishingLoot_Columns.HeroicChance, "loot_heroicchance")
        Table.Columns.Add(FishingLoot_Columns.Min, "loot_min")
        Table.Columns.Add(FishingLoot_Columns.Max, "loot_max")
        Table.Columns.Add(FishingLoot_Columns.FFA, "loot_ffa")

        'Loots_PickPocketing
        Table = New TTable("loots_pickpocketing", TableTypes.LootsPickPocketing)
        Tables.Add(Table)
        Table.Columns.Add(PickPocketingLoot_Columns.Entry, "loot_creature")
        Table.Columns.Add(PickPocketingLoot_Columns.Item, "loot_item")
        Table.Columns.Add(PickPocketingLoot_Columns.Chance, "loot_chance")
        Table.Columns.Add(PickPocketingLoot_Columns.HeroicChance, "loot_heroicchance")
        Table.Columns.Add(PickPocketingLoot_Columns.Min, "loot_min")
        Table.Columns.Add(PickPocketingLoot_Columns.Max, "loot_max")
        Table.Columns.Add(PickPocketingLoot_Columns.FFA, "loot_ffa")

        'Fishing
        Table = New TTable("fishing", TableTypes.Fishing)
        Tables.Add(Table)
        Table.Columns.Add(Fishing_Columns.Zone, "zone")
        Table.Columns.Add(Fishing_Columns.MinSkill, "MinSkill")
        Table.Columns.Add(Fishing_Columns.MaxSkill, "MaxSkill")

        'Quests
        Table = New TTable("quests", TableTypes.Quests)
        Tables.Add(Table)
        Table.Columns.Add(Quest_Columns.ID, "id")
        Table.Columns.Add(Quest_Columns.PrevQuest, "PrevQuest")
        Table.Columns.Add(Quest_Columns.NextQuest, "NextQuest")
        Table.Columns.Add(Quest_Columns.Title, "Title")
        Table.Columns.Add(Quest_Columns.Zone, "Zone")
        Table.Columns.Add(Quest_Columns.Type, "Type")
        Table.Columns.Add(Quest_Columns.Flags, "Flags")
        Table.Columns.Add(Quest_Columns.RewTitleId, "RewTitleId")
        Table.Columns.Add(Quest_Columns.RewardTalents, "rewtalents")
        Table.Columns.Add(Quest_Columns.SpecialFlags, "SpecialFlags")
        Table.Columns.Add(Quest_Columns.LevelStart, "Level_Start")
        Table.Columns.Add(Quest_Columns.LevelNormal, "Level_Normal")
        Table.Columns.Add(Quest_Columns.RequiredOneOfQuest, "Required_One_Of_Quest")
        Table.Columns.Add(Quest_Columns.RequiredQuest1, "Required_Quest1")
        Table.Columns.Add(Quest_Columns.RequiredQuest2, "Required_Quest2")
        Table.Columns.Add(Quest_Columns.RequiredQuest3, "Required_Quest3")
        Table.Columns.Add(Quest_Columns.RequiredQuest4, "Required_Quest4")
        Table.Columns.Add(Quest_Columns.RemoveQuests, "Remove_Quests")
        Table.Columns.Add(Quest_Columns.ReceiveItemId1, "Receive_ItemId1")
        Table.Columns.Add(Quest_Columns.ReceiveItem1Count, "Receive_ItemId1_Count")
        Table.Columns.Add(Quest_Columns.ReceiveItemId2, "Receive_ItemId2")
        Table.Columns.Add(Quest_Columns.ReceiveItem2Count, "Receive_ItemId2_Count")
        Table.Columns.Add(Quest_Columns.ReceiveItemId3, "Receive_ItemId3")
        Table.Columns.Add(Quest_Columns.ReceiveItem3Count, "Receive_ItemId3_Count")
        Table.Columns.Add(Quest_Columns.ReceiveItemId4, "Receive_ItemId4")
        Table.Columns.Add(Quest_Columns.ReceiveItem4Count, "Receive_ItemId4_Count")
        Table.Columns.Add(Quest_Columns.IsRepeatable, "IsRepeatable")
        Table.Columns.Add(Quest_Columns.BonusHonor, "BonusHonor")
        Table.Columns.Add(Quest_Columns.RequiredRace, "Required_Race")
        Table.Columns.Add(Quest_Columns.RequiredClass, "Required_Class")
        Table.Columns.Add(Quest_Columns.RequiredTradeSkill, "Required_TradeSkill")
        Table.Columns.Add(Quest_Columns.RequiredTradeSkillValue, "Required_TradeSkillValue")
        Table.Columns.Add(Quest_Columns.RequiredReputation1, "Required_Reputation1")
        Table.Columns.Add(Quest_Columns.RequiredReputation1Faction, "Required_Reputation1_Faction")
        Table.Columns.Add(Quest_Columns.RequiredReputation2, "Required_Reputation2")
        Table.Columns.Add(Quest_Columns.RequiredReputation2Faction, "Required_Reputation2_Faction")
        Table.Columns.Add(Quest_Columns.TextObjectives, "Text_Objectives")
        Table.Columns.Add(Quest_Columns.TextDescription, "Text_Description")
        Table.Columns.Add(Quest_Columns.TextEnd, "Text_End")
        Table.Columns.Add(Quest_Columns.TextIncomplete, "Text_Incomplete")
        Table.Columns.Add(Quest_Columns.TextComplete, "Text_Complete")
        Table.Columns.Add(Quest_Columns.RewardXP, "Reward_XP")
        Table.Columns.Add(Quest_Columns.RewardGold, "Reward_Gold")
        Table.Columns.Add(Quest_Columns.RewardSpell, "Reward_Spell")
        Table.Columns.Add(Quest_Columns.RewardSpellCast, "Reward_SpellCast")
        Table.Columns.Add(Quest_Columns.RewardReputation1, "Reward_Reputation1")
        Table.Columns.Add(Quest_Columns.RewardReputation1Faction, "Reward_Reputation1_Faction")
        Table.Columns.Add(Quest_Columns.RewardReputation2, "Reward_Reputation2")
        Table.Columns.Add(Quest_Columns.RewardReputation2Faction, "Reward_Reputation2_Faction")
        Table.Columns.Add(Quest_Columns.RewardReputation3, "Reward_Reputation3")
        Table.Columns.Add(Quest_Columns.RewardReputation3Faction, "Reward_Reputation3_Faction")
        Table.Columns.Add(Quest_Columns.RewardReputation4, "Reward_Reputation4")
        Table.Columns.Add(Quest_Columns.RewardReputation4Faction, "Reward_Reputation4_Faction")
        Table.Columns.Add(Quest_Columns.RewardReputation5, "Reward_Reputation5")
        Table.Columns.Add(Quest_Columns.RewardReputation5Faction, "Reward_Reputation5_Faction")
        Table.Columns.Add(Quest_Columns.RewardReputation6, "Reward_Reputation6")
        Table.Columns.Add(Quest_Columns.RewardReputation6Faction, "Reward_Reputation6_Faction")
        Table.Columns.Add(Quest_Columns.RewardItem1, "Reward_Item1")
        Table.Columns.Add(Quest_Columns.RewardItem1Count, "Reward_Item1_Count")
        Table.Columns.Add(Quest_Columns.RewardItem2, "Reward_Item2")
        Table.Columns.Add(Quest_Columns.RewardItem2Count, "Reward_Item2_Count")
        Table.Columns.Add(Quest_Columns.RewardItem3, "Reward_Item3")
        Table.Columns.Add(Quest_Columns.RewardItem3Count, "Reward_Item3_Count")
        Table.Columns.Add(Quest_Columns.RewardItem4, "Reward_Item4")
        Table.Columns.Add(Quest_Columns.RewardItem4Count, "Reward_Item4_Count")
        Table.Columns.Add(Quest_Columns.RewardItem5, "Reward_Item5")
        Table.Columns.Add(Quest_Columns.RewardItem5Count, "Reward_Item5_Count")
        Table.Columns.Add(Quest_Columns.RewardItem6, "Reward_Item6")
        Table.Columns.Add(Quest_Columns.RewardItem6Count, "Reward_Item6_Count")
        Table.Columns.Add(Quest_Columns.RewardStaticItem1, "Reward_StaticItem1")
        Table.Columns.Add(Quest_Columns.RewardStaticItem1Count, "Reward_StaticItem1_Count")
        Table.Columns.Add(Quest_Columns.RewardStaticItem2, "Reward_StaticItem2")
        Table.Columns.Add(Quest_Columns.RewardStaticItem2Count, "Reward_StaticItem2_Count")
        Table.Columns.Add(Quest_Columns.RewardStaticItem3, "Reward_StaticItem3")
        Table.Columns.Add(Quest_Columns.RewardStaticItem3Count, "Reward_StaticItem3_Count")
        Table.Columns.Add(Quest_Columns.RewardStaticItem4, "Reward_StaticItem4")
        Table.Columns.Add(Quest_Columns.RewardStaticItem4Count, "Reward_StaticItem4_Count")
        Table.Columns.Add(Quest_Columns.TimeLimit, "Time_Limit")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger1, "Objective_Trigger1")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger2, "Objective_Trigger2")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger3, "Objective_Trigger3")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger4, "Objective_Trigger4")
        Table.Columns.Add(Quest_Columns.ObjectiveCast1, "Objective_Cast1")
        Table.Columns.Add(Quest_Columns.ObjectiveCast2, "Objective_Cast2")
        Table.Columns.Add(Quest_Columns.ObjectiveCast3, "Objective_Cast3")
        Table.Columns.Add(Quest_Columns.ObjectiveCast4, "Objective_Cast4")
        Table.Columns.Add(Quest_Columns.RequiredEmoteId1, "Requested_EmoteId1")
        Table.Columns.Add(Quest_Columns.RequiredEmoteId2, "Requested_EmoteId2")
        Table.Columns.Add(Quest_Columns.RequiredEmoteId3, "Requested_EmoteId3")
        Table.Columns.Add(Quest_Columns.RequiredEmoteId4, "Requested_EmoteId4")
        Table.Columns.Add(Quest_Columns.DetailEmotecount, "Detail_Emote_Count")
        Table.Columns.Add(Quest_Columns.DetailEmote1, "Detail_Emote1")
        Table.Columns.Add(Quest_Columns.DetailEmote2, "Detail_Emote2")
        Table.Columns.Add(Quest_Columns.DetailEmote3, "Detail_Emote3")
        Table.Columns.Add(Quest_Columns.DetailEmote4, "Detail_Emote4")
        Table.Columns.Add(Quest_Columns.DetailEmoteDelay1, "Detail_Emote1_Delay")
        Table.Columns.Add(Quest_Columns.DetailEmoteDelay2, "Detail_Emote2_Delay")
        Table.Columns.Add(Quest_Columns.DetailEmoteDelay3, "Detail_Emote3_Delay")
        Table.Columns.Add(Quest_Columns.DetailEmoteDelay4, "Detail_Emote4_Delay")
        Table.Columns.Add(Quest_Columns.CompletionEmoteCount, "Completion_Emote_Count")
        Table.Columns.Add(Quest_Columns.CompletionEmote1, "Completion_Emote1")
        Table.Columns.Add(Quest_Columns.CompletionEmote2, "Completion_Emote2")
        Table.Columns.Add(Quest_Columns.CompletionEmote3, "Completion_Emote3")
        Table.Columns.Add(Quest_Columns.CompletionEmote4, "Completion_Emote4")
        Table.Columns.Add(Quest_Columns.CompletionEmoteDelay1, "Completion_Emote1_Delay")
        Table.Columns.Add(Quest_Columns.CompletionEmoteDelay2, "Completion_Emote2_Delay")
        Table.Columns.Add(Quest_Columns.CompletionEmoteDelay3, "Completion_Emote3_Delay")
        Table.Columns.Add(Quest_Columns.CompletionEmoteDelay4, "Completion_Emote4_Delay")
        Table.Columns.Add(Quest_Columns.CompleteEmote, "Complete_Emote")
        Table.Columns.Add(Quest_Columns.InCompleteEmote, "Incomplete_Emote")
        Table.Columns.Add(Quest_Columns.ObjectiveKill1, "Objective_Kill1")
        Table.Columns.Add(Quest_Columns.ObjectiveKill1Count, "Objective_Kill1_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveKill2, "Objective_Kill2")
        Table.Columns.Add(Quest_Columns.ObjectiveKill2Count, "Objective_Kill2_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveKill3, "Objective_Kill3")
        Table.Columns.Add(Quest_Columns.ObjectiveKill3Count, "Objective_Kill3_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveKill4, "Objective_Kill4")
        Table.Columns.Add(Quest_Columns.ObjectiveKill4Count, "Objective_Kill4_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveItem1, "Objective_Item1")
        Table.Columns.Add(Quest_Columns.ObjectiveItem1Count, "Objective_Item1_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveItem2, "Objective_Item2")
        Table.Columns.Add(Quest_Columns.ObjectiveItem2Count, "Objective_Item2_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveItem3, "Objective_Item3")
        Table.Columns.Add(Quest_Columns.ObjectiveItem3Count, "Objective_Item3_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveItem4, "Objective_Item4")
        Table.Columns.Add(Quest_Columns.ObjectiveItem4Count, "Objective_Item4_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveItem5, "Objective_Item5")
        Table.Columns.Add(Quest_Columns.ObjectiveItem5Count, "Objective_Item5_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveItem6, "Objective_Item6")
        Table.Columns.Add(Quest_Columns.ObjectiveItem6Count, "Objective_Item6_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveDeliver1, "Objective_Deliver1")
        Table.Columns.Add(Quest_Columns.ObjectiveDeliver1Count, "Objective_Deliver1_Count")
        Table.Columns.Add(Quest_Columns.ObjectiveText1, "Objective_Text1")
        Table.Columns.Add(Quest_Columns.ObjectiveText2, "Objective_Text2")
        Table.Columns.Add(Quest_Columns.ObjectiveText3, "Objective_Text3")
        Table.Columns.Add(Quest_Columns.ObjectiveText4, "Objective_Text4")
        Table.Columns.Add(Quest_Columns.SuggestedPlayers, "SuggestedPlayers")
        Table.Columns.Add(Quest_Columns.PointMap, "PointMap")
        Table.Columns.Add(Quest_Columns.PointX, "PointX")
        Table.Columns.Add(Quest_Columns.PointY, "PointY")
        Table.Columns.Add(Quest_Columns.PointOpt, "PointOpt")
        Table.Columns.Add(Quest_Columns.MoneyAtMaxLevel, "MoneyAtMaxLevel")
        Table.Columns.Add(Quest_Columns.isCompletedBySpellEffect, "IsCompleted_By_Spell_Effect")
        Table.Columns.Add(Quest_Columns.IsActive, "IsActive")

        'Battleground_Battlemaster
        Table = New TTable("battleground_battlemaster", TableTypes.BattleGround_BattleMaster)
        Tables.Add(Table)
        Table.Columns.Add(BattleGround_Columns.Entry, "entry")
        Table.Columns.Add(BattleGround_Columns.Battleground_Entry, "battleground_entry")

        'Queststarters
        Table = New TTable("queststarters", TableTypes.QuestStartersCreature)
        Tables.Add(Table)
        Table.Columns.Add(QuestStarter_Columns.Type, "type")
        Table.Columns.Add(QuestStarter_Columns.TypeID, "typeid")
        Table.Columns.Add(QuestStarter_Columns.QuestID, "questid")

        'QuestStarters
        Table = New TTable("queststarters", TableTypes.QuestStartersGameobject)
        Tables.Add(Table)
        Table.Columns.Add(QuestStarter_Columns.Type, "type")
        Table.Columns.Add(QuestStarter_Columns.TypeID, "typeid")
        Table.Columns.Add(QuestStarter_Columns.QuestID, "questid")

        'QuestFinishers
        Table = New TTable("questfinishers", TableTypes.QuestFinishersCreature)
        Tables.Add(Table)
        Table.Columns.Add(QuestFinisher_Columns.Type, "type")
        Table.Columns.Add(QuestFinisher_Columns.TypeID, "typeid")
        Table.Columns.Add(QuestFinisher_Columns.QuestID, "questid")

        'Questfinishers
        Table = New TTable("questfinishers", TableTypes.QuestFinishersGameobject)
        Tables.Add(Table)
        Table.Columns.Add(QuestFinisher_Columns.Type, "type")
        Table.Columns.Add(QuestFinisher_Columns.TypeID, "typeid")
        Table.Columns.Add(QuestFinisher_Columns.QuestID, "questid")

        'Spells_Teleport_Coords
        Table = New TTable("spells_teleport_coords", TableTypes.SpellTeleportCoords)
        Tables.Add(Table)
        Table.Columns.Add(SpellTeleportCoords_Columns.ID, "id")
        Table.Columns.Add(SpellTeleportCoords_Columns.Name, "name")
        Table.Columns.Add(SpellTeleportCoords_Columns.Map, "mapId")
        Table.Columns.Add(SpellTeleportCoords_Columns.PosX, "position_x")
        Table.Columns.Add(SpellTeleportCoords_Columns.PosY, "position_y")
        Table.Columns.Add(SpellTeleportCoords_Columns.PosZ, "position_z")
        Table.Columns.Add(SpellTeleportCoords_Columns.ToTrigger, "totrigger")

        'Gameobject_Quest_Association
        Table = New TTable("gameobject_quest_association", TableTypes.GameObjectQuestAssociation)
        Tables.Add(Table)
        Table.Columns.Add(GameObjectQuestAssociation_Columns.Entry, "entry")
        Table.Columns.Add(GameObjectQuestAssociation_Columns.Quest, "quest")
        Table.Columns.Add(GameObjectQuestAssociation_Columns.Item, "item")
        Table.Columns.Add(GameObjectQuestAssociation_Columns.ItemCount, "item_count")

        'NpcText
        Table = New TTable("npctext", TableTypes.NpcText)
        Tables.Add(Table)
        Table.Columns.Add(NpcText_Columns.Entry, "entry")
        Table.Columns.Add(NpcText_Columns.Prob0, "prob0")
        Table.Columns.Add(NpcText_Columns.Text0_0, "text0_0")
        Table.Columns.Add(NpcText_Columns.Text0_1, "text0_1")
        Table.Columns.Add(NpcText_Columns.Lang0, "lang0")
        Table.Columns.Add(NpcText_Columns.em0_0, "em0_0")
        Table.Columns.Add(NpcText_Columns.em0_1, "em0_1")
        Table.Columns.Add(NpcText_Columns.em0_2, "em0_2")
        Table.Columns.Add(NpcText_Columns.em0_3, "em0_3")
        Table.Columns.Add(NpcText_Columns.em0_4, "em0_4")
        Table.Columns.Add(NpcText_Columns.em0_5, "em0_5")
        Table.Columns.Add(NpcText_Columns.Prob1, "prob1")
        Table.Columns.Add(NpcText_Columns.Text1_0, "text1_0")
        Table.Columns.Add(NpcText_Columns.Text1_1, "text1_1")
        Table.Columns.Add(NpcText_Columns.Lang1, "lang1")
        Table.Columns.Add(NpcText_Columns.em1_0, "em1_0")
        Table.Columns.Add(NpcText_Columns.em1_1, "em1_1")
        Table.Columns.Add(NpcText_Columns.em1_2, "em1_2")
        Table.Columns.Add(NpcText_Columns.em1_3, "em1_3")
        Table.Columns.Add(NpcText_Columns.em1_4, "em1_4")
        Table.Columns.Add(NpcText_Columns.em1_5, "em1_5")
        Table.Columns.Add(NpcText_Columns.Prob2, "prob2")
        Table.Columns.Add(NpcText_Columns.Text2_0, "text2_0")
        Table.Columns.Add(NpcText_Columns.Text2_1, "text2_1")
        Table.Columns.Add(NpcText_Columns.Lang2, "lang2")
        Table.Columns.Add(NpcText_Columns.em2_0, "em2_0")
        Table.Columns.Add(NpcText_Columns.em2_1, "em2_1")
        Table.Columns.Add(NpcText_Columns.em2_2, "em2_2")
        Table.Columns.Add(NpcText_Columns.em2_3, "em2_3")
        Table.Columns.Add(NpcText_Columns.em2_4, "em2_4")
        Table.Columns.Add(NpcText_Columns.em2_5, "em2_5")
        Table.Columns.Add(NpcText_Columns.Prob3, "prob3")
        Table.Columns.Add(NpcText_Columns.Text3_0, "text3_0")
        Table.Columns.Add(NpcText_Columns.Text3_1, "text3_1")
        Table.Columns.Add(NpcText_Columns.Lang3, "lang3")
        Table.Columns.Add(NpcText_Columns.em3_0, "em3_0")
        Table.Columns.Add(NpcText_Columns.em3_1, "em3_1")
        Table.Columns.Add(NpcText_Columns.em3_2, "em3_2")
        Table.Columns.Add(NpcText_Columns.em3_3, "em3_3")
        Table.Columns.Add(NpcText_Columns.em3_4, "em3_4")
        Table.Columns.Add(NpcText_Columns.em3_5, "em3_5")
        Table.Columns.Add(NpcText_Columns.Prob4, "prob4")
        Table.Columns.Add(NpcText_Columns.Text4_0, "text4_0")
        Table.Columns.Add(NpcText_Columns.Text4_1, "text4_1")
        Table.Columns.Add(NpcText_Columns.Lang4, "lang4")
        Table.Columns.Add(NpcText_Columns.em4_0, "em4_0")
        Table.Columns.Add(NpcText_Columns.em4_1, "em4_1")
        Table.Columns.Add(NpcText_Columns.em4_2, "em4_2")
        Table.Columns.Add(NpcText_Columns.em4_3, "em4_3")
        Table.Columns.Add(NpcText_Columns.em4_4, "em4_4")
        Table.Columns.Add(NpcText_Columns.em4_5, "em4_5")
        Table.Columns.Add(NpcText_Columns.Prob5, "prob5")
        Table.Columns.Add(NpcText_Columns.Text5_0, "text5_0")
        Table.Columns.Add(NpcText_Columns.Text5_1, "text5_1")
        Table.Columns.Add(NpcText_Columns.Lang5, "lang5")
        Table.Columns.Add(NpcText_Columns.em5_0, "em5_0")
        Table.Columns.Add(NpcText_Columns.em5_1, "em5_1")
        Table.Columns.Add(NpcText_Columns.em5_2, "em5_2")
        Table.Columns.Add(NpcText_Columns.em5_3, "em5_3")
        Table.Columns.Add(NpcText_Columns.em5_4, "em5_4")
        Table.Columns.Add(NpcText_Columns.em5_5, "em5_5")
        Table.Columns.Add(NpcText_Columns.Prob6, "prob6")
        Table.Columns.Add(NpcText_Columns.Text6_0, "text6_0")
        Table.Columns.Add(NpcText_Columns.Text6_1, "text6_1")
        Table.Columns.Add(NpcText_Columns.Lang6, "lang6")
        Table.Columns.Add(NpcText_Columns.em6_0, "em6_0")
        Table.Columns.Add(NpcText_Columns.em6_1, "em6_1")
        Table.Columns.Add(NpcText_Columns.em6_2, "em6_2")
        Table.Columns.Add(NpcText_Columns.em6_3, "em6_3")
        Table.Columns.Add(NpcText_Columns.em6_4, "em6_4")
        Table.Columns.Add(NpcText_Columns.em6_5, "em6_5")
        Table.Columns.Add(NpcText_Columns.Prob7, "prob7")
        Table.Columns.Add(NpcText_Columns.Text7_0, "text7_0")
        Table.Columns.Add(NpcText_Columns.Text7_1, "text7_1")
        Table.Columns.Add(NpcText_Columns.Lang7, "lang7")
        Table.Columns.Add(NpcText_Columns.em7_0, "em7_0")
        Table.Columns.Add(NpcText_Columns.em7_1, "em7_1")
        Table.Columns.Add(NpcText_Columns.em7_2, "em7_2")
        Table.Columns.Add(NpcText_Columns.em7_3, "em7_3")
        Table.Columns.Add(NpcText_Columns.em7_4, "em7_4")
        Table.Columns.Add(NpcText_Columns.em7_5, "em7_5")

        'Npc_Vendor
        Table = New TTable("npc_vendor", TableTypes.NpcVendor)
        Tables.Add(Table)
        Table.Columns.Add(NpcVendor_Columns.Entry, "entry")
        Table.Columns.Add(NpcVendor_Columns.Item, "item")
        Table.Columns.Add(NpcVendor_Columns.Amount, "sellamount")
        Table.Columns.Add(NpcVendor_Columns.Stock, "maxcount")
        Table.Columns.Add(NpcVendor_Columns.Refill, "incrtime")
        Table.Columns.Add(NpcVendor_Columns.ExtendedCost, "extendedcost")

        'Npc_Gossip_TextID
        Table = New TTable("npc_gossip_textid", TableTypes.NpcGossipTextID)
        Tables.Add(Table)
        Table.Columns.Add(NpcGossipTextID_Columns.Entry, "creatureid")
        Table.Columns.Add(NpcGossipTextID_Columns.TextID, "textid")

        'Trainer_Defs
        Table = New TTable("trainer_defs", TableTypes.NpcTrainerDefs)
        Tables.Add(Table)
        Table.Columns.Add(NpcTrainerDef_Columns.Entry, "entry")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqSkill, "required_skill")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqSkillValue, "required_skillvalue")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqRace, "")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqClass, "req_class")
        Table.Columns.Add(NpcTrainerDef_Columns.TrainerType, "trainer_type")
        Table.Columns.Add(NpcTrainerDef_Columns.WindowMessage, "trainer_ui_window_message")
        Table.Columns.Add(NpcTrainerDef_Columns.CanTrainMessage, "can_train_gossip_textid")
        Table.Columns.Add(NpcTrainerDef_Columns.CanNotTrainMessage, "cannot_train_gossip_textid")

        'Items_RandomProp_Groups
        Table = New TTable("item_randomprop_groups", TableTypes.ItemRandomPropGroups)
        Tables.Add(Table)
        Table.Columns.Add(ItemRandom_Props_Columns.ItemEntry, "entry_id")
        Table.Columns.Add(ItemRandom_Props_Columns.RandomPropsEntryID, "randomprops_entryid")
        Table.Columns.Add(ItemRandom_Props_Columns.Chance, "chance")

        'Items_RandomSuffix_Groups
        Table = New TTable("item_randomsuffix_groups", TableTypes.ItemSuffixGroups)
        Tables.Add(Table)
        Table.Columns.Add(ItemRandom_Suffix_Columns.ItemEntry, "entry_id")
        Table.Columns.Add(ItemRandom_Suffix_Columns.RandomSuffixEntryID, "randomsuffix_entryid")
        Table.Columns.Add(ItemRandom_Suffix_Columns.Chance, "chance")

        'ItemPages
        Table = New TTable("itempages", TableTypes.ItemPages)
        Tables.Add(Table)
        Table.Columns.Add(ItemPages_Columns.ItemEntry, "entry")
        Table.Columns.Add(ItemPages_Columns.Text, "text")
        Table.Columns.Add(ItemPages_Columns.NextPage, "next_page")

        'Items_FoodType
        Table = New TTable("itempetfood", TableTypes.ItemPetFood)
        Tables.Add(Table)
        Table.Columns.Add(PetFood_Columns.ItemEntry, "entry")
        Table.Columns.Add(PetFood_Columns.FoodType, "food_type")

        'PlayerCreateInfo
        Table = New TTable("playercreateinfo", TableTypes.PlayerCreateInfo)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfo_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfo_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseStrength, "BaseStrength")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseAgility, "BaseAgility")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseStamina, "BaseStamina")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseIntellect, "BaseIntellect")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseSpirit, "BaseSpirit")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseHealth, "BaseHealth")

        'PlayerCreateInfo_Bars
        Table = New TTable("playercreateinfo_bars", TableTypes.PlayerCreateInfo_Bars)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Button, "button")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Action, "action")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Type, "type")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Misc, "misc")

        'PlayerCreateInfo_Items
        Table = New TTable("playercreateinfo_items", TableTypes.PlayerCreateInfo_Items)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoItem_Columns.IndexID, "indexid")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.ProtoID, "protoid")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.SlotID, "slotid")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.Amount, "amount")

        'PlayerCreateInfo_Skills
        Table = New TTable("playercreateinfo_skills", TableTypes.PlayerCreateInfo_Skills)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.IndexID, "indexid")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.SkillID, "skillid")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.Level, "level")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.MaxLevel, "maxlevel")

        'PlayerCreateInfo_Spells
        Table = New TTable("playercreateinfo_spells", TableTypes.PlayerCreateInfo_Spells)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoSpell_Columns.IndexID, "indexid")
        Table.Columns.Add(PlayerCreateInfoSpell_Columns.SpellID, "spellid")

        'Npc_MonsterSay
        Table = New TTable("npc_monstersay", TableTypes.MonsterSay)
        Tables.Add(Table)
        Table.Columns.Add(MonsterSay_Columns.Entry, "entry")
        Table.Columns.Add(MonsterSay_Columns.Evente, "event")
        Table.Columns.Add(MonsterSay_Columns.Chance, "chance")
        Table.Columns.Add(MonsterSay_Columns.Language, "language")
        Table.Columns.Add(MonsterSay_Columns.Type, "type")
        Table.Columns.Add(MonsterSay_Columns.MonsterName, "monstername")
        Table.Columns.Add(MonsterSay_Columns.Text0, "text0")
        Table.Columns.Add(MonsterSay_Columns.Text1, "text1")
        Table.Columns.Add(MonsterSay_Columns.Text2, "text2")
        Table.Columns.Add(MonsterSay_Columns.Text3, "text3")
        Table.Columns.Add(MonsterSay_Columns.Text4, "text4")

        'World_CmdTeleports
        Table = New TTable("world_cmdteleports", TableTypes.CmdTeleports)
        Tables.Add(Table)
        Table.Columns.Add(CmdTeleports_Columns.Id, "id")
        Table.Columns.Add(CmdTeleports_Columns.Name, "name")
        Table.Columns.Add(CmdTeleports_Columns.MapID, "MapId")
        Table.Columns.Add(CmdTeleports_Columns.PositionX, "positionX")
        Table.Columns.Add(CmdTeleports_Columns.PositionY, "positionY")
        Table.Columns.Add(CmdTeleports_Columns.PositionZ, "positionZ")

        'Creatures_Movement
        Table = New TTable("creature_movement", TableTypes.creature_movement)
        Tables.Add(Table)
        Table.Columns.Add(Creature_Movement_Columns.spawnid, "spawnid")
        Table.Columns.Add(Creature_Movement_Columns.waypointid, "waypointid")
        Table.Columns.Add(Creature_Movement_Columns.position_x, "position_x")
        Table.Columns.Add(Creature_Movement_Columns.position_y, "position_y")
        Table.Columns.Add(Creature_Movement_Columns.position_z, "position_z")
        Table.Columns.Add(Creature_Movement_Columns.waittime, "waittime")
        Table.Columns.Add(Creature_Movement_Columns.flags, "flags")
        Table.Columns.Add(Creature_Movement_Columns.emote, "emote")
        Table.Columns.Add(Creature_Movement_Columns.orientation, "orientation")
    End Sub
End Class
