Public Class WhyDB
    Inherits WhyDBBaseDB

    Public Sub New()
        InitTables()
    End Sub

    Public Sub InitTables()
        'Creature_Names
        Dim Table As TTable
        Table = New TTable("creature_names", TableTypes.CreatureInfo)
        Tables.Add(Table)
        Table.Columns.Add(CreatureInfo_Columns.Entry, "entry")
        Table.Columns.Add(CreatureInfo_Columns.Name, "name")
        Table.Columns.Add(CreatureInfo_Columns.SubName, "subname")
        Table.Columns.Add(CreatureInfo_Columns.InfoStr, "info_str")
        Table.Columns.Add(CreatureInfo_Columns.Flags, "flags1")
        Table.Columns.Add(CreatureInfo_Columns.Type, "type")
        'Table.Columns.Add(CreatureInfo_Columns.SpellDataID, "0")
        Table.Columns.Add(CreatureInfo_Columns.Family, "family")
        Table.Columns.Add(CreatureInfo_Columns.Rank, "rank")
        Table.Columns.Add(CreatureInfo_Columns.KillCredit1, "killcredit1")
        Table.Columns.Add(CreatureInfo_Columns.KillCredit2, "killcredit2")
        Table.Columns.Add(CreatureInfo_Columns.MaleDisplayID, "male_displayid")
        Table.Columns.Add(CreatureInfo_Columns.FemaleDisplayID, "female_displayid")
        Table.Columns.Add(CreatureInfo_Columns.MaleDisplayID2, "male_displayid2")
        Table.Columns.Add(CreatureInfo_Columns.FemaleDisplayID2, "female_displayid2")
        Table.Columns.Add(CreatureInfo_Columns.UnknownFloat1, "unknown_float1")
        Table.Columns.Add(CreatureInfo_Columns.UnknownFloat2, "unknown_float2")
        Table.Columns.Add(CreatureInfo_Columns.Leader, "leader")
        Table.Columns.Add(CreatureInfo_Columns.QuestItem1, "questitem1")
        Table.Columns.Add(CreatureInfo_Columns.QuestItem2, "questitem2")
        Table.Columns.Add(CreatureInfo_Columns.QuestItem3, "questitem3")
        Table.Columns.Add(CreatureInfo_Columns.QuestItem4, "questitem4")
        Table.Columns.Add(CreatureInfo_Columns.QuestItem5, "questitem5")
        Table.Columns.Add(CreatureInfo_Columns.QuestItem6, "questitem6")

        'Creature_Proto
        Table = New TTable("creature_proto", TableTypes.CreatureInfo)
        Tables.Add(Table)
        Table.Columns.Add(CreatureInfo_Columns.Entry, "entry")
        Table.Columns.Add(CreatureInfo_Columns.MinLevel, "minlevel")
        Table.Columns.Add(CreatureInfo_Columns.MaxLevel, "maxlevel")
        Table.Columns.Add(CreatureInfo_Columns.Faction, "faction")
        Table.Columns.Add(CreatureInfo_Columns.MinLife, "minhealth")
        Table.Columns.Add(CreatureInfo_Columns.MaxLife, "maxhealth")
        Table.Columns.Add(CreatureInfo_Columns.MinMana, "mana")
        Table.Columns.Add(CreatureInfo_Columns.MaxMana, "mana")
        Table.Columns.Add(CreatureInfo_Columns.Size, "scale")
        'Table.Columns.Add(CreatureInfo_Columns.ManaType, "0")
        Table.Columns.Add(CreatureInfo_Columns.NpcFlags, "npcflags")
        Table.Columns.Add(CreatureInfo_Columns.BaseAttackSpeed, "attacktime")
        Table.Columns.Add(CreatureInfo_Columns.MinDamage, "mindamage")
        Table.Columns.Add(CreatureInfo_Columns.MaxDamage, "maxdamage")
        Table.Columns.Add(CreatureInfo_Columns.BaseRangedAttackSpeed, "rangedattacktime")
        Table.Columns.Add(CreatureInfo_Columns.MinRangedDamage, "rangedmindamage")
        Table.Columns.Add(CreatureInfo_Columns.MaxRangedDamage, "rangedmaxdamage")
        Table.Columns.Add(CreatureInfo_Columns.RespawnTime, "respawntime")
        Table.Columns.Add(CreatureInfo_Columns.Armor, "armor")
        Table.Columns.Add(CreatureInfo_Columns.ResHoly, "resistance1")
        Table.Columns.Add(CreatureInfo_Columns.ResFire, "resistance2")
        Table.Columns.Add(CreatureInfo_Columns.ResNature, "resistance3")
        Table.Columns.Add(CreatureInfo_Columns.ResFrost, "resistance4")
        Table.Columns.Add(CreatureInfo_Columns.ResShadow, "resistance5")
        Table.Columns.Add(CreatureInfo_Columns.ResArcane, "resistance6")
        Table.Columns.Add(CreatureInfo_Columns.CombatReach, "combat_reach")
        Table.Columns.Add(CreatureInfo_Columns.BondingRadius, "bounding_radius")
        Table.Columns.Add(CreatureInfo_Columns.Boss, "boss")
        Table.Columns.Add(CreatureInfo_Columns.MinGold, "money")
        Table.Columns.Add(CreatureInfo_Columns.MaxGold, "money")
        Table.Columns.Add(CreatureInfo_Columns.WalkSpeed, "walk_speed")
        Table.Columns.Add(CreatureInfo_Columns.RunSpeed, "run_speed")
        Table.Columns.Add(CreatureInfo_Columns.FlySpeed, "fly_speed")
        Table.Columns.Add(CreatureInfo_Columns.ExtraA9Flags, "extra_a9_flags")
        Table.Columns.Add(CreatureInfo_Columns.ModImmunities, "modImmunities")
        'Table.Columns.Add(CreatureInfo_Columns.Loot, "0")
        'Table.Columns.Add(CreatureInfo_Columns.SkinLoot, "0")
        'Table.Columns.Add(CreatureInfo_Columns.PickpocketLoot, "0")
        'Table.Columns.Add(CreatureInfo_Columns.EquipmentEntry, "0")
        'Table.Columns.Add(CreatureInfo_Columns.EquipModel1, "0")
        'Table.Columns.Add(CreatureInfo_Columns.EquipModel2, "0")
        'Table.Columns.Add(CreatureInfo_Columns.EquipModel3, "0")
        'Table.Columns.Add(CreatureInfo_Columns.EquipInfo1, "0")
        'Table.Columns.Add(CreatureInfo_Columns.EquipInfo2, "0")
        'Table.Columns.Add(CreatureInfo_Columns.EquipInfo3, "0")
        'Table.Columns.Add(CreatureInfo_Columns.EquipSlot1, "0")
        'Table.Columns.Add(CreatureInfo_Columns.EquipSlot2, "0")
        'Table.Columns.Add(CreatureInfo_Columns.EquipSlot3, "0")
        'Table.Columns.Add(CreatureInfo_Columns.AiScript, "")
        'Table.Columns.Add(CreatureInfo_Columns.TrainerType, "0")
        'Table.Columns.Add(CreatureInfo_Columns.TrainerSpell, "0")
        'Table.Columns.Add(CreatureInfo_Columns.TrainerClass, "0")
        'Table.Columns.Add(CreatureInfo_Columns.TrainerRace, "0")
        'Table.Columns.Add(CreatureInfo_Columns.MovementType, "0")
        'Table.Columns.Add(CreatureInfo_Columns.RegenHealth, "0")

        'Creature_Spawns
        Table = New TTable("creature_spawns", TableTypes.CreatureSpawn)
        Tables.Add(Table)
        Table.Columns.Add(CreatureSpawn_Columns.ID, "id")
        Table.Columns.Add(CreatureSpawn_Columns.Entry, "entry")
        Table.Columns.Add(CreatureSpawn_Columns.Map, "map")
        Table.Columns.Add(CreatureSpawn_Columns.PositionX, "position_x")
        Table.Columns.Add(CreatureSpawn_Columns.PositionY, "position_y")
        Table.Columns.Add(CreatureSpawn_Columns.PositionZ, "position_z")
        Table.Columns.Add(CreatureSpawn_Columns.Orientation, "orientation")
        'Table.Columns.Add(CreatureSpawn_Columns.Range, "")
        Table.Columns.Add(CreatureSpawn_Columns.MoveType, "movetype")
        Table.Columns.Add(CreatureSpawn_Columns.Model, "displayid")
        Table.Columns.Add(CreatureSpawn_Columns.Faction, "faction")
        Table.Columns.Add(CreatureSpawn_Columns.Flags, "flags")
        Table.Columns.Add(CreatureSpawn_Columns.Bytes0, "bytes0")
        Table.Columns.Add(CreatureSpawn_Columns.Bytes1, "bytes1")
        Table.Columns.Add(CreatureSpawn_Columns.Bytes2, "bytes2")
        Table.Columns.Add(CreatureSpawn_Columns.EmoteState, "emote_state")
        Table.Columns.Add(CreatureSpawn_Columns.StandState, "standstate")
        Table.Columns.Add(CreatureSpawn_Columns.Mount, "mountdisplayid")
        Table.Columns.Add(CreatureSpawn_Columns.equipslot1, "slot1item")
        Table.Columns.Add(CreatureSpawn_Columns.equipslot2, "slot2item")
        Table.Columns.Add(CreatureSpawn_Columns.equipslot3, "slot3item")
        Table.Columns.Add(CreatureSpawn_Columns.CanFly, "CanFly")

        'Gameobject_Names
        Table = New TTable("gameobject_names", TableTypes.GameobjectInfo)
        Tables.Add(Table)
        Table.Columns.Add(GameobjectInfo_Columns.Entry, "entry")
        Table.Columns.Add(GameobjectInfo_Columns.Type, "Type")
        Table.Columns.Add(GameobjectInfo_Columns.Model, "DisplayID")
        Table.Columns.Add(GameobjectInfo_Columns.Name, "Name")
        Table.Columns.Add(GameobjectInfo_Columns.Category, "Category")
        Table.Columns.Add(GameobjectInfo_Columns.CastBarCaption, "CastBarText")
        'Table.Columns.Add(GameobjectInfo_Columns.RespawnTime, "0")
        Table.Columns.Add(GameobjectInfo_Columns.Field0, "sound1")
        Table.Columns.Add(GameobjectInfo_Columns.Field1, "sound2")
        Table.Columns.Add(GameobjectInfo_Columns.Field2, "sound3")
        Table.Columns.Add(GameobjectInfo_Columns.Field3, "sound4")
        Table.Columns.Add(GameobjectInfo_Columns.Field4, "sound5")
        Table.Columns.Add(GameobjectInfo_Columns.Field5, "sound6")
        Table.Columns.Add(GameobjectInfo_Columns.Field6, "sound7")
        Table.Columns.Add(GameobjectInfo_Columns.Field7, "sound8")
        Table.Columns.Add(GameobjectInfo_Columns.Field8, "sound9")
        Table.Columns.Add(GameobjectInfo_Columns.Field9, "unknown1")
        Table.Columns.Add(GameobjectInfo_Columns.Field10, "unknown2")
        Table.Columns.Add(GameobjectInfo_Columns.Field11, "unknown3")
        Table.Columns.Add(GameobjectInfo_Columns.Field12, "unknown4")
        Table.Columns.Add(GameobjectInfo_Columns.Field13, "unknown5")
        Table.Columns.Add(GameobjectInfo_Columns.Field14, "unknown6")
        Table.Columns.Add(GameobjectInfo_Columns.Field15, "unknown7")
        Table.Columns.Add(GameobjectInfo_Columns.Field16, "unknown8")
        Table.Columns.Add(GameobjectInfo_Columns.Field17, "unknown9")
        Table.Columns.Add(GameobjectInfo_Columns.Field18, "unknown10")
        Table.Columns.Add(GameobjectInfo_Columns.Field19, "unknown11")
        Table.Columns.Add(GameobjectInfo_Columns.Field20, "unknown12")
        Table.Columns.Add(GameobjectInfo_Columns.Field21, "unknown13")
        Table.Columns.Add(GameobjectInfo_Columns.Field22, "unknown14")
        'Table.Columns.Add(GameobjectInfo_Columns.Field23, "unknown15")
        Table.Columns.Add(GameobjectInfo_Columns.Scale, "Size")
        Table.Columns.Add(GameobjectInfo_Columns.QuestItem1, "QuestItem1")
        Table.Columns.Add(GameobjectInfo_Columns.QuestItem2, "QuestItem2")
        Table.Columns.Add(GameobjectInfo_Columns.QuestItem3, "QuestItem3")
        Table.Columns.Add(GameobjectInfo_Columns.QuestItem4, "QuestItem4")
        Table.Columns.Add(GameobjectInfo_Columns.QuestItem5, "QuestItem5")
        Table.Columns.Add(GameobjectInfo_Columns.QuestItem6, "QuestItem6")

        'Gameobject_Spawns
        Table = New TTable("gameobject_spawns", TableTypes.GameobjectSpawn)
        Tables.Add(Table)
        Table.Columns.Add(GameobjectSpawn_Columns.ID, "id")
        Table.Columns.Add(GameobjectSpawn_Columns.Entry, "Entry")
        Table.Columns.Add(GameobjectSpawn_Columns.Map, "map")
        Table.Columns.Add(GameobjectSpawn_Columns.PositionX, "position_x")
        Table.Columns.Add(GameobjectSpawn_Columns.PositionY, "position_y")
        Table.Columns.Add(GameobjectSpawn_Columns.PositionZ, "position_z")
        Table.Columns.Add(GameobjectSpawn_Columns.Orientation, "Facing")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation1, "orientation1")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation2, "orientation2")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation3, "orientation3")
        Table.Columns.Add(GameobjectSpawn_Columns.Rotation4, "orientation4")
        Table.Columns.Add(GameobjectSpawn_Columns.State, "State")
        Table.Columns.Add(GameobjectSpawn_Columns.Flags, "Flags")
        Table.Columns.Add(GameobjectSpawn_Columns.Faction, "Faction")
        Table.Columns.Add(GameobjectSpawn_Columns.Scale, "Scale")

        'Items
        Table = New TTable("items", TableTypes.Items)
        Tables.Add(Table)
        Table.Columns.Add(Item_Columns.Entry, "entry")
        Table.Columns.Add(Item_Columns.Classe, "class")
        Table.Columns.Add(Item_Columns.SubClass, "subclass")
        Table.Columns.Add(Item_Columns.Field4, "field4")
        Table.Columns.Add(Item_Columns.Name1, "name1")
        'Table.Columns.Add(Item_Columns.Name2, "")
        'Table.Columns.Add(Item_Columns.Name3, "")
        'Table.Columns.Add(Item_Columns.Name4, "")
        Table.Columns.Add(Item_Columns.DisplayID, "displayid")
        Table.Columns.Add(Item_Columns.Quality, "quality")
        Table.Columns.Add(Item_Columns.Flags, "flags")
        Table.Columns.Add(Item_Columns.Faction, "faction")
        'Table.Columns.Add(Item_Columns.BuyCount, "0")
        Table.Columns.Add(Item_Columns.Buyprice, "buyprice")
        Table.Columns.Add(Item_Columns.Sellprice, "sellprice")
        Table.Columns.Add(Item_Columns.InventoryType, "inventorytype")
        Table.Columns.Add(Item_Columns.AllowableClass, "allowableclass")
        Table.Columns.Add(Item_Columns.AllowableRace, "allowablerace")
        Table.Columns.Add(Item_Columns.ItemLevel, "itemlevel")
        Table.Columns.Add(Item_Columns.RequiredLevel, "requiredlevel")
        Table.Columns.Add(Item_Columns.RequiredSkill, "RequiredSkill")
        Table.Columns.Add(Item_Columns.RequiredSkillRank, "RequiredSkillRank")
        'Table.Columns.Add(Item_Columns.RequiredSubRank, "0")
        Table.Columns.Add(Item_Columns.RequiredSpell, "RequiredSpell")
        Table.Columns.Add(Item_Columns.RequiredPlayerRank1, "RequiredPlayerRank1")
        Table.Columns.Add(Item_Columns.RequiredPlayerRank2, "RequiredPlayerRank2")
        Table.Columns.Add(Item_Columns.RequiredFaction, "RequiredFaction")
        Table.Columns.Add(Item_Columns.RequiredFactionStanding, "RequiredFactionStanding")
        Table.Columns.Add(Item_Columns.Unique, "Unique")
        Table.Columns.Add(Item_Columns.MaxCount, "maxcount")
        Table.Columns.Add(Item_Columns.ContainerSlots, "ContainerSlots")
        Table.Columns.Add(Item_Columns.StatsCount, "itemstatscount")
        Table.Columns.Add(Item_Columns.Stat_Type1, "stat_type1")
        Table.Columns.Add(Item_Columns.Stat_Value1, "stat_value1")
        Table.Columns.Add(Item_Columns.Stat_Type2, "stat_type2")
        Table.Columns.Add(Item_Columns.Stat_Value2, "stat_value2")
        Table.Columns.Add(Item_Columns.Stat_Type3, "stat_type3")
        Table.Columns.Add(Item_Columns.Stat_Value3, "stat_value3")
        Table.Columns.Add(Item_Columns.Stat_Type4, "stat_type4")
        Table.Columns.Add(Item_Columns.Stat_Value4, "stat_value4")
        Table.Columns.Add(Item_Columns.Stat_Type5, "stat_type5")
        Table.Columns.Add(Item_Columns.Stat_Value5, "stat_value5")
        Table.Columns.Add(Item_Columns.Stat_Type6, "stat_type6")
        Table.Columns.Add(Item_Columns.Stat_Value6, "stat_value6")
        Table.Columns.Add(Item_Columns.Stat_Type7, "stat_type7")
        Table.Columns.Add(Item_Columns.Stat_Value7, "stat_value7")
        Table.Columns.Add(Item_Columns.Stat_Type8, "stat_type8")
        Table.Columns.Add(Item_Columns.Stat_Value8, "stat_value8")
        Table.Columns.Add(Item_Columns.Stat_Type9, "stat_type9")
        Table.Columns.Add(Item_Columns.Stat_Value9, "stat_value9")
        Table.Columns.Add(Item_Columns.Stat_Type10, "stat_type10")
        Table.Columns.Add(Item_Columns.Stat_Value10, "stat_value10")
        Table.Columns.Add(Item_Columns.ScaledStatsDistributionID, "ScaledStatsDistributionId")
        Table.Columns.Add(Item_Columns.ScaledStatsDistributionFlags, "ScaledStatsDistributionFlags")
        Table.Columns.Add(Item_Columns.Dmg_Min1, "dmg_min1")
        Table.Columns.Add(Item_Columns.Dmg_Max1, "dmg_max1")
        Table.Columns.Add(Item_Columns.Dmg_Type1, "dmg_type1")
        Table.Columns.Add(Item_Columns.Dmg_Min2, "dmg_min2")
        Table.Columns.Add(Item_Columns.Dmg_Max2, "dmg_max2")
        Table.Columns.Add(Item_Columns.Dmg_Type2, "dmg_type2")
        'Table.Columns.Add(Item_Columns.Dmg_Min3, "0")
        'Table.Columns.Add(Item_Columns.Dmg_Max3, "0")
        'Table.Columns.Add(Item_Columns.Dmg_Type3, "0")
        'Table.Columns.Add(Item_Columns.Dmg_Min4, "0")
        'Table.Columns.Add(Item_Columns.Dmg_Max4, "0")
        'Table.Columns.Add(Item_Columns.Dmg_Type4, "0")
        'Table.Columns.Add(Item_Columns.Dmg_Min5, "0")
        'Table.Columns.Add(Item_Columns.Dmg_Max5, "0")
        'Table.Columns.Add(Item_Columns.Dmg_Type5, "0")
        Table.Columns.Add(Item_Columns.Armor, "armor")
        Table.Columns.Add(Item_Columns.HolyRes, "holy_res")
        Table.Columns.Add(Item_Columns.FireRes, "fire_res")
        Table.Columns.Add(Item_Columns.NatureRes, "nature_res")
        Table.Columns.Add(Item_Columns.FrostRes, "frost_res")
        Table.Columns.Add(Item_Columns.ShadowRes, "shadow_res")
        Table.Columns.Add(Item_Columns.ArcaneRes, "arcane_res")
        Table.Columns.Add(Item_Columns.Delay, "delay")
        Table.Columns.Add(Item_Columns.AmmoType, "ammo_type")
        Table.Columns.Add(Item_Columns.Range, "range")
        Table.Columns.Add(Item_Columns.SpellID_1, "spellid_1")
        Table.Columns.Add(Item_Columns.SpellTrigger_1, "spelltrigger_1")
        Table.Columns.Add(Item_Columns.SpellCharges_1, "spellcharges_1")
        Table.Columns.Add(Item_Columns.SpellCooldown_1, "spellcooldown_1")
        Table.Columns.Add(Item_Columns.SpellCategory_1, "spellcategory_1")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_1, "spellcategorycooldown_1")
        Table.Columns.Add(Item_Columns.SpellID_2, "spellid_2")
        Table.Columns.Add(Item_Columns.SpellTrigger_2, "spelltrigger_2")
        Table.Columns.Add(Item_Columns.SpellCharges_2, "spellcharges_2")
        Table.Columns.Add(Item_Columns.SpellCooldown_2, "spellcooldown_2")
        Table.Columns.Add(Item_Columns.SpellCategory_2, "spellcategory_2")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_2, "spellcategorycooldown_2")
        Table.Columns.Add(Item_Columns.SpellID_3, "spellid_3")
        Table.Columns.Add(Item_Columns.SpellTrigger_3, "spelltrigger_3")
        Table.Columns.Add(Item_Columns.SpellCharges_3, "spellcharges_3")
        Table.Columns.Add(Item_Columns.SpellCooldown_3, "spellcooldown_3")
        Table.Columns.Add(Item_Columns.SpellCategory_3, "spellcategory_3")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_3, "spellcategorycooldown_3")
        Table.Columns.Add(Item_Columns.SpellID_4, "spellid_4")
        Table.Columns.Add(Item_Columns.SpellTrigger_4, "spelltrigger_4")
        Table.Columns.Add(Item_Columns.SpellCharges_4, "spellcharges_4")
        Table.Columns.Add(Item_Columns.SpellCooldown_4, "spellcooldown_4")
        Table.Columns.Add(Item_Columns.SpellCategory_4, "spellcategory_4")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_4, "spellcategorycooldown_4")
        Table.Columns.Add(Item_Columns.SpellID_5, "spellid_5")
        Table.Columns.Add(Item_Columns.SpellTrigger_5, "spelltrigger_5")
        Table.Columns.Add(Item_Columns.SpellCharges_5, "spellcharges_5")
        Table.Columns.Add(Item_Columns.SpellCooldown_5, "spellcooldown_5")
        Table.Columns.Add(Item_Columns.SpellCategory_5, "spellcategory_5")
        Table.Columns.Add(Item_Columns.SpellCategoryCooldown_5, "spellcategorycooldown_5")
        Table.Columns.Add(Item_Columns.Bonding, "bonding")
        Table.Columns.Add(Item_Columns.Description, "description")
        Table.Columns.Add(Item_Columns.PageID, "page_id")
        Table.Columns.Add(Item_Columns.PageLanguage, "page_language")
        Table.Columns.Add(Item_Columns.PageMaterial, "page_material")
        Table.Columns.Add(Item_Columns.QuestID, "quest_id")
        Table.Columns.Add(Item_Columns.LockID, "lock_id")
        Table.Columns.Add(Item_Columns.LockMaterial, "lock_material")
        Table.Columns.Add(Item_Columns.SheathID, "sheathID")
        Table.Columns.Add(Item_Columns.RandomProp, "randomprop")
        Table.Columns.Add(Item_Columns.RandomSuffix, "randomsuffix")
        Table.Columns.Add(Item_Columns.Block, "block")
        Table.Columns.Add(Item_Columns.ItemSet, "itemset")
        Table.Columns.Add(Item_Columns.MaxDurability, "MaxDurability")
        Table.Columns.Add(Item_Columns.ZoneNameID, "ZoneNameID")
        Table.Columns.Add(Item_Columns.MapID, "mapid")
        Table.Columns.Add(Item_Columns.BagFamily, "bagfamily")
        Table.Columns.Add(Item_Columns.TotemCategory, "TotemCategory")
        Table.Columns.Add(Item_Columns.SocketColor_1, "socket_color_1")
        Table.Columns.Add(Item_Columns.SocketContent_1, "unk201_3")
        Table.Columns.Add(Item_Columns.SocketColor_2, "socket_color_2")
        Table.Columns.Add(Item_Columns.SocketContent_2, "unk201_5")
        Table.Columns.Add(Item_Columns.SocketColor_3, "socket_color_3")
        Table.Columns.Add(Item_Columns.SocketContent_3, "unk201_7")
        Table.Columns.Add(Item_Columns.SocketBonus, "socket_bonus")
        Table.Columns.Add(Item_Columns.GemProperties, "GemProperties")
        Table.Columns.Add(Item_Columns.ReqDisenchantSkill, "ReqDisenchantSkill")
        Table.Columns.Add(Item_Columns.ArmorDamageModifier, "armorDamageModifier")
        Table.Columns.Add(Item_Columns.ExistingDuration, "ExistingDuration")
        Table.Columns.Add(Item_Columns.ItemLimitCategory, "ItemLimitCategoryId")
        Table.Columns.Add(Item_Columns.HolidayId, "HolidayId")
        'Table.Columns.Add(Item_Columns.DisenchantID, "0")
        'Table.Columns.Add(Item_Columns.FoodType, "0")
        'Table.Columns.Add(Item_Columns.MinMoneyLoot, "0")
        'Table.Columns.Add(Item_Columns.MaxMoneyLoot, "0")
        'Table.Columns.Add(Item_Columns.ExtraFlags, "0")

        'Loot_Creatures
        Table = New TTable("loot_creatures", TableTypes.CreatureLoot)
        Tables.Add(Table)
        Table.Columns.Add(CreatureLoot_Columns.Index, "index")
        Table.Columns.Add(CreatureLoot_Columns.Entry, "entryid")
        Table.Columns.Add(CreatureLoot_Columns.Item, "itemid")
        Table.Columns.Add(CreatureLoot_Columns.Chance, "normal10percentchance")
        Table.Columns.Add(CreatureLoot_Columns.HeroicChance, "heroic10percentchance")
        Table.Columns.Add(CreatureLoot_Columns.Min, "mincount")
        Table.Columns.Add(CreatureLoot_Columns.Max, "maxcount")
        Table.Columns.Add(CreatureLoot_Columns.FFA, "ffa_loot")

        'Loot_Gameobjects
        Table = New TTable("loot_gameobjects", TableTypes.GameobjectLoot)
        Tables.Add(Table)
        Table.Columns.Add(GameobjectLoot_Columns.Index, "index")
        Table.Columns.Add(GameobjectLoot_Columns.Entry, "entryid")
        Table.Columns.Add(GameobjectLoot_Columns.Item, "itemid")
        Table.Columns.Add(GameobjectLoot_Columns.Chance, "normal10percentchance")
        Table.Columns.Add(GameobjectLoot_Columns.HeroicChance, "heroic10percentchance")
        Table.Columns.Add(GameobjectLoot_Columns.Min, "mincount")
        Table.Columns.Add(GameobjectLoot_Columns.Max, "maxcount")
        Table.Columns.Add(GameobjectLoot_Columns.FFA, "ffa_loot")

        'Loot_Items
        Table = New TTable("loot_items", TableTypes.LootsItem)
        Tables.Add(Table)
        Table.Columns.Add(ItemsLoot_Columns.Index, "index")
        Table.Columns.Add(ItemsLoot_Columns.Entry, "entryid")
        Table.Columns.Add(ItemsLoot_Columns.Item, "itemid")
        Table.Columns.Add(ItemsLoot_Columns.Chance, "normal10percentchance")
        Table.Columns.Add(ItemsLoot_Columns.HeroicChance, "heroic10percentchance")
        Table.Columns.Add(ItemsLoot_Columns.Min, "mincount")
        Table.Columns.Add(ItemsLoot_Columns.Max, "maxcount")
        Table.Columns.Add(ItemsLoot_Columns.FFA, "ffa_loot")

        'Loot_Skinning
        Table = New TTable("loot_skinning", TableTypes.LootsSkinning)
        Tables.Add(Table)
        Table.Columns.Add(SkinningLoot_Columns.Index, "index")
        Table.Columns.Add(SkinningLoot_Columns.Entry, "entryid")
        Table.Columns.Add(SkinningLoot_Columns.Item, "itemid")
        Table.Columns.Add(SkinningLoot_Columns.Chance, "normal10percentchance")
        Table.Columns.Add(SkinningLoot_Columns.HeroicChance, "heroic10percentchance")
        Table.Columns.Add(SkinningLoot_Columns.Min, "mincount")
        Table.Columns.Add(SkinningLoot_Columns.Max, "maxcount")
        Table.Columns.Add(SkinningLoot_Columns.FFA, "ffa_loot")

        'Loot_Fishing
        Table = New TTable("loot_fishing", TableTypes.LootsFishing)
        Tables.Add(Table)
        Table.Columns.Add(FishingLoot_Columns.Index, "index")
        Table.Columns.Add(FishingLoot_Columns.Entry, "entryid")
        Table.Columns.Add(FishingLoot_Columns.Item, "itemid")
        Table.Columns.Add(FishingLoot_Columns.Chance, "normal10percentchance")
        Table.Columns.Add(FishingLoot_Columns.HeroicChance, "heroic10percentchance")
        Table.Columns.Add(FishingLoot_Columns.Min, "mincount")
        Table.Columns.Add(FishingLoot_Columns.Max, "maxcount")
        Table.Columns.Add(FishingLoot_Columns.FFA, "ffa_loot")

        'Fishing
        Table = New TTable("fishing", TableTypes.Fishing)
        Tables.Add(Table)
        Table.Columns.Add(Fishing_Columns.Zone, "zone")
        Table.Columns.Add(Fishing_Columns.MinSkill, "MinSkill")
        Table.Columns.Add(Fishing_Columns.MaxSkill, "MaxSkill")

        'Loot_PickPocketing
        Table = New TTable("loot_pickpocketing", TableTypes.LootsPickPocketing)
        Tables.Add(Table)
        Table.Columns.Add(PickPocketingLoot_Columns.Index, "index")
        Table.Columns.Add(PickPocketingLoot_Columns.Entry, "entryid")
        Table.Columns.Add(PickPocketingLoot_Columns.Item, "itemid")
        Table.Columns.Add(PickPocketingLoot_Columns.Chance, "normal10percentchance")
        Table.Columns.Add(PickPocketingLoot_Columns.HeroicChance, "heroic10percentchance")
        Table.Columns.Add(PickPocketingLoot_Columns.Min, "mincount")
        Table.Columns.Add(PickPocketingLoot_Columns.Max, "maxcount")
        Table.Columns.Add(PickPocketingLoot_Columns.FFA, "ffa_loot")

        'Quests
        Table = New TTable("quests", TableTypes.Quests)
        Tables.Add(Table)
        Table.Columns.Add(Quest_Columns.ID, "entry")
        Table.Columns.Add(Quest_Columns.Zone, "ZoneId")
        Table.Columns.Add(Quest_Columns.Flags, "flags")
        Table.Columns.Add(Quest_Columns.LevelStart, "MinLevel")
        Table.Columns.Add(Quest_Columns.LevelNormal, "questlevel")
        Table.Columns.Add(Quest_Columns.Type, "Type")
        Table.Columns.Add(Quest_Columns.RequiredRace, "RequiredRaces")
        Table.Columns.Add(Quest_Columns.RequiredClass, "RequiredClass")
        Table.Columns.Add(Quest_Columns.RequiredTradeSkill, "RequiredTradeSkill")
        Table.Columns.Add(Quest_Columns.RequiredTradeSkillValue, "RequiredTradeSkillValue")
        Table.Columns.Add(Quest_Columns.RequiredReputation1Faction, "RequiredRepFaction")
        Table.Columns.Add(Quest_Columns.RequiredReputation1, "RequiredRepValue")
        'Table.Columns.Add(Quest_Columns.RequiredReputation2Faction, "0")
        'Table.Columns.Add(Quest_Columns.RequiredReputation2, "0")
        Table.Columns.Add(Quest_Columns.TimeLimit, "LimitTime")
        Table.Columns.Add(Quest_Columns.SpecialFlags, "SpecialFlags")
        Table.Columns.Add(Quest_Columns.PrevQuest, "PrevQuestId")
        Table.Columns.Add(Quest_Columns.NextQuest, "NextQuestId")
        Table.Columns.Add(Quest_Columns.ObjectiveDeliver1, "srcItem")
        Table.Columns.Add(Quest_Columns.ObjectiveDeliver1Count, "SrcItemCount")
        Table.Columns.Add(Quest_Columns.Title, "Title")
        Table.Columns.Add(Quest_Columns.TextDescription, "Details")
        Table.Columns.Add(Quest_Columns.TextObjectives, "Objectives")
        Table.Columns.Add(Quest_Columns.TextComplete, "CompletionText")
        Table.Columns.Add(Quest_Columns.TextIncomplete, "IncompleteText")
        Table.Columns.Add(Quest_Columns.TextEnd, "EndText")
        Table.Columns.Add(Quest_Columns.ObjectiveText1, "ObjectiveText1")
        Table.Columns.Add(Quest_Columns.ObjectiveText2, "ObjectiveText2")
        Table.Columns.Add(Quest_Columns.ObjectiveText3, "ObjectiveText3")
        Table.Columns.Add(Quest_Columns.ObjectiveText4, "ObjectiveText4")
        Table.Columns.Add(Quest_Columns.ObjectiveItem1, "ReqItemId1")
        Table.Columns.Add(Quest_Columns.ObjectiveItem2, "ReqItemId2")
        Table.Columns.Add(Quest_Columns.ObjectiveItem3, "ReqItemId3")
        Table.Columns.Add(Quest_Columns.ObjectiveItem4, "ReqItemId4")
        Table.Columns.Add(Quest_Columns.ObjectiveItem5, "ReqItemId5")
        Table.Columns.Add(Quest_Columns.ObjectiveItem6, "ReqItemId6")
        Table.Columns.Add(Quest_Columns.ObjectiveItem1Count, "ReqItemCount1")
        Table.Columns.Add(Quest_Columns.ObjectiveItem2Count, "ReqItemCount2")
        Table.Columns.Add(Quest_Columns.ObjectiveItem3Count, "ReqItemCount3")
        Table.Columns.Add(Quest_Columns.ObjectiveItem4Count, "ReqItemCount4")
        Table.Columns.Add(Quest_Columns.ObjectiveItem5Count, "ReqItemCount5")
        Table.Columns.Add(Quest_Columns.ObjectiveItem6Count, "ReqItemCount6")
        Table.Columns.Add(Quest_Columns.ObjectiveKill1, "ReqKillMobOrGOId1")
        Table.Columns.Add(Quest_Columns.ObjectiveKill2, "ReqKillMobOrGOId2")
        Table.Columns.Add(Quest_Columns.ObjectiveKill3, "ReqKillMobOrGOId3")
        Table.Columns.Add(Quest_Columns.ObjectiveKill4, "ReqKillMobOrGOId4")
        Table.Columns.Add(Quest_Columns.ObjectiveKill1Count, "ReqKillMobOrGOCount1")
        Table.Columns.Add(Quest_Columns.ObjectiveKill2Count, "ReqKillMobOrGOCount2")
        Table.Columns.Add(Quest_Columns.ObjectiveKill3Count, "ReqKillMobOrGOCount3")
        Table.Columns.Add(Quest_Columns.ObjectiveKill4Count, "ReqKillMobOrGOCount4")
        Table.Columns.Add(Quest_Columns.ObjectiveCast1, "ReqCastSpellId1")
        Table.Columns.Add(Quest_Columns.ObjectiveCast2, "ReqCastSpellId2")
        Table.Columns.Add(Quest_Columns.ObjectiveCast3, "ReqCastSpellId3")
        Table.Columns.Add(Quest_Columns.ObjectiveCast4, "ReqCastSpellId4")
        Table.Columns.Add(Quest_Columns.RequiredEmoteId1, "ReqEmoteId1")
        Table.Columns.Add(Quest_Columns.RequiredEmoteId2, "ReqEmoteId2")
        Table.Columns.Add(Quest_Columns.RequiredEmoteId3, "ReqEmoteId3")
        Table.Columns.Add(Quest_Columns.RequiredEmoteId4, "ReqEmoteId4")
        Table.Columns.Add(Quest_Columns.RewardItem1, "RewChoiceItemId1")
        Table.Columns.Add(Quest_Columns.RewardItem2, "RewChoiceItemId2")
        Table.Columns.Add(Quest_Columns.RewardItem3, "RewChoiceItemId3")
        Table.Columns.Add(Quest_Columns.RewardItem4, "RewChoiceItemId4")
        Table.Columns.Add(Quest_Columns.RewardItem5, "RewChoiceItemId5")
        Table.Columns.Add(Quest_Columns.RewardItem6, "RewChoiceItemId6")
        Table.Columns.Add(Quest_Columns.RewardItem1Count, "RewChoiceItemCount1")
        Table.Columns.Add(Quest_Columns.RewardItem2Count, "RewChoiceItemCount2")
        Table.Columns.Add(Quest_Columns.RewardItem3Count, "RewChoiceItemCount3")
        Table.Columns.Add(Quest_Columns.RewardItem4Count, "RewChoiceItemCount4")
        Table.Columns.Add(Quest_Columns.RewardItem5Count, "RewChoiceItemCount5")
        Table.Columns.Add(Quest_Columns.RewardItem6Count, "RewChoiceItemCount6")
        Table.Columns.Add(Quest_Columns.RewardStaticItem1, "RewItemId1")
        Table.Columns.Add(Quest_Columns.RewardStaticItem2, "RewItemId2")
        Table.Columns.Add(Quest_Columns.RewardStaticItem3, "RewItemId3")
        Table.Columns.Add(Quest_Columns.RewardStaticItem4, "RewItemId4")
        Table.Columns.Add(Quest_Columns.RewardStaticItem1Count, "RewItemCount1")
        Table.Columns.Add(Quest_Columns.RewardStaticItem2Count, "RewItemCount2")
        Table.Columns.Add(Quest_Columns.RewardStaticItem3Count, "RewItemCount3")
        Table.Columns.Add(Quest_Columns.RewardStaticItem4Count, "RewItemCount4")
        Table.Columns.Add(Quest_Columns.RewardReputation1Faction, "RewRepFaction1")
        Table.Columns.Add(Quest_Columns.RewardReputation2Faction, "RewRepFaction2")
        Table.Columns.Add(Quest_Columns.RewardReputation3Faction, "RewRepFaction3")
        Table.Columns.Add(Quest_Columns.RewardReputation4Faction, "RewRepFaction4")
        Table.Columns.Add(Quest_Columns.RewardReputation5Faction, "RewRepFaction5")
        Table.Columns.Add(Quest_Columns.RewardReputation6Faction, "RewRepFaction6")
        Table.Columns.Add(Quest_Columns.RewardReputation1, "RewRepValue1")
        Table.Columns.Add(Quest_Columns.RewardReputation2, "RewRepValue2")
        Table.Columns.Add(Quest_Columns.RewardReputation3, "RewRepValue3")
        Table.Columns.Add(Quest_Columns.RewardReputation4, "RewRepValue4")
        Table.Columns.Add(Quest_Columns.RewardReputation5, "RewRepValue5")
        Table.Columns.Add(Quest_Columns.RewardReputation6, "RewRepValue6")
        Table.Columns.Add(Quest_Columns.RewardRepLimit, "RewRepLimit")
        Table.Columns.Add(Quest_Columns.RewardGold, "RewMoney")
        Table.Columns.Add(Quest_Columns.RewardXP, "RewXP")
        Table.Columns.Add(Quest_Columns.RewardSpell, "RewSpell")
        Table.Columns.Add(Quest_Columns.RewardSpellCast, "CastSpell")
        Table.Columns.Add(Quest_Columns.PointMap, "PointMapId")
        Table.Columns.Add(Quest_Columns.PointX, "PointX")
        Table.Columns.Add(Quest_Columns.PointY, "PointY")
        Table.Columns.Add(Quest_Columns.PointOpt, "PointOpt")
        Table.Columns.Add(Quest_Columns.MoneyAtMaxLevel, "RewardMoneyAtMaxLevel")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger1, "ExploreTrigger1")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger2, "ExploreTrigger2")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger3, "ExploreTrigger3")
        Table.Columns.Add(Quest_Columns.ObjectiveTrigger4, "ExploreTrigger4")
        Table.Columns.Add(Quest_Columns.RequiredOneOfQuest, "RequiredOneOfQuest")
        Table.Columns.Add(Quest_Columns.RequiredQuest1, "RequiredQuest1")
        Table.Columns.Add(Quest_Columns.RequiredQuest2, "RequiredQuest2")
        Table.Columns.Add(Quest_Columns.RequiredQuest3, "RequiredQuest3")
        Table.Columns.Add(Quest_Columns.RequiredQuest4, "RequiredQuest4")
        Table.Columns.Add(Quest_Columns.RemoveQuests, "RemoveQuests")
        Table.Columns.Add(Quest_Columns.ReceiveItemId1, "ReceiveItemId1")
        Table.Columns.Add(Quest_Columns.ReceiveItemId2, "ReceiveItemId2")
        Table.Columns.Add(Quest_Columns.ReceiveItemId3, "ReceiveItemId3")
        Table.Columns.Add(Quest_Columns.ReceiveItemId4, "ReceiveItemId4")
        Table.Columns.Add(Quest_Columns.ReceiveItem1Count, "ReceiveItemCount1")
        Table.Columns.Add(Quest_Columns.ReceiveItem2Count, "ReceiveItemCount2")
        Table.Columns.Add(Quest_Columns.ReceiveItem3Count, "ReceiveItemCount3")
        Table.Columns.Add(Quest_Columns.ReceiveItem4Count, "ReceiveItemCount4")
        Table.Columns.Add(Quest_Columns.IsRepeatable, "IsRepeatable")
        Table.Columns.Add(Quest_Columns.BonusHonor, "bonushonor")
        Table.Columns.Add(Quest_Columns.RewTitleId, "rewardtitleid")
        Table.Columns.Add(Quest_Columns.RewardTalents, "rewardtalents")
        Table.Columns.Add(Quest_Columns.SuggestedPlayers, "suggestedplayers")
        Table.Columns.Add(Quest_Columns.DetailEmotecount, "detailemotecount")
        Table.Columns.Add(Quest_Columns.DetailEmote1, "detailemote1")
        Table.Columns.Add(Quest_Columns.DetailEmote2, "detailemote2")
        Table.Columns.Add(Quest_Columns.DetailEmote3, "detailemote3")
        Table.Columns.Add(Quest_Columns.DetailEmote4, "detailemote4")
        Table.Columns.Add(Quest_Columns.DetailEmoteDelay1, "detailemotedelay1")
        Table.Columns.Add(Quest_Columns.DetailEmoteDelay2, "detailemotedelay2")
        Table.Columns.Add(Quest_Columns.DetailEmoteDelay3, "detailemotedelay3")
        Table.Columns.Add(Quest_Columns.DetailEmoteDelay4, "detailemotedelay4")
        Table.Columns.Add(Quest_Columns.CompletionEmoteCount, "completionemotecnt")
        Table.Columns.Add(Quest_Columns.CompletionEmote1, "completionemote1")
        Table.Columns.Add(Quest_Columns.CompletionEmote2, "completionemote2")
        Table.Columns.Add(Quest_Columns.CompletionEmote3, "completionemote3")
        Table.Columns.Add(Quest_Columns.CompletionEmote4, "completionemote4")
        Table.Columns.Add(Quest_Columns.CompletionEmoteDelay1, "completionemotedelay1")
        Table.Columns.Add(Quest_Columns.CompletionEmoteDelay2, "completionemotedelay2")
        Table.Columns.Add(Quest_Columns.CompletionEmoteDelay3, "completionemotedelay3")
        Table.Columns.Add(Quest_Columns.CompletionEmoteDelay4, "completionemotedelay4")
        Table.Columns.Add(Quest_Columns.CompleteEmote, "completeemote")
        Table.Columns.Add(Quest_Columns.InCompleteEmote, "incompleteemote")
        Table.Columns.Add(Quest_Columns.isCompletedBySpellEffect, "iscompletedbyspelleffect")
        'Table.Columns.Add(Quest_Columns.IsActive, "2")

        'Battlemasters
        Table = New TTable("battlemasters", TableTypes.BattleGround_BattleMaster)
        Tables.Add(Table)
        Table.Columns.Add(BattleGround_Columns.Entry, "creature_entry")
        Table.Columns.Add(BattleGround_Columns.Battleground_Entry, "battleground_id")

        'Creature_Quest_Starter
        Table = New TTable("creature_quest_starter", TableTypes.QuestStartersCreature)
        Tables.Add(Table)
        Table.Columns.Add(QuestStarter_Columns.Type, "-1") 'hardcoded to value 1 (creature)
        Table.Columns.Add(QuestStarter_Columns.TypeID, "id")
        Table.Columns.Add(QuestStarter_Columns.QuestID, "quest")

        'Gameobject_Quest_Starter
        Table = New TTable("gameobject_quest_starter", TableTypes.QuestStartersGameobject)
        Tables.Add(Table)
        Table.Columns.Add(QuestStarter_Columns.Type, "-2") 'hardcoded to value 2 (gameobject)
        Table.Columns.Add(QuestStarter_Columns.TypeID, "id")
        Table.Columns.Add(QuestStarter_Columns.QuestID, "quest")

        'Creature_Quest_Finisher
        Table = New TTable("creature_quest_finisher", TableTypes.QuestFinishersCreature)
        Tables.Add(Table)
        Table.Columns.Add(QuestFinisher_Columns.Type, "-1") 'hardcoded to value 1 (creature)
        Table.Columns.Add(QuestFinisher_Columns.TypeID, "id")
        Table.Columns.Add(QuestFinisher_Columns.QuestID, "quest")

        'Quests_Gameobject_Quest_Finsher
        Table = New TTable("gameobject_quest_finisher", TableTypes.QuestFinishersGameobject)
        Tables.Add(Table)
        Table.Columns.Add(QuestFinisher_Columns.Type, "-2") 'hardcoded to value 2 (gameobject)
        Table.Columns.Add(QuestFinisher_Columns.TypeID, "id")
        Table.Columns.Add(QuestFinisher_Columns.QuestID, "quest")

        'Teleport_Coords
        Table = New TTable("teleport_coords", TableTypes.SpellTeleportCoords)
        Tables.Add(Table)
        Table.Columns.Add(SpellTeleportCoords_Columns.ID, "id")
        Table.Columns.Add(SpellTeleportCoords_Columns.Name, "name")
        Table.Columns.Add(SpellTeleportCoords_Columns.Map, "mapId")
        Table.Columns.Add(SpellTeleportCoords_Columns.PosX, "position_x")
        Table.Columns.Add(SpellTeleportCoords_Columns.PosY, "position_y")
        Table.Columns.Add(SpellTeleportCoords_Columns.PosZ, "position_z")
        'Table.Columns.Add(SpellTeleportCoords_Columns.orientation, "0")
        Table.Columns.Add(SpellTeleportCoords_Columns.ToTrigger, "totrigger")

        'Gameobject_Quest_Item_Binding
        Table = New TTable("gameobject_quest_item_binding", TableTypes.GameObjectQuestAssociation)
        Tables.Add(Table)
        Table.Columns.Add(GameObjectQuestAssociation_Columns.Entry, "entry")
        Table.Columns.Add(GameObjectQuestAssociation_Columns.Quest, "quest")
        Table.Columns.Add(GameObjectQuestAssociation_Columns.Item, "item")
        Table.Columns.Add(GameObjectQuestAssociation_Columns.ItemCount, "item_count")

        'Npc_Text
        Table = New TTable("npc_text", TableTypes.NpcText)
        Tables.Add(Table)
        Table.Columns.Add(NpcText_Columns.Entry, "entry")
        Table.Columns.Add(NpcText_Columns.Prob0, "prob0")
        Table.Columns.Add(NpcText_Columns.Text0_0, "text0_0")
        Table.Columns.Add(NpcText_Columns.Text0_1, "text0_1")
        Table.Columns.Add(NpcText_Columns.Lang0, "lang0")
        Table.Columns.Add(NpcText_Columns.em0_0, "em0_0")
        Table.Columns.Add(NpcText_Columns.em0_1, "em0_1")
        Table.Columns.Add(NpcText_Columns.em0_2, "em0_2")
        Table.Columns.Add(NpcText_Columns.em0_3, "em0_3")
        Table.Columns.Add(NpcText_Columns.em0_4, "em0_4")
        Table.Columns.Add(NpcText_Columns.em0_5, "em0_5")
        Table.Columns.Add(NpcText_Columns.Prob1, "prob1")
        Table.Columns.Add(NpcText_Columns.Text1_0, "text1_0")
        Table.Columns.Add(NpcText_Columns.Text1_1, "text1_1")
        Table.Columns.Add(NpcText_Columns.Lang1, "lang1")
        Table.Columns.Add(NpcText_Columns.em1_0, "em1_0")
        Table.Columns.Add(NpcText_Columns.em1_1, "em1_1")
        Table.Columns.Add(NpcText_Columns.em1_2, "em1_2")
        Table.Columns.Add(NpcText_Columns.em1_3, "em1_3")
        Table.Columns.Add(NpcText_Columns.em1_4, "em1_4")
        Table.Columns.Add(NpcText_Columns.em1_5, "em1_5")
        Table.Columns.Add(NpcText_Columns.Prob2, "prob2")
        Table.Columns.Add(NpcText_Columns.Text2_0, "text2_0")
        Table.Columns.Add(NpcText_Columns.Text2_1, "text2_1")
        Table.Columns.Add(NpcText_Columns.Lang2, "lang2")
        Table.Columns.Add(NpcText_Columns.em2_0, "em2_0")
        Table.Columns.Add(NpcText_Columns.em2_1, "em2_1")
        Table.Columns.Add(NpcText_Columns.em2_2, "em2_2")
        Table.Columns.Add(NpcText_Columns.em2_3, "em2_3")
        Table.Columns.Add(NpcText_Columns.em2_4, "em2_4")
        Table.Columns.Add(NpcText_Columns.em2_5, "em2_5")
        Table.Columns.Add(NpcText_Columns.Prob3, "prob3")
        Table.Columns.Add(NpcText_Columns.Text3_0, "text3_0")
        Table.Columns.Add(NpcText_Columns.Text3_1, "text3_1")
        Table.Columns.Add(NpcText_Columns.Lang3, "lang3")
        Table.Columns.Add(NpcText_Columns.em3_0, "em3_0")
        Table.Columns.Add(NpcText_Columns.em3_1, "em3_1")
        Table.Columns.Add(NpcText_Columns.em3_2, "em3_2")
        Table.Columns.Add(NpcText_Columns.em3_3, "em3_3")
        Table.Columns.Add(NpcText_Columns.em3_4, "em3_4")
        Table.Columns.Add(NpcText_Columns.em3_5, "em3_5")
        Table.Columns.Add(NpcText_Columns.Prob4, "prob4")
        Table.Columns.Add(NpcText_Columns.Text4_0, "text4_0")
        Table.Columns.Add(NpcText_Columns.Text4_1, "text4_1")
        Table.Columns.Add(NpcText_Columns.Lang4, "lang4")
        Table.Columns.Add(NpcText_Columns.em4_0, "em4_0")
        Table.Columns.Add(NpcText_Columns.em4_1, "em4_1")
        Table.Columns.Add(NpcText_Columns.em4_2, "em4_2")
        Table.Columns.Add(NpcText_Columns.em4_3, "em4_3")
        Table.Columns.Add(NpcText_Columns.em4_4, "em4_4")
        Table.Columns.Add(NpcText_Columns.em4_5, "em4_5")
        Table.Columns.Add(NpcText_Columns.Prob5, "prob5")
        Table.Columns.Add(NpcText_Columns.Text5_0, "text5_0")
        Table.Columns.Add(NpcText_Columns.Text5_1, "text5_1")
        Table.Columns.Add(NpcText_Columns.Lang5, "lang5")
        Table.Columns.Add(NpcText_Columns.em5_0, "em5_0")
        Table.Columns.Add(NpcText_Columns.em5_1, "em5_1")
        Table.Columns.Add(NpcText_Columns.em5_2, "em5_2")
        Table.Columns.Add(NpcText_Columns.em5_3, "em5_3")
        Table.Columns.Add(NpcText_Columns.em5_4, "em5_4")
        Table.Columns.Add(NpcText_Columns.em5_5, "em5_5")
        Table.Columns.Add(NpcText_Columns.Prob6, "prob6")
        Table.Columns.Add(NpcText_Columns.Text6_0, "text6_0")
        Table.Columns.Add(NpcText_Columns.Text6_1, "text6_1")
        Table.Columns.Add(NpcText_Columns.Lang6, "lang6")
        Table.Columns.Add(NpcText_Columns.em6_0, "em6_0")
        Table.Columns.Add(NpcText_Columns.em6_1, "em6_1")
        Table.Columns.Add(NpcText_Columns.em6_2, "em6_2")
        Table.Columns.Add(NpcText_Columns.em6_3, "em6_3")
        Table.Columns.Add(NpcText_Columns.em6_4, "em6_4")
        Table.Columns.Add(NpcText_Columns.em6_5, "em6_5")
        Table.Columns.Add(NpcText_Columns.Prob7, "prob7")
        Table.Columns.Add(NpcText_Columns.Text7_0, "text7_0")
        Table.Columns.Add(NpcText_Columns.Text7_1, "text7_1")
        Table.Columns.Add(NpcText_Columns.Lang7, "lang7")
        Table.Columns.Add(NpcText_Columns.em7_0, "em7_0")
        Table.Columns.Add(NpcText_Columns.em7_1, "em7_1")
        Table.Columns.Add(NpcText_Columns.em7_2, "em7_2")
        Table.Columns.Add(NpcText_Columns.em7_3, "em7_3")
        Table.Columns.Add(NpcText_Columns.em7_4, "em7_4")
        Table.Columns.Add(NpcText_Columns.em7_5, "em7_5")

        'Vendors
        Table = New TTable("vendors", TableTypes.NpcVendor)
        Tables.Add(Table)
        Table.Columns.Add(NpcVendor_Columns.Entry, "entry")
        Table.Columns.Add(NpcVendor_Columns.Item, "item")
        Table.Columns.Add(NpcVendor_Columns.Amount, "amount")
        Table.Columns.Add(NpcVendor_Columns.Stock, "max_amount")
        Table.Columns.Add(NpcVendor_Columns.Refill, "inctime")
        Table.Columns.Add(NpcVendor_Columns.ExtendedCost, "extended_cost")

        'Npc_Gossip_TextID
        Table = New TTable("npc_gossip_textid", TableTypes.NpcGossipTextID)
        Tables.Add(Table)
        Table.Columns.Add(NpcGossipTextID_Columns.Entry, "creatureid")
        Table.Columns.Add(NpcGossipTextID_Columns.TextID, "textid")

        'Trainer_Defs
        Table = New TTable("trainer_defs", TableTypes.NpcTrainerDefs)
        Tables.Add(Table)
        Table.Columns.Add(NpcTrainerDef_Columns.Entry, "entry")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqSkill, "required_skill")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqSkillValue, "required_skillvalue")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqClass, "req_class")
        Table.Columns.Add(NpcTrainerDef_Columns.ReqRace, "RequiredRace")
        Table.Columns.Add(NpcTrainerDef_Columns.RequiredReputation, "RequiredReputation")
        Table.Columns.Add(NpcTrainerDef_Columns.RequiredReputationValue, "RequiredReputationValue")
        Table.Columns.Add(NpcTrainerDef_Columns.TrainerType, "trainer_type")
        Table.Columns.Add(NpcTrainerDef_Columns.WindowMessage, "trainer_ui_window_message")
        Table.Columns.Add(NpcTrainerDef_Columns.CanTrainMessage, "can_train_gossip_textid")
        Table.Columns.Add(NpcTrainerDef_Columns.CanNotTrainMessage, "cannot_train_gossip_textid")

        'Trainer_Spells
        Table = New TTable("trainer_spells", TableTypes.NpcTrainerSpells)
        Tables.Add(Table)
        Table.Columns.Add(NpcTrainerSpell_Columns.Spell, "SpellID")
        Table.Columns.Add(NpcTrainerSpell_Columns.Entry, "creature_entry")

        'items_randomprop_groups
        Table = New TTable("item_randomprop_groups", TableTypes.ItemRandomPropGroups)
        Tables.Add(Table)
        Table.Columns.Add(ItemRandom_Props_Columns.ItemEntry, "entry_id")
        Table.Columns.Add(ItemRandom_Props_Columns.RandomPropsEntryID, "randomprops_entryid")
        Table.Columns.Add(ItemRandom_Props_Columns.Chance, "chance")

        'items_randomsuffix_groups
        Table = New TTable("item_randomsuffix_groups", TableTypes.ItemSuffixGroups)
        Tables.Add(Table)
        Table.Columns.Add(ItemRandom_Suffix_Columns.ItemEntry, "entry_id")
        Table.Columns.Add(ItemRandom_Suffix_Columns.RandomSuffixEntryID, "randomsuffix_entryid")
        Table.Columns.Add(ItemRandom_Suffix_Columns.Chance, "chance")

        'itempages
        Table = New TTable("itempages", TableTypes.ItemPages)
        Tables.Add(Table)
        Table.Columns.Add(ItemPages_Columns.ItemEntry, "entry")
        Table.Columns.Add(ItemPages_Columns.Text, "text")
        Table.Columns.Add(ItemPages_Columns.NextPage, "next_page")

        'itempetfood
        Table = New TTable("itempetfood", TableTypes.ItemPetFood)
        Tables.Add(Table)
        Table.Columns.Add(PetFood_Columns.ItemEntry, "entry")
        Table.Columns.Add(PetFood_Columns.FoodType, "food_type")

        'PlayerCreateInfo
        Table = New TTable("playercreateinfo", TableTypes.PlayerCreateInfo)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfo_Columns.Index, "Index")
        Table.Columns.Add(PlayerCreateInfo_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfo_Columns.FactionTemplate, "factiontemplate")
        Table.Columns.Add(PlayerCreateInfo_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfo_Columns.MapID, "mapID")
        Table.Columns.Add(PlayerCreateInfo_Columns.ZoneID, "zoneID")
        Table.Columns.Add(PlayerCreateInfo_Columns.PositionX, "positionX")
        Table.Columns.Add(PlayerCreateInfo_Columns.PositionY, "positionY")
        Table.Columns.Add(PlayerCreateInfo_Columns.PositionZ, "positionZ")
        Table.Columns.Add(PlayerCreateInfo_Columns.DisplayID, "displayID")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseStrength, "BaseStrength")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseAgility, "BaseAgility")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseStamina, "BaseStamina")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseIntellect, "BaseIntellect")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseSpirit, "BaseSpirit")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseHealth, "BaseHealth")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseMana, "BaseMana")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseRage, "BaseRage")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseFocus, "BaseFocus")
        Table.Columns.Add(PlayerCreateInfo_Columns.BaseEnergy, "BaseEnergy")
        Table.Columns.Add(PlayerCreateInfo_Columns.AttackPower, "attackpower")
        Table.Columns.Add(PlayerCreateInfo_Columns.MinDmg, "mindmg")
        Table.Columns.Add(PlayerCreateInfo_Columns.MaxDmg, "maxdmg")
        Table.Columns.Add(PlayerCreateInfo_Columns.IntroID, "introid")
        Table.Columns.Add(PlayerCreateInfo_Columns.TaxiMask, "taximask")

        'PlayerCreateInfo_Bars
        Table = New TTable("playercreateinfo_bars", TableTypes.PlayerCreateInfo_Bars)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Race, "race")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Classe, "class")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Button, "button")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Action, "action")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Type, "type")
        Table.Columns.Add(PlayerCreateInfoBar_Columns.Misc, "misc")

        'PlayerCreateInfo_Items
        Table = New TTable("playercreateinfo_items", TableTypes.PlayerCreateInfo_Items)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoItem_Columns.IndexID, "indexid")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.ProtoID, "protoid")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.SlotID, "slotid")
        Table.Columns.Add(PlayerCreateInfoItem_Columns.Amount, "amount")

        'PlayerCreateInfo_Skills
        Table = New TTable("playercreateinfo_skills", TableTypes.PlayerCreateInfo_Skills)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.IndexID, "indexid")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.SkillID, "skillid")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.Level, "level")
        Table.Columns.Add(PlayerCreateInfoSkill_Columns.MaxLevel, "maxlevel")

        'PlayerCreateInfo_Spells
        Table = New TTable("playercreateinfo_spells", TableTypes.PlayerCreateInfo_Spells)
        Tables.Add(Table)
        Table.Columns.Add(PlayerCreateInfoSpell_Columns.IndexID, "indexid")
        Table.Columns.Add(PlayerCreateInfoSpell_Columns.SpellID, "spellid")

        'Npc_MonsterSay
        Table = New TTable("npc_monstersay", TableTypes.MonsterSay)
        Tables.Add(Table)
        Table.Columns.Add(MonsterSay_Columns.Entry, "entry")
        Table.Columns.Add(MonsterSay_Columns.Evente, "event")
        Table.Columns.Add(MonsterSay_Columns.Chance, "chance")
        Table.Columns.Add(MonsterSay_Columns.Language, "language")
        Table.Columns.Add(MonsterSay_Columns.Type, "type")
        Table.Columns.Add(MonsterSay_Columns.MonsterName, "monstername")
        Table.Columns.Add(MonsterSay_Columns.Text0, "text0")
        Table.Columns.Add(MonsterSay_Columns.Text1, "text1")
        Table.Columns.Add(MonsterSay_Columns.Text2, "text2")
        Table.Columns.Add(MonsterSay_Columns.Text3, "text3")
        Table.Columns.Add(MonsterSay_Columns.Text4, "text4")

        'Recall
        Table = New TTable("recall", TableTypes.CmdTeleports)
        Tables.Add(Table)
        Table.Columns.Add(CmdTeleports_Columns.Id, "id")
        Table.Columns.Add(CmdTeleports_Columns.Name, "name")
        Table.Columns.Add(CmdTeleports_Columns.MapID, "MapId")
        Table.Columns.Add(CmdTeleports_Columns.PositionX, "positionX")
        Table.Columns.Add(CmdTeleports_Columns.PositionY, "positionY")
        Table.Columns.Add(CmdTeleports_Columns.PositionZ, "positionZ")
        Table.Columns.Add(CmdTeleports_Columns.Orientation, "Orientation")

        'Creature_Waypoints
        Table = New TTable("creature_waypoints", TableTypes.creature_movement)
        Tables.Add(Table)
        Table.Columns.Add(Creature_Movement_Columns.spawnid, "spawnid")
        Table.Columns.Add(Creature_Movement_Columns.waypointid, "waypointid")
        Table.Columns.Add(Creature_Movement_Columns.position_x, "position_x")
        Table.Columns.Add(Creature_Movement_Columns.position_y, "position_y")
        Table.Columns.Add(Creature_Movement_Columns.position_z, "position_z")
        Table.Columns.Add(Creature_Movement_Columns.waittime, "waittime")
        Table.Columns.Add(Creature_Movement_Columns.flags, "flags")
        Table.Columns.Add(Creature_Movement_Columns.emote, "forwardemoteid")
        'Table.Columns.Add(Creature_Movement_Columns.orientation, "0")

    End Sub

End Class
